syntax="proto3";
package zds;

option go_package = "zpr.org/vs/pkg/snio/zds";

// ============================================================================
// Implementation Notes
//
// 1. Beware the leaking of sensitive information
//
//    Unrestricted use of the datasource API may result in sensitive data being
//    returned to the caller.  An implementation should take steps to restrict
//    the queries such that only appropriate information is returned.  For
//    example, it would make sense to restrict queries to only keys known to be
//    used in ZPR policy.
//
// 2. Beware of excessively short TTL or expiration
//
//    ZPR will not issue visas with a TTL longer than the shortest TLL returned
//    from a related datasource.  Since a preponderance of short lifetime visas
//    will degrade ZPR performance, an implementation should strive to keep TTLs
//    as long as possible.
//
// ============================================================================



// ----------------------------------------------------------------------------
// ZDS defines the validation and data source API. Validation functions start
// with an 'A', data source methods start with a 'D'.
//
// A given endpoint may support the Axxx methods, the Dxxx methods or both.
// What exactly is supported is expressed in the policy, but the API also
// allows for the return of the UNIMPLEMENTED status code.
//
// Responses from API calls include a TTL which is intended as a caching guide
// for ZPR.  The TTL value is a duration expressed in seconds. ZPR is allowed to
// cache the results of the call for at most TTL seconds. A TTL value of zero
// means that no caching should be performed.
//
// Attributes have expiration values. These are absolute time values expressed
// in seconds (unix seconds since the epoch).  ZPR can cache and make use of the
// values of attributes (for a subject) until they expire.
//
// ----------------------------------------------------------------------------
service ZDS {

    // ------------------------------------------------------------------------
    // Axxx is the data source authentication API.
    // ------------------------------------------------------------------------
    //
    // There are two operations: one to validate and another to extend a
    // previous validation.
    //
    // ------------------------------------------------------------------------

    // AValidate validates a challenge response from an agent.
    // This is called when an agent is connecting to the network, or during a
    // re-authentication.
    //
    // If AValidate is not supported, the UNIMPLEMENTED status code should
    // be returned.
    rpc AValidate(ValidateRequest) returns (ValidateResponse) {}

    // ARefresh requests an extension of a previous validation.
    rpc ARefresh(RefreshRequest) returns (RefreshResponse) {}


    // ------------------------------------------------------------------------
    // Dxxx is the data source attribute API.
    // ------------------------------------------------------------------------
    //
    // The API has two endpoints:
    //
    // 1) A query that returns the value of a specific set of attributes for
    //    an agent.
    // 2) A "satisfy" operation that returns the set of user identifiers that
    //    satisfy a set of attributes.
    //
    // When datasource responses return attributes, the attributes are typles of
    // the form (KEY, VALUE, EXPIRATION). When the attributes are processed by
    // ZPR, a namespace (as defined in policy) is added to the keys. So if a
    // datasource returns (userid, 22, 0) in ZPR this may become
    // (ds1.userid, 22. 0). The datasource is not expected to be aware of its
    // policy namespace.
    //
    // User identifiers (also called subjects) are expected to be strings which
    // can be compared for equality and to the "sub" valies in the
    // authentication tokens returned by the AValidate function.
    //
    // The authentication endpoint can return datasource style attributes
    // through the "attrs" field on the ValidateResponse struct.
    //
    // Attribute valies are generally opaque strings to ZPR, but in the case of
    // the set operations, they are interpreted as a comma separated list of
    // strings.
    //
    // ZPR does not assume that attribute keys are actually implemented as
    // "properties".  The datasource can interpret the keys and values as it
    // sees fit.  For example, a key could invoke a function on a datasource.
    //
    // ------------------------------------------------------------------------

    // DQuery returns the value of a specific set of attributes for an agent.
    // This may be called during visa request processing.
    //
    // If DQuery is not supported, the UNIMPLEMENTED status code should be
    // returned.
    rpc DQuery(QueryRequest) returns (QueryResponse) {}

    // DSatisfy query a datasource for subjects matching attribute expressions.
    // This is called during dynamic assertion checking. At the moment this is
    // not called by the visa service (since assertion checking is a compile
    // step).
    //
    // If DSatisfy is not supported, the UNIMPLEMENTED status code should be
    // returned.
    rpc DSatisfy(SatisfyRequest) returns (SatisfyResponse) {}
}

// Challenge is the initial challenge.  This is generated by ZPR. The challenge
// is a buffer of random bytes which is designed to be large enough to satisfy
// common cryptography requirements.  When the ZPR challenge is insufficient,
// the authentication service must use the NEEDS_MORE response status to send
// their own challenge to the agent.
//
message Challenge {
    string spec      = 1;  // A string identifying the challenge type, this is
                           // interpreted by the adapter.
    string timestamp = 2;  // Timestamp that challenge was generated (RFC3339).
    bytes nonce      = 3;  // Random bytes to be used by the agent to respond.
    bytes data       = 4;  // Optional additional bytes if needed for the
                           // challenge type.
}

// ValidateRequest is the argument to AValidate.
message ValidateRequest {
    Challenge chal                       = 1;  // A copy of the challenge sent to the agent.
    repeated ChallengeResponse cresp_set = 2;  // A the response details, created by the adapter based on the challenge
                                               // type. This is a flexible structure mostly opaque to ZPR.
    map<string,string> claims            = 3;  // All the claims sent by the adapter.
    map<string, string> conf             = 4;  // Optional configuration data from policy.
    bytes challenger_addr                = 5;  // Node which requested the challenge (IP address)
}


// The ultimate result of a call to AValidate is the generation of an identity
// token and an (initial) set of attributes.
//
// The JWT token returned by a successful call to validate has the following
// required fields:
//
//   sub   Must be set to the agent identifier. A particular identifier must
//         always be maped to the same agent within a given ZPR network.
//
//   exp   Must be set to the expiration of the auth token. This may be
//         reduced by policy.  (unix time seconds)
//
//   iss   Must be the same for every token issued by a given validation
//         service.
//
//   aud   Must be set to "zpr".
//
//   nbf   Must be set to valid Not-Before timestamp as specified in RFC7519.
//         (unix time seconds)
//
//   iat   Must be set to issue date (unix time seconds)
//
//   jti   The ID of this token. Set as described in RFC7519.
//
// In addition the signature on the token must match the certificate specified
// in policy for the validation service.
//
message ValidateResponse {
    enum Status {
        FAIL      = 0;  // Validation has failed
        SUCCESS   = 1;  // Validation has succeeded
        NEED_MORE = 2;  // More data is needed to perform validation
    }
    Status stat               = 1;  // One of the status codes above.
    string error              = 2;  // Used for ZPR logging purposes
    uint32 ttl                = 3;  // Time-to-live value in seconds for this RPC result.

    bytes token               = 4;  // A JWT (RFC7519) token, signed by validation service attesting to
                                    // successful validation. See details above.

    repeated Attribute attrs  = 5;  // The list of validated claims and additional attributes to associate
                                    // with the agent.

    Challenge follow_on       = 6;  // If NEEDS_MORE is set, this is an AuthChallenge structure to
                                    // send to the agent for an additional response..
}

// RefreshRequest is the argument to the ARefresh call.
message RefreshRequest {
    bytes token = 1;  // The token returned from a previously successful call to Validate.
}

message RefreshResponse {
    bool success = 1;  // If false, then refresh is denied and a new Validation call must be made.
    bytes token  = 2;  // If success is true, this is a new token (presumably with a new expiration date).
}

// QueryRequest is the argument to the DQuery call.
message QueryRequest {
    repeated bytes token_list = 1;  // A list of the JWT tokens associated with the agent.
                                    // The tokens come from validation services.

    repeated string attr_keys = 2; // A list of attribute keys to query for.
}

message QueryResponse {
    repeated Attribute attrs = 1;  // A list of result attributes that apply to the agent and match
                                   // the keys sent in the query request. If the agent is unknown
                                   // to the validation service, it should return an empty.
                                   // 
                                   // There must be no duplicate Attribute.key values in this list.
                                   // If the agent has multiple values for an attribute then the
                                   // values should be returned as a single, comma-separated value.
                                   // Eg, 
                                   //    Attribute {
                                   //      key: "group",
                                   //      value: "it, managers, project_blue"
                                   //    }                                   

    uint32 ttl               = 2;  // Time-to-live value in seconds for caching of this RPC call.
}

// SatisfyRequest is the argument to the DSatisfy call.
message SatisfyRequest {
    repeated AttributeExpression query_exp = 1; // A list of attribute-expression values to query for.
}

message SatisfyResponse {
    repeated string subjects = 1; // List of subject identifiers which satisfy the request.
                                  // (TODO: This could be a large list, should we support some sort of cursor/pagination?)
    uint32 ttl               = 2; // Time-to-live (seconds) for the result.
}


message Attribute {
    string key = 1;
    string val = 2;
    int64 exp  = 3; // unix time seconds
}


// An "attribute-expression" is a 3-tuple of the form (key, operator, value).
// These expressions appear in ZPL too.
//
message AttributeExpression {
    enum OPER {
       UNDEF    = 0;
       EQ       = 1; // String comparison
       NEQ      = 2; // String comparison

       HAS      = 3; // (A, HAS, V) means:
                     //    - read subject attribute A as a string
                     //    - split the string using ","
                     //    - if one of the resultant parts equals V, return true
                     //    - else false

       EXCLUDES = 4; // (A, EXCLUDES, V) means:
                     //    - read subject attribute A as a string
                     //    - split the string using ","
                     //    - if none of the resultant parts equals V, return true
                     //    - else return false
    }
    string key = 1;
    OPER op    = 2;
    string val = 3;
}


// ChallengeResponse data is generated by adapters in response to a challenge.
// This is consumed by the validation services to verify identity.
//
// TODO: Just like the old AuthRespBlock but lacking the encoding -- what was that for anyway?
message ChallengeResponse {
    string chal_spec     = 1; // Identifies the challenge type.
    string resp_spec     = 2; // Identifies the response type.
    uint32 nonce_offset  = 3; // Describe the part of the nonce we used (offset)
    uint32 nonce_len     = 4; // Describe the part of the nonce we used (length)
    oneof result {
      RawChalResp cr_raw = 5; // just an opaque byte buffer
      U2FChalResp cr_u2f = 6; // the u2f crypto response
    }
    bytes certificate    = 7; // optional, depends on chal_spec and resp_spec.
}

message RawChalResp {
    bytes data = 1; // Very simple, just raw bytes.
}

// U2fChalResp represents an ECDSA signature performed by a U2F device.
message U2FChalResp {
    bytes sig_r    = 1;
    bytes sig_s    = 2;
    uint32 counter = 3;
}
