# Example configuration file for visa service.
# (work in progress)


# transport credentials to use for our visa service service.
vs_cert: node-cert.pem
vs_key: node.key


# Enable verbose logging
# verbose: true
