use chrono::{DateTime, SecondsFormat, Utc};
use colored::{Color, Colorize};
use serde::{Deserialize, Serialize};
use std::fmt;

#[derive(Deserialize)]
pub struct PolicyListEntry {
    pub config_id: u64,
    pub version: String,
}

#[derive(Serialize)]
pub struct PolicyBundle {
    pub config_id: u64,  // ignored when installing
    pub version: String, // use empty string if you don't care
    pub format: String,
    pub container: String,
}

#[derive(Deserialize)]
pub struct VisaDescriptor {
    pub id: u64,
    pub expires: u64, // milliseconds since the epoch
    pub source: String,
    pub dest: String,
}

#[derive(Deserialize)]
#[allow(dead_code)]
pub struct HostRecordBrief {
    ctime: i64, // unix SECONDS (not millis)
    cn: String,
    zpr_addr: String,
    ident: String,
    node: bool,
}

impl fmt::Display for VisaDescriptor {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let now = Utc::now();

        let exp_secs = (self.expires / 1000) as i64;
        let exp_nanos = ((self.expires % 1000) * 1_000_000) as u32;

        let dt: DateTime<Utc> = DateTime::from_timestamp(exp_secs, exp_nanos).unwrap();
        let remain = dt.signed_duration_since(now);
        write!(
            f,
            "visa id {} [{}]->[{}] expires {} ({}d:{}h:{}m:{}s remaining)",
            self.id,
            self.source,
            self.dest,
            dt.to_rfc3339_opts(SecondsFormat::Millis, true),
            remain.num_days(),
            remain.num_hours() % 24,
            remain.num_minutes() % 60,
            remain.num_seconds() % 60,
        )
    }
}

impl fmt::Display for HostRecordBrief {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let ts: DateTime<Utc> = DateTime::from_timestamp(self.ctime, 0).unwrap();
        write!(
            f,
            "<{}> {} (created: {}) @ {}",
            if self.node { "node" } else { "agnt" },
            self.cn,
            ts.to_rfc3339_opts(SecondsFormat::Secs, true),
            self.zpr_addr,
        )
    }
}

// Not exactly an api type, but the version generated by the compiler has some parts
// to it separated by colons.  This splits them up and makes it possible to pretty
// print.
pub struct PolicyVersion {
    parts: Vec<String>,
}

impl PolicyVersion {
    pub fn new(version: &str) -> Self {
        PolicyVersion {
            parts: version.split(':').map(|s| s.to_string()).collect(),
        }
    }
}

impl fmt::Display for PolicyVersion {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let colors = [Color::Cyan, Color::Green, Color::Blue, Color::BrightBlue];
        for (i, part) in self.parts.iter().enumerate() {
            if i > 0 {
                write!(f, "{}", ":".bold())?;
            }
            write!(f, "{}", part.color(colors[i % 4]))?;
        }
        Ok(())
    }
}
