// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: vsio/vservice.proto

package vsio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	VisaService_Register_FullMethodName         = "/vsio.VisaService/Register"
	VisaService_DeRegister_FullMethodName       = "/vsio.VisaService/DeRegister"
	VisaService_AuthorizeConnect_FullMethodName = "/vsio.VisaService/AuthorizeConnect"
	VisaService_RequestVisa_FullMethodName      = "/vsio.VisaService/RequestVisa"
	VisaService_SubmitStats_FullMethodName      = "/vsio.VisaService/SubmitStats"
	VisaService_Poll_FullMethodName             = "/vsio.VisaService/Poll"
	VisaService_GetTopology_FullMethodName      = "/vsio.VisaService/GetTopology"
	VisaService_HostAdded_FullMethodName        = "/vsio.VisaService/HostAdded"
	VisaService_HostRemoved_FullMethodName      = "/vsio.VisaService/HostRemoved"
)

// VisaServiceClient is the client API for VisaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisaServiceClient interface {
	// A node must register with the visa service before calling any other functions.
	Register(ctx context.Context, in *VSRegisterRequest, opts ...grpc.CallOption) (*VSRegisterResponse, error)
	// A node should de-register before exiting (but this is optional)
	DeRegister(ctx context.Context, in *VSDeRegisterRequest, opts ...grpc.CallOption) (*VSDeRegisterResponse, error)
	// Authorize a connection to ZPRnet
	AuthorizeConnect(ctx context.Context, in *VSConnectRequest, opts ...grpc.CallOption) (*VSConnectResponse, error)
	// Note that for a given visa service instance, the visa issuer IDs should be increasing.
	RequestVisa(ctx context.Context, in *VSRequest, opts ...grpc.CallOption) (*VSResponse, error)
	// Nodes periodically submit stats on constraint counters.
	SubmitStats(ctx context.Context, in *VSStatsRequest, opts ...grpc.CallOption) (*VSStatsResponse, error)
	// Nodes should poll in case there are messages pushed out by visa service.
	Poll(ctx context.Context, in *VSPollRequest, opts ...grpc.CallOption) (*VSPollResponse, error)
	// Get the network topology relevant to the requestor based on current policy.
	GetTopology(ctx context.Context, in *VSTopoRequest, opts ...grpc.CallOption) (*VSTopoResponse, error)
	// Docking node notify visa service of new "service" host connection.
	HostAdded(ctx context.Context, in *VSHostAddRequest, opts ...grpc.CallOption) (*VSHostAddResponse, error)
	// Docking node notify visa service of removed "service" host connection.
	HostRemoved(ctx context.Context, in *VSHostRemoveRequest, opts ...grpc.CallOption) (*VSHostRemoveResponse, error)
}

type visaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisaServiceClient(cc grpc.ClientConnInterface) VisaServiceClient {
	return &visaServiceClient{cc}
}

func (c *visaServiceClient) Register(ctx context.Context, in *VSRegisterRequest, opts ...grpc.CallOption) (*VSRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSRegisterResponse)
	err := c.cc.Invoke(ctx, VisaService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceClient) DeRegister(ctx context.Context, in *VSDeRegisterRequest, opts ...grpc.CallOption) (*VSDeRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSDeRegisterResponse)
	err := c.cc.Invoke(ctx, VisaService_DeRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceClient) AuthorizeConnect(ctx context.Context, in *VSConnectRequest, opts ...grpc.CallOption) (*VSConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSConnectResponse)
	err := c.cc.Invoke(ctx, VisaService_AuthorizeConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceClient) RequestVisa(ctx context.Context, in *VSRequest, opts ...grpc.CallOption) (*VSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSResponse)
	err := c.cc.Invoke(ctx, VisaService_RequestVisa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceClient) SubmitStats(ctx context.Context, in *VSStatsRequest, opts ...grpc.CallOption) (*VSStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSStatsResponse)
	err := c.cc.Invoke(ctx, VisaService_SubmitStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceClient) Poll(ctx context.Context, in *VSPollRequest, opts ...grpc.CallOption) (*VSPollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSPollResponse)
	err := c.cc.Invoke(ctx, VisaService_Poll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceClient) GetTopology(ctx context.Context, in *VSTopoRequest, opts ...grpc.CallOption) (*VSTopoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSTopoResponse)
	err := c.cc.Invoke(ctx, VisaService_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceClient) HostAdded(ctx context.Context, in *VSHostAddRequest, opts ...grpc.CallOption) (*VSHostAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSHostAddResponse)
	err := c.cc.Invoke(ctx, VisaService_HostAdded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceClient) HostRemoved(ctx context.Context, in *VSHostRemoveRequest, opts ...grpc.CallOption) (*VSHostRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VSHostRemoveResponse)
	err := c.cc.Invoke(ctx, VisaService_HostRemoved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisaServiceServer is the server API for VisaService service.
// All implementations must embed UnimplementedVisaServiceServer
// for forward compatibility
type VisaServiceServer interface {
	// A node must register with the visa service before calling any other functions.
	Register(context.Context, *VSRegisterRequest) (*VSRegisterResponse, error)
	// A node should de-register before exiting (but this is optional)
	DeRegister(context.Context, *VSDeRegisterRequest) (*VSDeRegisterResponse, error)
	// Authorize a connection to ZPRnet
	AuthorizeConnect(context.Context, *VSConnectRequest) (*VSConnectResponse, error)
	// Note that for a given visa service instance, the visa issuer IDs should be increasing.
	RequestVisa(context.Context, *VSRequest) (*VSResponse, error)
	// Nodes periodically submit stats on constraint counters.
	SubmitStats(context.Context, *VSStatsRequest) (*VSStatsResponse, error)
	// Nodes should poll in case there are messages pushed out by visa service.
	Poll(context.Context, *VSPollRequest) (*VSPollResponse, error)
	// Get the network topology relevant to the requestor based on current policy.
	GetTopology(context.Context, *VSTopoRequest) (*VSTopoResponse, error)
	// Docking node notify visa service of new "service" host connection.
	HostAdded(context.Context, *VSHostAddRequest) (*VSHostAddResponse, error)
	// Docking node notify visa service of removed "service" host connection.
	HostRemoved(context.Context, *VSHostRemoveRequest) (*VSHostRemoveResponse, error)
	mustEmbedUnimplementedVisaServiceServer()
}

// UnimplementedVisaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVisaServiceServer struct {
}

func (UnimplementedVisaServiceServer) Register(context.Context, *VSRegisterRequest) (*VSRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedVisaServiceServer) DeRegister(context.Context, *VSDeRegisterRequest) (*VSDeRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeRegister not implemented")
}
func (UnimplementedVisaServiceServer) AuthorizeConnect(context.Context, *VSConnectRequest) (*VSConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeConnect not implemented")
}
func (UnimplementedVisaServiceServer) RequestVisa(context.Context, *VSRequest) (*VSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVisa not implemented")
}
func (UnimplementedVisaServiceServer) SubmitStats(context.Context, *VSStatsRequest) (*VSStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitStats not implemented")
}
func (UnimplementedVisaServiceServer) Poll(context.Context, *VSPollRequest) (*VSPollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedVisaServiceServer) GetTopology(context.Context, *VSTopoRequest) (*VSTopoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedVisaServiceServer) HostAdded(context.Context, *VSHostAddRequest) (*VSHostAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostAdded not implemented")
}
func (UnimplementedVisaServiceServer) HostRemoved(context.Context, *VSHostRemoveRequest) (*VSHostRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostRemoved not implemented")
}
func (UnimplementedVisaServiceServer) mustEmbedUnimplementedVisaServiceServer() {}

// UnsafeVisaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisaServiceServer will
// result in compilation errors.
type UnsafeVisaServiceServer interface {
	mustEmbedUnimplementedVisaServiceServer()
}

func RegisterVisaServiceServer(s grpc.ServiceRegistrar, srv VisaServiceServer) {
	s.RegisterService(&VisaService_ServiceDesc, srv)
}

func _VisaService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).Register(ctx, req.(*VSRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaService_DeRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSDeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).DeRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_DeRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).DeRegister(ctx, req.(*VSDeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaService_AuthorizeConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).AuthorizeConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_AuthorizeConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).AuthorizeConnect(ctx, req.(*VSConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaService_RequestVisa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).RequestVisa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_RequestVisa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).RequestVisa(ctx, req.(*VSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaService_SubmitStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).SubmitStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_SubmitStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).SubmitStats(ctx, req.(*VSStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaService_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_Poll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).Poll(ctx, req.(*VSPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaService_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSTopoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).GetTopology(ctx, req.(*VSTopoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaService_HostAdded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSHostAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).HostAdded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_HostAdded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).HostAdded(ctx, req.(*VSHostAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaService_HostRemoved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VSHostRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceServer).HostRemoved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaService_HostRemoved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceServer).HostRemoved(ctx, req.(*VSHostRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisaService_ServiceDesc is the grpc.ServiceDesc for VisaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vsio.VisaService",
	HandlerType: (*VisaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _VisaService_Register_Handler,
		},
		{
			MethodName: "DeRegister",
			Handler:    _VisaService_DeRegister_Handler,
		},
		{
			MethodName: "AuthorizeConnect",
			Handler:    _VisaService_AuthorizeConnect_Handler,
		},
		{
			MethodName: "RequestVisa",
			Handler:    _VisaService_RequestVisa_Handler,
		},
		{
			MethodName: "SubmitStats",
			Handler:    _VisaService_SubmitStats_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _VisaService_Poll_Handler,
		},
		{
			MethodName: "GetTopology",
			Handler:    _VisaService_GetTopology_Handler,
		},
		{
			MethodName: "HostAdded",
			Handler:    _VisaService_HostAdded_Handler,
		},
		{
			MethodName: "HostRemoved",
			Handler:    _VisaService_HostRemoved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vsio/vservice.proto",
}
