// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: vsio/vservice.proto

package vsio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	zds "zpr.org/vs/pkg/snio/zds"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VSRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeAddr []byte `protobuf:"bytes,1,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"` // ZPR address of the node
}

func (x *VSRegisterRequest) Reset() {
	*x = VSRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSRegisterRequest) ProtoMessage() {}

func (x *VSRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSRegisterRequest.ProtoReflect.Descriptor instead.
func (*VSRegisterRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{0}
}

func (x *VSRegisterRequest) GetNodeAddr() []byte {
	if x != nil {
		return x.NodeAddr
	}
	return nil
}

type VSRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // TODO: could return an access_token here and then use it in all future calls from the node.
}

func (x *VSRegisterResponse) Reset() {
	*x = VSRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSRegisterResponse) ProtoMessage() {}

func (x *VSRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSRegisterResponse.ProtoReflect.Descriptor instead.
func (*VSRegisterResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{1}
}

func (x *VSRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// VSDeRegisterRequest is a polite "goodbye" message and is optional.
type VSDeRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeAddr []byte `protobuf:"bytes,1,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"` // ZPR address of the node
}

func (x *VSDeRegisterRequest) Reset() {
	*x = VSDeRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSDeRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSDeRegisterRequest) ProtoMessage() {}

func (x *VSDeRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSDeRegisterRequest.ProtoReflect.Descriptor instead.
func (*VSDeRegisterRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{2}
}

func (x *VSDeRegisterRequest) GetNodeAddr() []byte {
	if x != nil {
		return x.NodeAddr
	}
	return nil
}

type VSDeRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *VSDeRegisterResponse) Reset() {
	*x = VSDeRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSDeRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSDeRegisterResponse) ProtoMessage() {}

func (x *VSDeRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSDeRegisterResponse.ProtoReflect.Descriptor instead.
func (*VSDeRegisterResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{3}
}

func (x *VSDeRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VSConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DockAddr  []byte                   `protobuf:"bytes,1,opt,name=dock_addr,json=dockAddr,proto3" json:"dock_addr,omitempty"` // dock ZPR address
	ConId     string                   `protobuf:"bytes,2,opt,name=con_id,json=conId,proto3" json:"con_id,omitempty"`          // unique (to caller) connection identifier
	ReqAddr   []byte                   `protobuf:"bytes,3,opt,name=req_addr,json=reqAddr,proto3" json:"req_addr,omitempty"`    // set if connecting entity has requested an address
	Claims    map[string]string        `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Chal      *zds.Challenge           `protobuf:"bytes,5,opt,name=chal,proto3" json:"chal,omitempty"`
	ChalResp  []*zds.ChallengeResponse `protobuf:"bytes,6,rep,name=chal_resp,json=chalResp,proto3" json:"chal_resp,omitempty"`
	Token     []byte                   `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"` // to use node-agent (originates through visa support)
	NodeAgent *Agent                   `protobuf:"bytes,8,opt,name=node_agent,json=nodeAgent,proto3" json:"node_agent,omitempty"`
}

func (x *VSConnectRequest) Reset() {
	*x = VSConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSConnectRequest) ProtoMessage() {}

func (x *VSConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSConnectRequest.ProtoReflect.Descriptor instead.
func (*VSConnectRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{4}
}

func (x *VSConnectRequest) GetDockAddr() []byte {
	if x != nil {
		return x.DockAddr
	}
	return nil
}

func (x *VSConnectRequest) GetConId() string {
	if x != nil {
		return x.ConId
	}
	return ""
}

func (x *VSConnectRequest) GetReqAddr() []byte {
	if x != nil {
		return x.ReqAddr
	}
	return nil
}

func (x *VSConnectRequest) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *VSConnectRequest) GetChal() *zds.Challenge {
	if x != nil {
		return x.Chal
	}
	return nil
}

func (x *VSConnectRequest) GetChalResp() []*zds.ChallengeResponse {
	if x != nil {
		return x.ChalResp
	}
	return nil
}

func (x *VSConnectRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *VSConnectRequest) GetNodeAgent() *Agent {
	if x != nil {
		return x.NodeAgent
	}
	return nil
}

type VSConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConId    string `protobuf:"bytes,1,opt,name=con_id,json=conId,proto3" json:"con_id,omitempty"`          // copied from request
	Success  bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                  // FALSE if connect fails
	ErrorMsg string `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"` // May be set if success == FALSE
	Agent    *Agent `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`                       // nil if connect fails
}

func (x *VSConnectResponse) Reset() {
	*x = VSConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSConnectResponse) ProtoMessage() {}

func (x *VSConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSConnectResponse.ProtoReflect.Descriptor instead.
func (*VSConnectResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{5}
}

func (x *VSConnectResponse) GetConId() string {
	if x != nil {
		return x.ConId
	}
	return ""
}

func (x *VSConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VSConnectResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *VSConnectResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type VSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcTetherAddr []byte      `protobuf:"bytes,1,opt,name=src_tether_addr,json=srcTetherAddr,proto3" json:"src_tether_addr,omitempty"`
	Traffic       *PacketDesc `protobuf:"bytes,2,opt,name=traffic,proto3" json:"traffic,omitempty"`
}

func (x *VSRequest) Reset() {
	*x = VSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSRequest) ProtoMessage() {}

func (x *VSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSRequest.ProtoReflect.Descriptor instead.
func (*VSRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{6}
}

func (x *VSRequest) GetSrcTetherAddr() []byte {
	if x != nil {
		return x.SrcTetherAddr
	}
	return nil
}

func (x *VSRequest) GetTraffic() *PacketDesc {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type VSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                  // If TRUE visa will be non-nil
	ErrorMsg string     `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"` // Optionally set if success == FALSE
	Visa     *VSVisaHop `protobuf:"bytes,3,opt,name=visa,proto3" json:"visa,omitempty"`                         // Set if request has succeeded
}

func (x *VSResponse) Reset() {
	*x = VSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSResponse) ProtoMessage() {}

func (x *VSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSResponse.ProtoReflect.Descriptor instead.
func (*VSResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{7}
}

func (x *VSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VSResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *VSResponse) GetVisa() *VSVisaHop {
	if x != nil {
		return x.Visa
	}
	return nil
}

type VSStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssuerId  uint32 `protobuf:"varint,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	CapKey    string `protobuf:"bytes,2,opt,name=cap_key,json=capKey,proto3" json:"cap_key,omitempty"`
	BytesUsed uint64 `protobuf:"varint,3,opt,name=bytes_used,json=bytesUsed,proto3" json:"bytes_used,omitempty"`
}

func (x *VSStatsRequest) Reset() {
	*x = VSStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSStatsRequest) ProtoMessage() {}

func (x *VSStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSStatsRequest.ProtoReflect.Descriptor instead.
func (*VSStatsRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{8}
}

func (x *VSStatsRequest) GetIssuerId() uint32 {
	if x != nil {
		return x.IssuerId
	}
	return 0
}

func (x *VSStatsRequest) GetCapKey() string {
	if x != nil {
		return x.CapKey
	}
	return ""
}

func (x *VSStatsRequest) GetBytesUsed() uint64 {
	if x != nil {
		return x.BytesUsed
	}
	return 0
}

type VSStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VSStatsResponse) Reset() {
	*x = VSStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSStatsResponse) ProtoMessage() {}

func (x *VSStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSStatsResponse.ProtoReflect.Descriptor instead.
func (*VSStatsResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{9}
}

// Dock polling visa service for any messages.
type VSPollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DockAddr []byte `protobuf:"bytes,1,opt,name=dock_addr,json=dockAddr,proto3" json:"dock_addr,omitempty"`
}

func (x *VSPollRequest) Reset() {
	*x = VSPollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSPollRequest) ProtoMessage() {}

func (x *VSPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSPollRequest.ProtoReflect.Descriptor instead.
func (*VSPollRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{10}
}

func (x *VSPollRequest) GetDockAddr() []byte {
	if x != nil {
		return x.DockAddr
	}
	return nil
}

type VSPollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Visas   []*VSVisaHop    `protobuf:"bytes,1,rep,name=visas,proto3" json:"visas,omitempty"`
	Revokes []*VSRevocation `protobuf:"bytes,2,rep,name=revokes,proto3" json:"revokes,omitempty"`
	More    bool            `protobuf:"varint,3,opt,name=more,proto3" json:"more,omitempty"` // TRUE means there are yet more messages
}

func (x *VSPollResponse) Reset() {
	*x = VSPollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSPollResponse) ProtoMessage() {}

func (x *VSPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSPollResponse.ProtoReflect.Descriptor instead.
func (*VSPollResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{11}
}

func (x *VSPollResponse) GetVisas() []*VSVisaHop {
	if x != nil {
		return x.Visas
	}
	return nil
}

func (x *VSPollResponse) GetRevokes() []*VSRevocation {
	if x != nil {
		return x.Revokes
	}
	return nil
}

func (x *VSPollResponse) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

type VSTopoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeAddr      []byte `protobuf:"bytes,1,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	PolicyVersion uint64 `protobuf:"varint,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
}

func (x *VSTopoRequest) Reset() {
	*x = VSTopoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSTopoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSTopoRequest) ProtoMessage() {}

func (x *VSTopoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSTopoRequest.ProtoReflect.Descriptor instead.
func (*VSTopoRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{12}
}

func (x *VSTopoRequest) GetNodeAddr() []byte {
	if x != nil {
		return x.NodeAddr
	}
	return nil
}

func (x *VSTopoRequest) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type VSTopoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links         []*VSTopoResponse_Link `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	PolicyVersion uint64                 `protobuf:"varint,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
}

func (x *VSTopoResponse) Reset() {
	*x = VSTopoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSTopoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSTopoResponse) ProtoMessage() {}

func (x *VSTopoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSTopoResponse.ProtoReflect.Descriptor instead.
func (*VSTopoResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{13}
}

func (x *VSTopoResponse) GetLinks() []*VSTopoResponse_Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *VSTopoResponse) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

// See snio.Traffic
type PacketDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source   []byte `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Dest     []byte `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Protocol uint32 `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`                 // is a byte
	SrcPort  uint32 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`    // is a uint16
	DstPort  uint32 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`    // is a uint16
	Flags    uint32 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`                       // TCP flags (bottom 9 bits)
	IcmpType uint32 `protobuf:"varint,7,opt,name=icmp_type,json=icmpType,proto3" json:"icmp_type,omitempty"` // is a byte
	IcmpCode uint32 `protobuf:"varint,8,opt,name=icmp_code,json=icmpCode,proto3" json:"icmp_code,omitempty"` // is a byte
	IcmpAddr []byte `protobuf:"bytes,9,opt,name=icmp_addr,json=icmpAddr,proto3" json:"icmp_addr,omitempty"`  // ICMP target address for ICMP neighbor solicitation only
	Size     uint32 `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *PacketDesc) Reset() {
	*x = PacketDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketDesc) ProtoMessage() {}

func (x *PacketDesc) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketDesc.ProtoReflect.Descriptor instead.
func (*PacketDesc) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{14}
}

func (x *PacketDesc) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PacketDesc) GetDest() []byte {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *PacketDesc) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *PacketDesc) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *PacketDesc) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *PacketDesc) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *PacketDesc) GetIcmpType() uint32 {
	if x != nil {
		return x.IcmpType
	}
	return 0
}

func (x *PacketDesc) GetIcmpCode() uint32 {
	if x != nil {
		return x.IcmpCode
	}
	return 0
}

func (x *PacketDesc) GetIcmpAddr() []byte {
	if x != nil {
		return x.IcmpAddr
	}
	return nil
}

func (x *PacketDesc) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type VSVisaHop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Visa     *Visa  `protobuf:"bytes,1,opt,name=visa,proto3" json:"visa,omitempty"`
	HopCount uint32 `protobuf:"varint,2,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"` // for herald (uint8)
}

func (x *VSVisaHop) Reset() {
	*x = VSVisaHop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSVisaHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSVisaHop) ProtoMessage() {}

func (x *VSVisaHop) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSVisaHop.ProtoReflect.Descriptor instead.
func (*VSVisaHop) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{15}
}

func (x *VSVisaHop) GetVisa() *Visa {
	if x != nil {
		return x.Visa
	}
	return nil
}

func (x *VSVisaHop) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

type VSRevocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssuerId      uint32 `protobuf:"varint,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Configuration uint64 `protobuf:"varint,2,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *VSRevocation) Reset() {
	*x = VSRevocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSRevocation) ProtoMessage() {}

func (x *VSRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSRevocation.ProtoReflect.Descriptor instead.
func (*VSRevocation) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{16}
}

func (x *VSRevocation) GetIssuerId() uint32 {
	if x != nil {
		return x.IssuerId
	}
	return 0
}

func (x *VSRevocation) GetConfiguration() uint64 {
	if x != nil {
		return x.Configuration
	}
	return 0
}

type VSHostAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration uint64 `protobuf:"varint,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Agent         *Agent `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *VSHostAddRequest) Reset() {
	*x = VSHostAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSHostAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSHostAddRequest) ProtoMessage() {}

func (x *VSHostAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSHostAddRequest.ProtoReflect.Descriptor instead.
func (*VSHostAddRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{17}
}

func (x *VSHostAddRequest) GetConfiguration() uint64 {
	if x != nil {
		return x.Configuration
	}
	return 0
}

func (x *VSHostAddRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type VSHostAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VSHostAddResponse) Reset() {
	*x = VSHostAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSHostAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSHostAddResponse) ProtoMessage() {}

func (x *VSHostAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSHostAddResponse.ProtoReflect.Descriptor instead.
func (*VSHostAddResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{18}
}

type VSHostRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration uint64 `protobuf:"varint,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Agent         *Agent `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *VSHostRemoveRequest) Reset() {
	*x = VSHostRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSHostRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSHostRemoveRequest) ProtoMessage() {}

func (x *VSHostRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSHostRemoveRequest.ProtoReflect.Descriptor instead.
func (*VSHostRemoveRequest) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{19}
}

func (x *VSHostRemoveRequest) GetConfiguration() uint64 {
	if x != nil {
		return x.Configuration
	}
	return 0
}

func (x *VSHostRemoveRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type VSHostRemoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VSHostRemoveResponse) Reset() {
	*x = VSHostRemoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSHostRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSHostRemoveResponse) ProtoMessage() {}

func (x *VSHostRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSHostRemoveResponse.ProtoReflect.Descriptor instead.
func (*VSHostRemoveResponse) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{20}
}

type VSTopoResponse_NodeAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZprId   []byte `protobuf:"bytes,1,opt,name=zpr_id,json=zprId,proto3" json:"zpr_id,omitempty"`
	Host    string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                       // IP or Hostname
	Port    uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                      // for node-node IPv4 connection
	ExtAuth bool   `protobuf:"varint,4,opt,name=ext_auth,json=extAuth,proto3" json:"ext_auth,omitempty"` // true if node requires auth service
	Key     []byte `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`                         // Noise PK
}

func (x *VSTopoResponse_NodeAddr) Reset() {
	*x = VSTopoResponse_NodeAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSTopoResponse_NodeAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSTopoResponse_NodeAddr) ProtoMessage() {}

func (x *VSTopoResponse_NodeAddr) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSTopoResponse_NodeAddr.ProtoReflect.Descriptor instead.
func (*VSTopoResponse_NodeAddr) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{13, 0}
}

func (x *VSTopoResponse_NodeAddr) GetZprId() []byte {
	if x != nil {
		return x.ZprId
	}
	return nil
}

func (x *VSTopoResponse_NodeAddr) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VSTopoResponse_NodeAddr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VSTopoResponse_NodeAddr) GetExtAuth() bool {
	if x != nil {
		return x.ExtAuth
	}
	return false
}

func (x *VSTopoResponse_NodeAddr) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type VSTopoResponse_Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceId []byte                     `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // zpr id value for link originator
	Terms    []*VSTopoResponse_NodeAddr `protobuf:"bytes,2,rep,name=terms,proto3" json:"terms,omitempty"`                       // link terminators
}

func (x *VSTopoResponse_Link) Reset() {
	*x = VSTopoResponse_Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsio_vservice_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VSTopoResponse_Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSTopoResponse_Link) ProtoMessage() {}

func (x *VSTopoResponse_Link) ProtoReflect() protoreflect.Message {
	mi := &file_vsio_vservice_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSTopoResponse_Link.ProtoReflect.Descriptor instead.
func (*VSTopoResponse_Link) Descriptor() ([]byte, []int) {
	return file_vsio_vservice_proto_rawDescGZIP(), []int{13, 1}
}

func (x *VSTopoResponse_Link) GetSourceId() []byte {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *VSTopoResponse_Link) GetTerms() []*VSTopoResponse_NodeAddr {
	if x != nil {
		return x.Terms
	}
	return nil
}

var File_vsio_vservice_proto protoreflect.FileDescriptor

var file_vsio_vservice_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x73, 0x69, 0x6f, 0x2f, 0x76, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x76, 0x73, 0x69, 0x6f, 0x1a, 0x0d, 0x7a, 0x64, 0x73,
	0x2f, 0x7a, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x76, 0x73, 0x69, 0x6f,
	0x2f, 0x76, 0x69, 0x73, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x76, 0x73, 0x69,
	0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a,
	0x11, 0x56, 0x53, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x22,
	0x2e, 0x0a, 0x12, 0x56, 0x53, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x32, 0x0a, 0x13, 0x56, 0x53, 0x44, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41,
	0x64, 0x64, 0x72, 0x22, 0x30, 0x0a, 0x14, 0x56, 0x53, 0x44, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xf3, 0x02, 0x0a, 0x10, 0x56, 0x53, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f,
	0x63, 0x6b, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64,
	0x6f, 0x63, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x65, 0x71, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x41, 0x64, 0x64, 0x72, 0x12, 0x3a, 0x0a, 0x06, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x76, 0x73, 0x69, 0x6f,
	0x2e, 0x56, 0x53, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x52, 0x04, 0x63, 0x68, 0x61, 0x6c, 0x12, 0x33, 0x0a, 0x09, 0x63, 0x68, 0x61,
	0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x7a,
	0x64, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2a, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x84, 0x01, 0x0a, 0x11,
	0x56, 0x53, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12,
	0x21, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x22, 0x5f, 0x0a, 0x09, 0x56, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x26, 0x0a, 0x0f, 0x73, 0x72, 0x63, 0x5f, 0x74, 0x65, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x72, 0x63, 0x54, 0x65, 0x74,
	0x68, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x2a, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x52, 0x07, 0x74, 0x72, 0x61, 0x66,
	0x66, 0x69, 0x63, 0x22, 0x68, 0x0a, 0x0a, 0x56, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x23, 0x0a, 0x04, 0x76, 0x69, 0x73, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53,
	0x56, 0x69, 0x73, 0x61, 0x48, 0x6f, 0x70, 0x52, 0x04, 0x76, 0x69, 0x73, 0x61, 0x22, 0x65, 0x0a,
	0x0e, 0x56, 0x53, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x75,
	0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x55, 0x73, 0x65, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x56, 0x53, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x0d, 0x56, 0x53, 0x50, 0x6f, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x6b,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x6f, 0x63,
	0x6b, 0x41, 0x64, 0x64, 0x72, 0x22, 0x79, 0x0a, 0x0e, 0x56, 0x53, 0x50, 0x6f, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x69, 0x73, 0x61, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53,
	0x56, 0x69, 0x73, 0x61, 0x48, 0x6f, 0x70, 0x52, 0x05, 0x76, 0x69, 0x73, 0x61, 0x73, 0x12, 0x2c,
	0x0a, 0x07, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x52, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6d, 0x6f, 0x72, 0x65,
	0x22, 0x53, 0x0a, 0x0d, 0x56, 0x53, 0x54, 0x6f, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x25,
	0x0a, 0x0e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xba, 0x02, 0x0a, 0x0e, 0x56, 0x53, 0x54, 0x6f, 0x70, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56,
	0x53, 0x54, 0x6f, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0d, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x1a, 0x76, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x15, 0x0a, 0x06,
	0x7a, 0x70, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x7a, 0x70,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x78, 0x74, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65,
	0x78, 0x74, 0x41, 0x75, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x1a, 0x58, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x33, 0x0a,
	0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76,
	0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x54, 0x6f, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x52, 0x05, 0x74, 0x65, 0x72,
	0x6d, 0x73, 0x22, 0x8b, 0x02, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x73,
	0x63, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x72, 0x63,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x72, 0x63,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63, 0x6d, 0x70, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x63, 0x6d, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63, 0x6d, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x63, 0x6d, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x63, 0x6d, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x69, 0x63, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0x48, 0x0a, 0x09, 0x56, 0x53, 0x56, 0x69, 0x73, 0x61, 0x48, 0x6f, 0x70, 0x12, 0x1e, 0x0a,
	0x04, 0x76, 0x69, 0x73, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x73,
	0x69, 0x6f, 0x2e, 0x56, 0x69, 0x73, 0x61, 0x52, 0x04, 0x76, 0x69, 0x73, 0x61, 0x12, 0x1b, 0x0a,
	0x09, 0x68, 0x6f, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x68, 0x6f, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x0c, 0x56, 0x53,
	0x52, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5b, 0x0a,
	0x10, 0x56, 0x53, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x56, 0x53,
	0x48, 0x6f, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x5e, 0x0a, 0x13, 0x56, 0x53, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x05,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x73,
	0x69, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22,
	0x16, 0x0a, 0x14, 0x56, 0x53, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc7, 0x04, 0x0a, 0x0b, 0x56, 0x69, 0x73, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76,
	0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x44, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53,
	0x44, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x44, 0x65, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x12, 0x16, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x76, 0x73,
	0x69, 0x6f, 0x2e, 0x56, 0x53, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x56, 0x69, 0x73, 0x61, 0x12, 0x0f, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0b, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x76, 0x73, 0x69, 0x6f,
	0x2e, 0x56, 0x53, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x04, 0x50, 0x6f, 0x6c, 0x6c,
	0x12, 0x13, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x50,
	0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x13, 0x2e, 0x76,
	0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x54, 0x6f, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x54, 0x6f, 0x70, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x48, 0x6f, 0x73,
	0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x16, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53,
	0x48, 0x6f, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x19, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e,
	0x56, 0x53, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x73, 0x69, 0x6f, 0x2e, 0x56, 0x53, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1a, 0x5a, 0x18, 0x7a, 0x70, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x76, 0x73, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x73, 0x6e, 0x69, 0x6f, 0x2f, 0x76, 0x73, 0x69, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vsio_vservice_proto_rawDescOnce sync.Once
	file_vsio_vservice_proto_rawDescData = file_vsio_vservice_proto_rawDesc
)

func file_vsio_vservice_proto_rawDescGZIP() []byte {
	file_vsio_vservice_proto_rawDescOnce.Do(func() {
		file_vsio_vservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_vsio_vservice_proto_rawDescData)
	})
	return file_vsio_vservice_proto_rawDescData
}

var file_vsio_vservice_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_vsio_vservice_proto_goTypes = []interface{}{
	(*VSRegisterRequest)(nil),       // 0: vsio.VSRegisterRequest
	(*VSRegisterResponse)(nil),      // 1: vsio.VSRegisterResponse
	(*VSDeRegisterRequest)(nil),     // 2: vsio.VSDeRegisterRequest
	(*VSDeRegisterResponse)(nil),    // 3: vsio.VSDeRegisterResponse
	(*VSConnectRequest)(nil),        // 4: vsio.VSConnectRequest
	(*VSConnectResponse)(nil),       // 5: vsio.VSConnectResponse
	(*VSRequest)(nil),               // 6: vsio.VSRequest
	(*VSResponse)(nil),              // 7: vsio.VSResponse
	(*VSStatsRequest)(nil),          // 8: vsio.VSStatsRequest
	(*VSStatsResponse)(nil),         // 9: vsio.VSStatsResponse
	(*VSPollRequest)(nil),           // 10: vsio.VSPollRequest
	(*VSPollResponse)(nil),          // 11: vsio.VSPollResponse
	(*VSTopoRequest)(nil),           // 12: vsio.VSTopoRequest
	(*VSTopoResponse)(nil),          // 13: vsio.VSTopoResponse
	(*PacketDesc)(nil),              // 14: vsio.PacketDesc
	(*VSVisaHop)(nil),               // 15: vsio.VSVisaHop
	(*VSRevocation)(nil),            // 16: vsio.VSRevocation
	(*VSHostAddRequest)(nil),        // 17: vsio.VSHostAddRequest
	(*VSHostAddResponse)(nil),       // 18: vsio.VSHostAddResponse
	(*VSHostRemoveRequest)(nil),     // 19: vsio.VSHostRemoveRequest
	(*VSHostRemoveResponse)(nil),    // 20: vsio.VSHostRemoveResponse
	nil,                             // 21: vsio.VSConnectRequest.ClaimsEntry
	(*VSTopoResponse_NodeAddr)(nil), // 22: vsio.VSTopoResponse.NodeAddr
	(*VSTopoResponse_Link)(nil),     // 23: vsio.VSTopoResponse.Link
	(*zds.Challenge)(nil),           // 24: zds.Challenge
	(*zds.ChallengeResponse)(nil),   // 25: zds.ChallengeResponse
	(*Agent)(nil),                   // 26: vsio.Agent
	(*Visa)(nil),                    // 27: vsio.Visa
}
var file_vsio_vservice_proto_depIdxs = []int32{
	21, // 0: vsio.VSConnectRequest.claims:type_name -> vsio.VSConnectRequest.ClaimsEntry
	24, // 1: vsio.VSConnectRequest.chal:type_name -> zds.Challenge
	25, // 2: vsio.VSConnectRequest.chal_resp:type_name -> zds.ChallengeResponse
	26, // 3: vsio.VSConnectRequest.node_agent:type_name -> vsio.Agent
	26, // 4: vsio.VSConnectResponse.agent:type_name -> vsio.Agent
	14, // 5: vsio.VSRequest.traffic:type_name -> vsio.PacketDesc
	15, // 6: vsio.VSResponse.visa:type_name -> vsio.VSVisaHop
	15, // 7: vsio.VSPollResponse.visas:type_name -> vsio.VSVisaHop
	16, // 8: vsio.VSPollResponse.revokes:type_name -> vsio.VSRevocation
	23, // 9: vsio.VSTopoResponse.links:type_name -> vsio.VSTopoResponse.Link
	27, // 10: vsio.VSVisaHop.visa:type_name -> vsio.Visa
	26, // 11: vsio.VSHostAddRequest.agent:type_name -> vsio.Agent
	26, // 12: vsio.VSHostRemoveRequest.agent:type_name -> vsio.Agent
	22, // 13: vsio.VSTopoResponse.Link.terms:type_name -> vsio.VSTopoResponse.NodeAddr
	0,  // 14: vsio.VisaService.Register:input_type -> vsio.VSRegisterRequest
	2,  // 15: vsio.VisaService.DeRegister:input_type -> vsio.VSDeRegisterRequest
	4,  // 16: vsio.VisaService.AuthorizeConnect:input_type -> vsio.VSConnectRequest
	6,  // 17: vsio.VisaService.RequestVisa:input_type -> vsio.VSRequest
	8,  // 18: vsio.VisaService.SubmitStats:input_type -> vsio.VSStatsRequest
	10, // 19: vsio.VisaService.Poll:input_type -> vsio.VSPollRequest
	12, // 20: vsio.VisaService.GetTopology:input_type -> vsio.VSTopoRequest
	17, // 21: vsio.VisaService.HostAdded:input_type -> vsio.VSHostAddRequest
	19, // 22: vsio.VisaService.HostRemoved:input_type -> vsio.VSHostRemoveRequest
	1,  // 23: vsio.VisaService.Register:output_type -> vsio.VSRegisterResponse
	3,  // 24: vsio.VisaService.DeRegister:output_type -> vsio.VSDeRegisterResponse
	5,  // 25: vsio.VisaService.AuthorizeConnect:output_type -> vsio.VSConnectResponse
	7,  // 26: vsio.VisaService.RequestVisa:output_type -> vsio.VSResponse
	9,  // 27: vsio.VisaService.SubmitStats:output_type -> vsio.VSStatsResponse
	11, // 28: vsio.VisaService.Poll:output_type -> vsio.VSPollResponse
	13, // 29: vsio.VisaService.GetTopology:output_type -> vsio.VSTopoResponse
	18, // 30: vsio.VisaService.HostAdded:output_type -> vsio.VSHostAddResponse
	20, // 31: vsio.VisaService.HostRemoved:output_type -> vsio.VSHostRemoveResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_vsio_vservice_proto_init() }
func file_vsio_vservice_proto_init() {
	if File_vsio_vservice_proto != nil {
		return
	}
	file_vsio_visa_proto_init()
	file_vsio_agent_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vsio_vservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSDeRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSDeRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSPollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSPollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSTopoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSTopoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSVisaHop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSRevocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSHostAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSHostAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSHostRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSHostRemoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSTopoResponse_NodeAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsio_vservice_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VSTopoResponse_Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vsio_vservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vsio_vservice_proto_goTypes,
		DependencyIndexes: file_vsio_vservice_proto_depIdxs,
		MessageInfos:      file_vsio_vservice_proto_msgTypes,
	}.Build()
	File_vsio_vservice_proto = out.File
	file_vsio_vservice_proto_rawDesc = nil
	file_vsio_vservice_proto_goTypes = nil
	file_vsio_vservice_proto_depIdxs = nil
}
