// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: zds.proto

package zds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateResponse_Status int32

const (
	ValidateResponse_FAIL      ValidateResponse_Status = 0 // Validation has failed
	ValidateResponse_SUCCESS   ValidateResponse_Status = 1 // Validation has succeeded
	ValidateResponse_NEED_MORE ValidateResponse_Status = 2 // More data is needed to perform validation
)

// Enum value maps for ValidateResponse_Status.
var (
	ValidateResponse_Status_name = map[int32]string{
		0: "FAIL",
		1: "SUCCESS",
		2: "NEED_MORE",
	}
	ValidateResponse_Status_value = map[string]int32{
		"FAIL":      0,
		"SUCCESS":   1,
		"NEED_MORE": 2,
	}
)

func (x ValidateResponse_Status) Enum() *ValidateResponse_Status {
	p := new(ValidateResponse_Status)
	*p = x
	return p
}

func (x ValidateResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_zds_proto_enumTypes[0].Descriptor()
}

func (ValidateResponse_Status) Type() protoreflect.EnumType {
	return &file_zds_proto_enumTypes[0]
}

func (x ValidateResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateResponse_Status.Descriptor instead.
func (ValidateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{2, 0}
}

type AttributeExpression_OPER int32

const (
	AttributeExpression_UNDEF    AttributeExpression_OPER = 0
	AttributeExpression_EQ       AttributeExpression_OPER = 1 // String comparison
	AttributeExpression_NEQ      AttributeExpression_OPER = 2 // String comparison
	AttributeExpression_HAS      AttributeExpression_OPER = 3 // (A, HAS, V) means:
	AttributeExpression_EXCLUDES AttributeExpression_OPER = 4 // (A, EXCLUDES, V) means:
)

// Enum value maps for AttributeExpression_OPER.
var (
	AttributeExpression_OPER_name = map[int32]string{
		0: "UNDEF",
		1: "EQ",
		2: "NEQ",
		3: "HAS",
		4: "EXCLUDES",
	}
	AttributeExpression_OPER_value = map[string]int32{
		"UNDEF":    0,
		"EQ":       1,
		"NEQ":      2,
		"HAS":      3,
		"EXCLUDES": 4,
	}
)

func (x AttributeExpression_OPER) Enum() *AttributeExpression_OPER {
	p := new(AttributeExpression_OPER)
	*p = x
	return p
}

func (x AttributeExpression_OPER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeExpression_OPER) Descriptor() protoreflect.EnumDescriptor {
	return file_zds_proto_enumTypes[1].Descriptor()
}

func (AttributeExpression_OPER) Type() protoreflect.EnumType {
	return &file_zds_proto_enumTypes[1]
}

func (x AttributeExpression_OPER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeExpression_OPER.Descriptor instead.
func (AttributeExpression_OPER) EnumDescriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{10, 0}
}

// Challenge is the initial challenge.  This is generated by ZPR. The challenge
// is a buffer of random bytes which is designed to be large enough to satisfy
// common cryptography requirements.  When the ZPR challenge is insufficient,
// the authentication service must use the NEEDS_MORE response status to send
// their own challenge to the agent.
type Challenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec string `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"` // A string identifying the challenge type, this is
	// interpreted by the adapter.
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp that challenge was generated (RFC3339).
	Nonce     []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`         // Random bytes to be used by the agent to respond.
	Data      []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`           // Optional additional bytes if needed for the
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{0}
}

func (x *Challenge) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *Challenge) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Challenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Challenge) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ValidateRequest is the argument to AValidate.
type ValidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chal     *Challenge           `protobuf:"bytes,1,opt,name=chal,proto3" json:"chal,omitempty"`                         // A copy of the challenge sent to the agent.
	CrespSet []*ChallengeResponse `protobuf:"bytes,2,rep,name=cresp_set,json=crespSet,proto3" json:"cresp_set,omitempty"` // A the response details, created by the adapter based on the challenge
	// type. This is a flexible structure mostly opaque to ZPR.
	Claims         map[string]string `protobuf:"bytes,3,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // All the claims sent by the adapter.
	Conf           map[string]string `protobuf:"bytes,4,rep,name=conf,proto3" json:"conf,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`     // Optional configuration data from policy.
	ChallengerAddr []byte            `protobuf:"bytes,5,opt,name=challenger_addr,json=challengerAddr,proto3" json:"challenger_addr,omitempty"`                                                   // Node which requested the challenge (IP address)
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRequest) GetChal() *Challenge {
	if x != nil {
		return x.Chal
	}
	return nil
}

func (x *ValidateRequest) GetCrespSet() []*ChallengeResponse {
	if x != nil {
		return x.CrespSet
	}
	return nil
}

func (x *ValidateRequest) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *ValidateRequest) GetConf() map[string]string {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *ValidateRequest) GetChallengerAddr() []byte {
	if x != nil {
		return x.ChallengerAddr
	}
	return nil
}

// The ultimate result of a call to AValidate is the generation of an identity
// token and an (initial) set of attributes.
//
// The JWT token returned by a successful call to validate has the following
// required fields:
//
//	sub   Must be set to the agent identifier. A particular identifier must
//	      always be maped to the same agent within a given ZPR network.
//
//	exp   Must be set to the expiration of the auth token. This may be
//	      reduced by policy.  (unix time seconds)
//
//	iss   Must be the same for every token issued by a given validation
//	      service.
//
//	aud   Must be set to "zpr".
//
//	nbf   Must be set to valid Not-Before timestamp as specified in RFC7519.
//	      (unix time seconds)
//
//	iat   Must be set to issue date (unix time seconds)
//
//	jti   The ID of this token. Set as described in RFC7519.
//
// In addition the signature on the token must match the certificate specified
// in policy for the validation service.
type ValidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stat     ValidateResponse_Status `protobuf:"varint,1,opt,name=stat,proto3,enum=zds.ValidateResponse_Status" json:"stat,omitempty"` // One of the status codes above.
	Error    string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                 // Used for ZPR logging purposes
	Ttl      uint32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`                                    // Time-to-live value in seconds for this RPC result.
	Token    []byte                  `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                 // A JWT (RFC7519) token, signed by validation service attesting to
	Attrs    []*Attribute            `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty"`                                 // The list of validated claims and additional attributes to associate
	FollowOn *Challenge              `protobuf:"bytes,6,opt,name=follow_on,json=followOn,proto3" json:"follow_on,omitempty"`           // If NEEDS_MORE is set, this is an AuthChallenge structure to
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateResponse) GetStat() ValidateResponse_Status {
	if x != nil {
		return x.Stat
	}
	return ValidateResponse_FAIL
}

func (x *ValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateResponse) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *ValidateResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ValidateResponse) GetAttrs() []*Attribute {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *ValidateResponse) GetFollowOn() *Challenge {
	if x != nil {
		return x.FollowOn
	}
	return nil
}

// RefreshRequest is the argument to the ARefresh call.
type RefreshRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // The token returned from a previously successful call to Validate.
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type RefreshResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // If false, then refresh is denied and a new Validation call must be made.
	Token   []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`      // If success is true, this is a new token (presumably with a new expiration date).
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// QueryRequest is the argument to the DQuery call.
type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenList [][]byte `protobuf:"bytes,1,rep,name=token_list,json=tokenList,proto3" json:"token_list,omitempty"` // A list of the JWT tokens associated with the agent.
	AttrKeys  []string `protobuf:"bytes,2,rep,name=attr_keys,json=attrKeys,proto3" json:"attr_keys,omitempty"`    // A list of attribute keys to query for.
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRequest) GetTokenList() [][]byte {
	if x != nil {
		return x.TokenList
	}
	return nil
}

func (x *QueryRequest) GetAttrKeys() []string {
	if x != nil {
		return x.AttrKeys
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attrs []*Attribute `protobuf:"bytes,1,rep,name=attrs,proto3" json:"attrs,omitempty"` // A list of result attributes that apply to the agent and match
	Ttl   uint32       `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`    // Time-to-live value in seconds for caching of this RPC call.
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResponse) GetAttrs() []*Attribute {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *QueryResponse) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// SatisfyRequest is the argument to the DSatisfy call.
type SatisfyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryExp []*AttributeExpression `protobuf:"bytes,1,rep,name=query_exp,json=queryExp,proto3" json:"query_exp,omitempty"` // A list of attribute-expression values to query for.
}

func (x *SatisfyRequest) Reset() {
	*x = SatisfyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SatisfyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatisfyRequest) ProtoMessage() {}

func (x *SatisfyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatisfyRequest.ProtoReflect.Descriptor instead.
func (*SatisfyRequest) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{7}
}

func (x *SatisfyRequest) GetQueryExp() []*AttributeExpression {
	if x != nil {
		return x.QueryExp
	}
	return nil
}

type SatisfyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subjects []string `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"` // List of subject identifiers which satisfy the request.
	// (TODO: This could be a large list, should we support some sort of cursor/pagination?)
	Ttl uint32 `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"` // Time-to-live (seconds) for the result.
}

func (x *SatisfyResponse) Reset() {
	*x = SatisfyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SatisfyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatisfyResponse) ProtoMessage() {}

func (x *SatisfyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatisfyResponse.ProtoReflect.Descriptor instead.
func (*SatisfyResponse) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{8}
}

func (x *SatisfyResponse) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *SatisfyResponse) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Exp int64  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"` // unix time seconds
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{9}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *Attribute) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// An "attribute-expression" is a 3-tuple of the form (key, operator, value).
// These expressions appear in ZPL too.
type AttributeExpression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Op  AttributeExpression_OPER `protobuf:"varint,2,opt,name=op,proto3,enum=zds.AttributeExpression_OPER" json:"op,omitempty"`
	Val string                   `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *AttributeExpression) Reset() {
	*x = AttributeExpression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeExpression) ProtoMessage() {}

func (x *AttributeExpression) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeExpression.ProtoReflect.Descriptor instead.
func (*AttributeExpression) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{10}
}

func (x *AttributeExpression) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributeExpression) GetOp() AttributeExpression_OPER {
	if x != nil {
		return x.Op
	}
	return AttributeExpression_UNDEF
}

func (x *AttributeExpression) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

// ChallengeResponse data is generated by adapters in response to a challenge.
// This is consumed by the validation services to verify identity.
//
// TODO: Just like the old AuthRespBlock but lacking the encoding -- what was that for anyway?
type ChallengeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChalSpec    string `protobuf:"bytes,1,opt,name=chal_spec,json=chalSpec,proto3" json:"chal_spec,omitempty"`           // Identifies the challenge type.
	RespSpec    string `protobuf:"bytes,2,opt,name=resp_spec,json=respSpec,proto3" json:"resp_spec,omitempty"`           // Identifies the response type.
	NonceOffset uint32 `protobuf:"varint,3,opt,name=nonce_offset,json=nonceOffset,proto3" json:"nonce_offset,omitempty"` // Describe the part of the nonce we used (offset)
	NonceLen    uint32 `protobuf:"varint,4,opt,name=nonce_len,json=nonceLen,proto3" json:"nonce_len,omitempty"`          // Describe the part of the nonce we used (length)
	// Types that are assignable to Result:
	//
	//	*ChallengeResponse_CrRaw
	//	*ChallengeResponse_CrU2F
	Result      isChallengeResponse_Result `protobuf_oneof:"result"`
	Certificate []byte                     `protobuf:"bytes,7,opt,name=certificate,proto3" json:"certificate,omitempty"` // optional, depends on chal_spec and resp_spec.
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{11}
}

func (x *ChallengeResponse) GetChalSpec() string {
	if x != nil {
		return x.ChalSpec
	}
	return ""
}

func (x *ChallengeResponse) GetRespSpec() string {
	if x != nil {
		return x.RespSpec
	}
	return ""
}

func (x *ChallengeResponse) GetNonceOffset() uint32 {
	if x != nil {
		return x.NonceOffset
	}
	return 0
}

func (x *ChallengeResponse) GetNonceLen() uint32 {
	if x != nil {
		return x.NonceLen
	}
	return 0
}

func (m *ChallengeResponse) GetResult() isChallengeResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ChallengeResponse) GetCrRaw() *RawChalResp {
	if x, ok := x.GetResult().(*ChallengeResponse_CrRaw); ok {
		return x.CrRaw
	}
	return nil
}

func (x *ChallengeResponse) GetCrU2F() *U2FChalResp {
	if x, ok := x.GetResult().(*ChallengeResponse_CrU2F); ok {
		return x.CrU2F
	}
	return nil
}

func (x *ChallengeResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type isChallengeResponse_Result interface {
	isChallengeResponse_Result()
}

type ChallengeResponse_CrRaw struct {
	CrRaw *RawChalResp `protobuf:"bytes,5,opt,name=cr_raw,json=crRaw,proto3,oneof"` // just an opaque byte buffer
}

type ChallengeResponse_CrU2F struct {
	CrU2F *U2FChalResp `protobuf:"bytes,6,opt,name=cr_u2f,json=crU2f,proto3,oneof"` // the u2f crypto response
}

func (*ChallengeResponse_CrRaw) isChallengeResponse_Result() {}

func (*ChallengeResponse_CrU2F) isChallengeResponse_Result() {}

type RawChalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Very simple, just raw bytes.
}

func (x *RawChalResp) Reset() {
	*x = RawChalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawChalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawChalResp) ProtoMessage() {}

func (x *RawChalResp) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawChalResp.ProtoReflect.Descriptor instead.
func (*RawChalResp) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{12}
}

func (x *RawChalResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// U2fChalResp represents an ECDSA signature performed by a U2F device.
type U2FChalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SigR    []byte `protobuf:"bytes,1,opt,name=sig_r,json=sigR,proto3" json:"sig_r,omitempty"`
	SigS    []byte `protobuf:"bytes,2,opt,name=sig_s,json=sigS,proto3" json:"sig_s,omitempty"`
	Counter uint32 `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (x *U2FChalResp) Reset() {
	*x = U2FChalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zds_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *U2FChalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*U2FChalResp) ProtoMessage() {}

func (x *U2FChalResp) ProtoReflect() protoreflect.Message {
	mi := &file_zds_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use U2FChalResp.ProtoReflect.Descriptor instead.
func (*U2FChalResp) Descriptor() ([]byte, []int) {
	return file_zds_proto_rawDescGZIP(), []int{13}
}

func (x *U2FChalResp) GetSigR() []byte {
	if x != nil {
		return x.SigR
	}
	return nil
}

func (x *U2FChalResp) GetSigS() []byte {
	if x != nil {
		return x.SigS
	}
	return nil
}

func (x *U2FChalResp) GetCounter() uint32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

var File_zds_proto protoreflect.FileDescriptor

var file_zds_proto_rawDesc = []byte{
	0x0a, 0x09, 0x7a, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x7a, 0x64, 0x73,
	0x22, 0x67, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf5, 0x02, 0x0a, 0x0f, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x04, 0x63, 0x68, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x7a, 0x64,
	0x73, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x04, 0x63, 0x68, 0x61,
	0x6c, 0x12, 0x33, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x63, 0x72,
	0x65, 0x73, 0x70, 0x53, 0x65, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73,
	0x12, 0x32, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x63, 0x6f, 0x6e, 0x66, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x1a, 0x39, 0x0a,
	0x0b, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x37, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x85, 0x02, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x74, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x09,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52,
	0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4f, 0x6e, 0x22, 0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x45,
	0x45, 0x44, 0x5f, 0x4d, 0x4f, 0x52, 0x45, 0x10, 0x02, 0x22, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x41, 0x0a, 0x0f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4a, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x4b, 0x65, 0x79, 0x73,
	0x22, 0x47, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0x47, 0x0a, 0x0e, 0x53, 0x61, 0x74,
	0x69, 0x73, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x09, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x45, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x71, 0x75, 0x65, 0x72, 0x79, 0x45,
	0x78, 0x70, 0x22, 0x3f, 0x0a, 0x0f, 0x53, 0x61, 0x74, 0x69, 0x73, 0x66, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x74, 0x74, 0x6c, 0x22, 0x41, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x76, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0xa3, 0x01, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x2d, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x7a,
	0x64, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x50, 0x45, 0x52, 0x52, 0x02, 0x6f, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61,
	0x6c, 0x22, 0x39, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x52, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x44,
	0x45, 0x46, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x45, 0x51, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x4e, 0x45, 0x51, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x41, 0x53, 0x10, 0x03, 0x12, 0x0c,
	0x0a, 0x08, 0x45, 0x58, 0x43, 0x4c, 0x55, 0x44, 0x45, 0x53, 0x10, 0x04, 0x22, 0x8f, 0x02, 0x0a,
	0x11, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x53, 0x70, 0x65, 0x63, 0x12, 0x21, 0x0a, 0x0c,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x4c, 0x65, 0x6e, 0x12, 0x29, 0x0a, 0x06,
	0x63, 0x72, 0x5f, 0x72, 0x61, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x7a,
	0x64, 0x73, 0x2e, 0x52, 0x61, 0x77, 0x43, 0x68, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x48, 0x00,
	0x52, 0x05, 0x63, 0x72, 0x52, 0x61, 0x77, 0x12, 0x29, 0x0a, 0x06, 0x63, 0x72, 0x5f, 0x75, 0x32,
	0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x55, 0x32,
	0x46, 0x43, 0x68, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x48, 0x00, 0x52, 0x05, 0x63, 0x72, 0x55,
	0x32, 0x66, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x21,
	0x0a, 0x0b, 0x52, 0x61, 0x77, 0x43, 0x68, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x51, 0x0a, 0x0b, 0x55, 0x32, 0x46, 0x43, 0x68, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x13, 0x0a, 0x05, 0x73, 0x69, 0x67, 0x5f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x73, 0x69, 0x67, 0x52, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x69, 0x67, 0x5f, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x53, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x32, 0xe6, 0x01, 0x0a, 0x03, 0x5a, 0x44, 0x53, 0x12, 0x3a, 0x0a, 0x09,
	0x41, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x7a, 0x64, 0x73, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x41, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x12, 0x13, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x7a, 0x64, 0x73, 0x2e,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x31, 0x0a, 0x06, 0x44, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x11, 0x2e, 0x7a, 0x64,
	0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x44, 0x53, 0x61, 0x74, 0x69, 0x73, 0x66, 0x79,
	0x12, 0x13, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x53, 0x61, 0x74, 0x69, 0x73, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x7a, 0x64, 0x73, 0x2e, 0x53, 0x61, 0x74, 0x69,
	0x73, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a,
	0x14, 0x7a, 0x70, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x76, 0x73, 0x78, 0x2f, 0x73, 0x6e, 0x69,
	0x6f, 0x2f, 0x7a, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zds_proto_rawDescOnce sync.Once
	file_zds_proto_rawDescData = file_zds_proto_rawDesc
)

func file_zds_proto_rawDescGZIP() []byte {
	file_zds_proto_rawDescOnce.Do(func() {
		file_zds_proto_rawDescData = protoimpl.X.CompressGZIP(file_zds_proto_rawDescData)
	})
	return file_zds_proto_rawDescData
}

var file_zds_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_zds_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_zds_proto_goTypes = []interface{}{
	(ValidateResponse_Status)(0),  // 0: zds.ValidateResponse.Status
	(AttributeExpression_OPER)(0), // 1: zds.AttributeExpression.OPER
	(*Challenge)(nil),             // 2: zds.Challenge
	(*ValidateRequest)(nil),       // 3: zds.ValidateRequest
	(*ValidateResponse)(nil),      // 4: zds.ValidateResponse
	(*RefreshRequest)(nil),        // 5: zds.RefreshRequest
	(*RefreshResponse)(nil),       // 6: zds.RefreshResponse
	(*QueryRequest)(nil),          // 7: zds.QueryRequest
	(*QueryResponse)(nil),         // 8: zds.QueryResponse
	(*SatisfyRequest)(nil),        // 9: zds.SatisfyRequest
	(*SatisfyResponse)(nil),       // 10: zds.SatisfyResponse
	(*Attribute)(nil),             // 11: zds.Attribute
	(*AttributeExpression)(nil),   // 12: zds.AttributeExpression
	(*ChallengeResponse)(nil),     // 13: zds.ChallengeResponse
	(*RawChalResp)(nil),           // 14: zds.RawChalResp
	(*U2FChalResp)(nil),           // 15: zds.U2FChalResp
	nil,                           // 16: zds.ValidateRequest.ClaimsEntry
	nil,                           // 17: zds.ValidateRequest.ConfEntry
}
var file_zds_proto_depIdxs = []int32{
	2,  // 0: zds.ValidateRequest.chal:type_name -> zds.Challenge
	13, // 1: zds.ValidateRequest.cresp_set:type_name -> zds.ChallengeResponse
	16, // 2: zds.ValidateRequest.claims:type_name -> zds.ValidateRequest.ClaimsEntry
	17, // 3: zds.ValidateRequest.conf:type_name -> zds.ValidateRequest.ConfEntry
	0,  // 4: zds.ValidateResponse.stat:type_name -> zds.ValidateResponse.Status
	11, // 5: zds.ValidateResponse.attrs:type_name -> zds.Attribute
	2,  // 6: zds.ValidateResponse.follow_on:type_name -> zds.Challenge
	11, // 7: zds.QueryResponse.attrs:type_name -> zds.Attribute
	12, // 8: zds.SatisfyRequest.query_exp:type_name -> zds.AttributeExpression
	1,  // 9: zds.AttributeExpression.op:type_name -> zds.AttributeExpression.OPER
	14, // 10: zds.ChallengeResponse.cr_raw:type_name -> zds.RawChalResp
	15, // 11: zds.ChallengeResponse.cr_u2f:type_name -> zds.U2FChalResp
	3,  // 12: zds.ZDS.AValidate:input_type -> zds.ValidateRequest
	5,  // 13: zds.ZDS.ARefresh:input_type -> zds.RefreshRequest
	7,  // 14: zds.ZDS.DQuery:input_type -> zds.QueryRequest
	9,  // 15: zds.ZDS.DSatisfy:input_type -> zds.SatisfyRequest
	4,  // 16: zds.ZDS.AValidate:output_type -> zds.ValidateResponse
	6,  // 17: zds.ZDS.ARefresh:output_type -> zds.RefreshResponse
	8,  // 18: zds.ZDS.DQuery:output_type -> zds.QueryResponse
	10, // 19: zds.ZDS.DSatisfy:output_type -> zds.SatisfyResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_zds_proto_init() }
func file_zds_proto_init() {
	if File_zds_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zds_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Challenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SatisfyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SatisfyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeExpression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawChalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zds_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*U2FChalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_zds_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*ChallengeResponse_CrRaw)(nil),
		(*ChallengeResponse_CrU2F)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zds_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zds_proto_goTypes,
		DependencyIndexes: file_zds_proto_depIdxs,
		EnumInfos:         file_zds_proto_enumTypes,
		MessageInfos:      file_zds_proto_msgTypes,
	}.Build()
	File_zds_proto = out.File
	file_zds_proto_rawDesc = nil
	file_zds_proto_goTypes = nil
	file_zds_proto_depIdxs = nil
}
