syntax = "proto3";
package pmctl;

option go_package = "zpr.org/vs/pkg/snio/admin";

// Converted from the pmctl.proto in zpr-prototype.
service Admin {

  // Visa service end points--
  //
  rpc Install (InstallRequest) returns (InstallResponse) {}    
  rpc Fetch (FetchRequest) returns (FetchResponse) {} 
  rpc List (ListRequest) returns (ListResponse) {} 
}


message InstallRequest{
  string version           = 1; // optional expected version of already installed policy (install fails if mismatch)
  uint32 format            = 2; // policy bundle format version (pol.SerialVersion)
  bytes policy_container   = 3; // Zipped PolicyContiner raw bytes
}

message InstallResponse{
  string version   = 1; // version installed
  uint64 config_id = 2;
}

message FetchRequest {
  uint64 config_id    = 1; // optional
}

message FetchResponse {
  string version           = 1; // policy version attachedc
  uint32 format            = 2; // format version of bundle
  bytes policy_container   = 3; // zipped PolicyContainer
  uint64 config_id         = 4;
}

message ListRequest {
  bool all         = 1;  // Not used (TODO: remove)
  uint64 config_id = 2;  // Not used (TODO: remove)
}

message ListResponseEl {
  uint64 config_id = 1;
  string version   = 2;
}

message ListResponse {
  repeated ListResponseEl list = 1;
}

