# Config for client adapter in front of the visa service

[global]
name = "vservice"
ca_file = "ca-cert.pem"
certificate_file = "adapter-vs-cert.pem"
private_key_file = "adapter-vs-key.pem"
agent_addr = "fd5a:5052::1" # visa service well known addr

# Currently tokio TUN on linux will not set an IPv6 address on a TUN interface.
# So the running of the node needs to first create and then pass in the TUN
# interface name using `--tun-if` on the command line.
tun_if = "MISSING_TUN"


[adapter]
node_addr = "172.16.1.1:5000"
node_public_key_file = "node-pubkey.pem"









