# Config for client adapter in front of the visa service

[global]
name = "vservice"
ca_file = "ca-cert.pem"
certificate_file = "adapter-vs-cert.pem"
private_key_file = "adapter-vs-key.pem"
agent_addr = [ "fd5a:5052::1" ] # visa service well known addr
self_addr = "0.0.0.0:5000"

# use `sudo ./mktun.sh` to set this up
tun_if = "tun9"


[adapter]
node_addr = "172.16.1.1:5000"
node_public_key_file = "node-pubkey.pem"









