[package]
name = "libnode2"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
capnp = { workspace = true }
capnp-rpc = { workspace = true }
clap = { workspace = true, optional = true }
ipnet = { workspace = true }
openssl = { workspace = true }
rcgen = "0.14.7"
rustyline = { version = "17.0.2", optional = true }
rustls = "0.23.36"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = "0.26.4"
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
zpr = { workspace = true }

[features]
build-lnt = ["clap", "tracing-subscriber", "rustyline"]

[[bin]]
name = "lntest"
path = "src/bin/lntest.rs"
required-features = ["build-lnt"]
