[package]
name = "libnode2"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
capnp = "0.25.0"
capnp-rpc = "0.25.0"
clap = { version = "4.5.23", features = ["derive"], optional = true } # lnt
ipnet = "2.11.0"
openssl = "0.10.74"
rustyline = { version = "17.0.2", optional = true } #lnt
thiserror = "2.0.17"
tokio-util = { version = "0.7.17", features = ["rt", "compat"] }
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", optional = true } # lnt
tokio-rustls = "0.26.4"
rustls = "0.23.36"
rcgen = "0.14.7"
zpr = { git = "https://github.com/org-zpr/zpr-common.git", tag = "v0.7.2", features = ["vsapi"] }

[features]
build-lnt = ["clap", "tracing-subscriber", "rustyline"]

[[bin]]
name = "lntest"
path = "src/bin/lntest.rs"
required-features = ["build-lnt"]
