[package]
name = "libnode2"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
capnp-rpc = "0.23.0"
capnp = "0.23.0"
thiserror = "2.0.17"
tracing = "0.1.41"
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = { version = "0.7.17", features = ["rt", "compat"] }
openssl = "0.10.74"
clap = { version = "4.5.23", features = ["derive"], optional = true } # ln2
tracing-subscriber = { version = "0.3.20", optional = true } # ln2
ipnet = "2.11.0"
zpr = { path = "../zpr" }
rustyline = { version = "17.0.2", optional = true } #ln2

[features]
build-ln2 = ["clap", "tracing-subscriber", "rustyline"]

[[bin]]
name = "ln2"
path = "src/bin/ln2.rs"
required-features = ["build-ln2"]


