[package]
name = "libnode"
version = "0.4.1"
edition = "2024"
license = "Apache-2.0"

[dependencies]
bytes = "1.7.2"
openssl = "0.10.70"
rand = "0.8.5"
thiserror = "1.0.65"
thrift = "0.17.0"
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["rt"] }
tracing = "0.1.40"
vsapi_thrift = { package = "vsapi", git = "https://github.com/org-zpr/zpr-vsapi-rs.git", tag = "v0.4.1" }
zpr = { git = "https://github.com/org-zpr/zpr-common.git", tag = "v0.7.0", features = ["vsapi"] }
zerocopy = { version = "0.8.3", features = ["derive", "std"] }
zpr-utils = { path = "../zpr-utils" }
