# config for the client adapter in front of the "service".

[profile]
name = "zprfoo"
root_ca = "ca-cert.pem"


[dock]

# Must match interface address in policy.
host_or_ip = "192.168.0.55"
port = 5000

noise_public_key = "GExPGh5RE/nKo8WoN8EqknDDNIEjWBL6PZm08Uhvn0w="


[adapter]
noise_certificate = "adapter-service-cert.pem"
noise_private_key = "AC1yJ8aoQx4JkqoX6x2O8GjkkHwrRATYJdwKPWHZx1M="





