# Config for client adapter in front of the visa service

[profile]
name = "zprfoo"
root_ca = "ca-cert.pem"


[dock]

# Must match node interface address in policy.
host_or_ip = "192.168.0.55"
port = 5000
noise_public_key = "GExPGh5RE/nKo8WoN8EqknDDNIEjWBL6PZm08Uhvn0w="


[adapter]
noise_certificate = "adapter-vs-cert.pem"
noise_private_key = "MOmMSwVohbhiP/srcaRztQeWuoRASvW4yfpHDY0DlWk="






