# config for a "client" adapter which talks to the service.

[profile]
name = "zprfoo"
root_ca = "ca-cert.pem"


[dock]

# Must match interface address in policy
host_or_ip = "192.168.0.55"
port = 5000

noise_public_key = "GExPGh5RE/nKo8WoN8EqknDDNIEjWBL6PZm08Uhvn0w="


[adapter]
noise_certificate = "adapter-client-cert.pem"
noise_private_key = "OE+TMMVDTaKEdE1LVf+y1fCUnsZ8whnq90klZJxzp1Q="





