# node configuration file.

node_name = "n0"

[creds]
ca_certificate = "ca-cert.pem"
noise_certificate = "node-cert.pem"
noise_private_key = "UFIB5WPx5eMEtn6XY55//vGn+HXRVLdcwQC0BtDZhkU="

[dock]
enabled = true
listen_address = "0.0.0.0:5000"


[claims]
# Should match policy
"zpr.addr" = "fc5a:5052:90de::1"


