// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: zds.proto

package zds2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ZAuthentication_GenerateChallenge_FullMethodName = "/zds2.ZAuthentication/GenerateChallenge"
	ZAuthentication_ValidateChallenge_FullMethodName = "/zds2.ZAuthentication/ValidateChallenge"
	ZAuthentication_GetSchema_FullMethodName         = "/zds2.ZAuthentication/GetSchema"
)

// ZAuthenticationClient is the client API for ZAuthentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZAuthenticationClient interface {
	GenerateChallenge(ctx context.Context, in *GenChalRequest, opts ...grpc.CallOption) (*GenChalResponse, error)
	ValidateChallenge(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	GetSchema(ctx context.Context, in *SchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
}

type zAuthenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewZAuthenticationClient(cc grpc.ClientConnInterface) ZAuthenticationClient {
	return &zAuthenticationClient{cc}
}

func (c *zAuthenticationClient) GenerateChallenge(ctx context.Context, in *GenChalRequest, opts ...grpc.CallOption) (*GenChalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenChalResponse)
	err := c.cc.Invoke(ctx, ZAuthentication_GenerateChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zAuthenticationClient) ValidateChallenge(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, ZAuthentication_ValidateChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zAuthenticationClient) GetSchema(ctx context.Context, in *SchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, ZAuthentication_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZAuthenticationServer is the server API for ZAuthentication service.
// All implementations must embed UnimplementedZAuthenticationServer
// for forward compatibility
type ZAuthenticationServer interface {
	GenerateChallenge(context.Context, *GenChalRequest) (*GenChalResponse, error)
	ValidateChallenge(context.Context, *ValidateRequest) (*ValidateResponse, error)
	GetSchema(context.Context, *SchemaRequest) (*SchemaResponse, error)
	mustEmbedUnimplementedZAuthenticationServer()
}

// UnimplementedZAuthenticationServer must be embedded to have forward compatible implementations.
type UnimplementedZAuthenticationServer struct {
}

func (UnimplementedZAuthenticationServer) GenerateChallenge(context.Context, *GenChalRequest) (*GenChalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateChallenge not implemented")
}
func (UnimplementedZAuthenticationServer) ValidateChallenge(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateChallenge not implemented")
}
func (UnimplementedZAuthenticationServer) GetSchema(context.Context, *SchemaRequest) (*SchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedZAuthenticationServer) mustEmbedUnimplementedZAuthenticationServer() {}

// UnsafeZAuthenticationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZAuthenticationServer will
// result in compilation errors.
type UnsafeZAuthenticationServer interface {
	mustEmbedUnimplementedZAuthenticationServer()
}

func RegisterZAuthenticationServer(s grpc.ServiceRegistrar, srv ZAuthenticationServer) {
	s.RegisterService(&ZAuthentication_ServiceDesc, srv)
}

func _ZAuthentication_GenerateChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenChalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZAuthenticationServer).GenerateChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZAuthentication_GenerateChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZAuthenticationServer).GenerateChallenge(ctx, req.(*GenChalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZAuthentication_ValidateChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZAuthenticationServer).ValidateChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZAuthentication_ValidateChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZAuthenticationServer).ValidateChallenge(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZAuthentication_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZAuthenticationServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZAuthentication_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZAuthenticationServer).GetSchema(ctx, req.(*SchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZAuthentication_ServiceDesc is the grpc.ServiceDesc for ZAuthentication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZAuthentication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zds2.ZAuthentication",
	HandlerType: (*ZAuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateChallenge",
			Handler:    _ZAuthentication_GenerateChallenge_Handler,
		},
		{
			MethodName: "ValidateChallenge",
			Handler:    _ZAuthentication_ValidateChallenge_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _ZAuthentication_GetSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zds.proto",
}

const (
	ZAttributes_QueryAttrs_FullMethodName     = "/zds2.ZAttributes/QueryAttrs"
	ZAttributes_StaisfiesAttrs_FullMethodName = "/zds2.ZAttributes/StaisfiesAttrs"
	ZAttributes_StreamChanges_FullMethodName  = "/zds2.ZAttributes/StreamChanges"
	ZAttributes_GetSchema_FullMethodName      = "/zds2.ZAttributes/GetSchema"
)

// ZAttributesClient is the client API for ZAttributes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZAttributesClient interface {
	QueryAttrs(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	StaisfiesAttrs(ctx context.Context, in *SatisfyRequest, opts ...grpc.CallOption) (*SatisfyResponse, error)
	StreamChanges(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (ZAttributes_StreamChangesClient, error)
	GetSchema(ctx context.Context, in *SchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
}

type zAttributesClient struct {
	cc grpc.ClientConnInterface
}

func NewZAttributesClient(cc grpc.ClientConnInterface) ZAttributesClient {
	return &zAttributesClient{cc}
}

func (c *zAttributesClient) QueryAttrs(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, ZAttributes_QueryAttrs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zAttributesClient) StaisfiesAttrs(ctx context.Context, in *SatisfyRequest, opts ...grpc.CallOption) (*SatisfyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SatisfyResponse)
	err := c.cc.Invoke(ctx, ZAttributes_StaisfiesAttrs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zAttributesClient) StreamChanges(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (ZAttributes_StreamChangesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZAttributes_ServiceDesc.Streams[0], ZAttributes_StreamChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &zAttributesStreamChangesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ZAttributes_StreamChangesClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type zAttributesStreamChangesClient struct {
	grpc.ClientStream
}

func (x *zAttributesStreamChangesClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zAttributesClient) GetSchema(ctx context.Context, in *SchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, ZAttributes_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZAttributesServer is the server API for ZAttributes service.
// All implementations must embed UnimplementedZAttributesServer
// for forward compatibility
type ZAttributesServer interface {
	QueryAttrs(context.Context, *QueryRequest) (*QueryResponse, error)
	StaisfiesAttrs(context.Context, *SatisfyRequest) (*SatisfyResponse, error)
	StreamChanges(*StreamRequest, ZAttributes_StreamChangesServer) error
	GetSchema(context.Context, *SchemaRequest) (*SchemaResponse, error)
	mustEmbedUnimplementedZAttributesServer()
}

// UnimplementedZAttributesServer must be embedded to have forward compatible implementations.
type UnimplementedZAttributesServer struct {
}

func (UnimplementedZAttributesServer) QueryAttrs(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAttrs not implemented")
}
func (UnimplementedZAttributesServer) StaisfiesAttrs(context.Context, *SatisfyRequest) (*SatisfyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaisfiesAttrs not implemented")
}
func (UnimplementedZAttributesServer) StreamChanges(*StreamRequest, ZAttributes_StreamChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamChanges not implemented")
}
func (UnimplementedZAttributesServer) GetSchema(context.Context, *SchemaRequest) (*SchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedZAttributesServer) mustEmbedUnimplementedZAttributesServer() {}

// UnsafeZAttributesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZAttributesServer will
// result in compilation errors.
type UnsafeZAttributesServer interface {
	mustEmbedUnimplementedZAttributesServer()
}

func RegisterZAttributesServer(s grpc.ServiceRegistrar, srv ZAttributesServer) {
	s.RegisterService(&ZAttributes_ServiceDesc, srv)
}

func _ZAttributes_QueryAttrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZAttributesServer).QueryAttrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZAttributes_QueryAttrs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZAttributesServer).QueryAttrs(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZAttributes_StaisfiesAttrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatisfyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZAttributesServer).StaisfiesAttrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZAttributes_StaisfiesAttrs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZAttributesServer).StaisfiesAttrs(ctx, req.(*SatisfyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZAttributes_StreamChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZAttributesServer).StreamChanges(m, &zAttributesStreamChangesServer{ServerStream: stream})
}

type ZAttributes_StreamChangesServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type zAttributesStreamChangesServer struct {
	grpc.ServerStream
}

func (x *zAttributesStreamChangesServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ZAttributes_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZAttributesServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZAttributes_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZAttributesServer).GetSchema(ctx, req.(*SchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZAttributes_ServiceDesc is the grpc.ServiceDesc for ZAttributes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZAttributes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zds2.ZAttributes",
	HandlerType: (*ZAttributesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryAttrs",
			Handler:    _ZAttributes_QueryAttrs_Handler,
		},
		{
			MethodName: "StaisfiesAttrs",
			Handler:    _ZAttributes_StaisfiesAttrs_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _ZAttributes_GetSchema_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChanges",
			Handler:       _ZAttributes_StreamChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "zds.proto",
}
