// Autogenerated by Thrift Compiler (0.20.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

#[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StatusCode(pub i32);

impl StatusCode {
  pub const SUCCESS: StatusCode = StatusCode(0);
  pub const FAIL: StatusCode = StatusCode(1);
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::SUCCESS,
    Self::FAIL,
  ];
}

impl TSerializable for StatusCode {
  #[allow(clippy::trivially_copy_pass_by_ref)]
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    o_prot.write_i32(self.0)
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<StatusCode> {
    let enum_value = i_prot.read_i32()?;
    Ok(StatusCode::from(enum_value))
  }
}

impl From<i32> for StatusCode {
  fn from(i: i32) -> Self {
    match i {
      0 => StatusCode::SUCCESS,
      1 => StatusCode::FAIL,
      _ => StatusCode(i)
    }
  }
}

impl From<&i32> for StatusCode {
  fn from(i: &i32) -> Self {
    StatusCode::from(*i)
  }
}

impl From<StatusCode> for i32 {
  fn from(e: StatusCode) -> i32 {
    e.0
  }
}

impl From<&StatusCode> for i32 {
  fn from(e: &StatusCode) -> i32 {
    e.0
  }
}

#[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct AgentType(pub i32);

impl AgentType {
  pub const ADAPTER: AgentType = AgentType(0);
  pub const NODE: AgentType = AgentType(1);
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::ADAPTER,
    Self::NODE,
  ];
}

impl TSerializable for AgentType {
  #[allow(clippy::trivially_copy_pass_by_ref)]
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    o_prot.write_i32(self.0)
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<AgentType> {
    let enum_value = i_prot.read_i32()?;
    Ok(AgentType::from(enum_value))
  }
}

impl From<i32> for AgentType {
  fn from(i: i32) -> Self {
    match i {
      0 => AgentType::ADAPTER,
      1 => AgentType::NODE,
      _ => AgentType(i)
    }
  }
}

impl From<&i32> for AgentType {
  fn from(i: &i32) -> Self {
    AgentType::from(*i)
  }
}

impl From<AgentType> for i32 {
  fn from(e: AgentType) -> i32 {
    e.0
  }
}

impl From<&AgentType> for i32 {
  fn from(e: &AgentType) -> i32 {
    e.0
  }
}

//
// UnauthorizedError
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct UnauthorizedError {
}

impl UnauthorizedError {
  pub fn new() -> UnauthorizedError {
    UnauthorizedError {}
  }
}

impl TSerializable for UnauthorizedError {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<UnauthorizedError> {
    i_prot.read_struct_begin()?;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      i_prot.skip(field_ident.field_type)?;
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = UnauthorizedError {};
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("UnauthorizedError");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

impl Error for UnauthorizedError {}

impl From<UnauthorizedError> for thrift::Error {
  fn from(e: UnauthorizedError) -> Self {
    thrift::Error::User(Box::new(e))
  }
}

impl Display for UnauthorizedError {
  fn fmt(&self, f: &mut Formatter) -> fmt::Result {
    write!(f, "remote service threw UnauthorizedError")
  }
}

//
// Agent
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Agent {
  pub agent_type: Option<AgentType>,
  pub attrs: Option<BTreeMap<String, String>>,
  pub auth_expires: Option<i64>,
  pub zpr_addr: Option<Vec<u8>>,
  pub tether_addr: Option<Vec<u8>>,
  pub ident: Option<String>,
  pub provides: Option<Vec<String>>,
}

impl Agent {
  pub fn new<F1, F2, F3, F4, F5, F6, F7>(agent_type: F1, attrs: F2, auth_expires: F3, zpr_addr: F4, tether_addr: F5, ident: F6, provides: F7) -> Agent where F1: Into<Option<AgentType>>, F2: Into<Option<BTreeMap<String, String>>>, F3: Into<Option<i64>>, F4: Into<Option<Vec<u8>>>, F5: Into<Option<Vec<u8>>>, F6: Into<Option<String>>, F7: Into<Option<Vec<String>>> {
    Agent {
      agent_type: agent_type.into(),
      attrs: attrs.into(),
      auth_expires: auth_expires.into(),
      zpr_addr: zpr_addr.into(),
      tether_addr: tether_addr.into(),
      ident: ident.into(),
      provides: provides.into(),
    }
  }
}

impl TSerializable for Agent {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Agent> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<AgentType> = None;
    let mut f_2: Option<BTreeMap<String, String>> = Some(BTreeMap::new());
    let mut f_3: Option<i64> = Some(0);
    let mut f_4: Option<Vec<u8>> = Some(Vec::new());
    let mut f_5: Option<Vec<u8>> = Some(Vec::new());
    let mut f_6: Option<String> = Some("".to_owned());
    let mut f_7: Option<Vec<String>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = AgentType::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        2 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<String, String> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_0 = i_prot.read_string()?;
            let map_val_1 = i_prot.read_string()?;
            val.insert(map_key_0, map_val_1);
          }
          i_prot.read_map_end()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_bytes()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_bytes()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_string()?;
          f_6 = Some(val);
        },
        7 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<String> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_2 = i_prot.read_string()?;
            val.push(list_elem_2);
          }
          i_prot.read_list_end()?;
          f_7 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = Agent {
      agent_type: f_1,
      attrs: f_2,
      auth_expires: f_3,
      zpr_addr: f_4,
      tether_addr: f_5,
      ident: f_6,
      provides: f_7,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("Agent");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.agent_type {
      o_prot.write_field_begin(&TFieldIdentifier::new("agent_type", TType::I32, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.attrs {
      o_prot.write_field_begin(&TFieldIdentifier::new("attrs", TType::Map, 2))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::String, TType::String, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_string(k)?;
        o_prot.write_string(v)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.auth_expires {
      o_prot.write_field_begin(&TFieldIdentifier::new("auth_expires", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.zpr_addr {
      o_prot.write_field_begin(&TFieldIdentifier::new("zpr_addr", TType::String, 4))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.tether_addr {
      o_prot.write_field_begin(&TFieldIdentifier::new("tether_addr", TType::String, 5))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.ident {
      o_prot.write_field_begin(&TFieldIdentifier::new("ident", TType::String, 6))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.provides {
      o_prot.write_field_begin(&TFieldIdentifier::new("provides", TType::List, 7))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::String, fld_var.len() as i32))?;
      for e in fld_var {
        o_prot.write_string(e)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// Challenge
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Challenge {
  pub challenge_type: Option<i32>,
  pub challenge_data: Option<Vec<u8>>,
}

impl Challenge {
  pub fn new<F1, F2>(challenge_type: F1, challenge_data: F2) -> Challenge where F1: Into<Option<i32>>, F2: Into<Option<Vec<u8>>> {
    Challenge {
      challenge_type: challenge_type.into(),
      challenge_data: challenge_data.into(),
    }
  }
}

impl TSerializable for Challenge {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Challenge> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = Some(0);
    let mut f_2: Option<Vec<u8>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bytes()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = Challenge {
      challenge_type: f_1,
      challenge_data: f_2,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("Challenge");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.challenge_type {
      o_prot.write_field_begin(&TFieldIdentifier::new("challenge_type", TType::I32, 1))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.challenge_data {
      o_prot.write_field_begin(&TFieldIdentifier::new("challenge_data", TType::String, 2))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// HelloResponse
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct HelloResponse {
  pub session_id: Option<i32>,
  pub challenge: Option<Challenge>,
}

impl HelloResponse {
  pub fn new<F1, F2>(session_id: F1, challenge: F2) -> HelloResponse where F1: Into<Option<i32>>, F2: Into<Option<Challenge>> {
    HelloResponse {
      session_id: session_id.into(),
      challenge: challenge.into(),
    }
  }
}

impl TSerializable for HelloResponse {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<HelloResponse> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = Some(0);
    let mut f_2: Option<Challenge> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = Challenge::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = HelloResponse {
      session_id: f_1,
      challenge: f_2,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("HelloResponse");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.session_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("session_id", TType::I32, 1))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.challenge {
      o_prot.write_field_begin(&TFieldIdentifier::new("challenge", TType::Struct, 2))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// NodeAuthRequest
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct NodeAuthRequest {
  pub session_id: Option<i32>,
  pub challenge: Option<Challenge>,
  pub timestamp: Option<i64>,
  pub node_cert: Option<Vec<u8>>,
  pub hmac: Option<Vec<u8>>,
  pub vss_service: Option<String>,
  pub node_agent: Option<Agent>,
}

impl NodeAuthRequest {
  pub fn new<F1, F2, F3, F4, F5, F6, F7>(session_id: F1, challenge: F2, timestamp: F3, node_cert: F4, hmac: F5, vss_service: F6, node_agent: F7) -> NodeAuthRequest where F1: Into<Option<i32>>, F2: Into<Option<Challenge>>, F3: Into<Option<i64>>, F4: Into<Option<Vec<u8>>>, F5: Into<Option<Vec<u8>>>, F6: Into<Option<String>>, F7: Into<Option<Agent>> {
    NodeAuthRequest {
      session_id: session_id.into(),
      challenge: challenge.into(),
      timestamp: timestamp.into(),
      node_cert: node_cert.into(),
      hmac: hmac.into(),
      vss_service: vss_service.into(),
      node_agent: node_agent.into(),
    }
  }
}

impl TSerializable for NodeAuthRequest {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<NodeAuthRequest> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = Some(0);
    let mut f_2: Option<Challenge> = None;
    let mut f_3: Option<i64> = Some(0);
    let mut f_4: Option<Vec<u8>> = Some(Vec::new());
    let mut f_5: Option<Vec<u8>> = Some(Vec::new());
    let mut f_6: Option<String> = Some("".to_owned());
    let mut f_7: Option<Agent> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = Challenge::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_bytes()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_bytes()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_string()?;
          f_6 = Some(val);
        },
        7 => {
          let val = Agent::read_from_in_protocol(i_prot)?;
          f_7 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = NodeAuthRequest {
      session_id: f_1,
      challenge: f_2,
      timestamp: f_3,
      node_cert: f_4,
      hmac: f_5,
      vss_service: f_6,
      node_agent: f_7,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("NodeAuthRequest");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.session_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("session_id", TType::I32, 1))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.challenge {
      o_prot.write_field_begin(&TFieldIdentifier::new("challenge", TType::Struct, 2))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.timestamp {
      o_prot.write_field_begin(&TFieldIdentifier::new("timestamp", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.node_cert {
      o_prot.write_field_begin(&TFieldIdentifier::new("node_cert", TType::String, 4))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.hmac {
      o_prot.write_field_begin(&TFieldIdentifier::new("hmac", TType::String, 5))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.vss_service {
      o_prot.write_field_begin(&TFieldIdentifier::new("vss_service", TType::String, 6))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.node_agent {
      o_prot.write_field_begin(&TFieldIdentifier::new("node_agent", TType::Struct, 7))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// ConnectRequest
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ConnectRequest {
  pub connection_id: Option<i32>,
  pub dock_addr: Option<Vec<u8>>,
  pub claims: Option<BTreeMap<String, String>>,
  pub challenge: Option<Vec<u8>>,
  pub challenge_responses: Option<Vec<Vec<u8>>>,
}

impl ConnectRequest {
  pub fn new<F1, F2, F3, F4, F5>(connection_id: F1, dock_addr: F2, claims: F3, challenge: F4, challenge_responses: F5) -> ConnectRequest where F1: Into<Option<i32>>, F2: Into<Option<Vec<u8>>>, F3: Into<Option<BTreeMap<String, String>>>, F4: Into<Option<Vec<u8>>>, F5: Into<Option<Vec<Vec<u8>>>> {
    ConnectRequest {
      connection_id: connection_id.into(),
      dock_addr: dock_addr.into(),
      claims: claims.into(),
      challenge: challenge.into(),
      challenge_responses: challenge_responses.into(),
    }
  }
}

impl TSerializable for ConnectRequest {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<ConnectRequest> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = Some(0);
    let mut f_2: Option<Vec<u8>> = Some(Vec::new());
    let mut f_3: Option<BTreeMap<String, String>> = Some(BTreeMap::new());
    let mut f_4: Option<Vec<u8>> = Some(Vec::new());
    let mut f_5: Option<Vec<Vec<u8>>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bytes()?;
          f_2 = Some(val);
        },
        3 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<String, String> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_3 = i_prot.read_string()?;
            let map_val_4 = i_prot.read_string()?;
            val.insert(map_key_3, map_val_4);
          }
          i_prot.read_map_end()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_bytes()?;
          f_4 = Some(val);
        },
        5 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<Vec<u8>> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_5 = i_prot.read_bytes()?;
            val.push(list_elem_5);
          }
          i_prot.read_list_end()?;
          f_5 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = ConnectRequest {
      connection_id: f_1,
      dock_addr: f_2,
      claims: f_3,
      challenge: f_4,
      challenge_responses: f_5,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("ConnectRequest");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.connection_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("connection_id", TType::I32, 1))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.dock_addr {
      o_prot.write_field_begin(&TFieldIdentifier::new("dock_addr", TType::String, 2))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.claims {
      o_prot.write_field_begin(&TFieldIdentifier::new("claims", TType::Map, 3))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::String, TType::String, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_string(k)?;
        o_prot.write_string(v)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.challenge {
      o_prot.write_field_begin(&TFieldIdentifier::new("challenge", TType::String, 4))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.challenge_responses {
      o_prot.write_field_begin(&TFieldIdentifier::new("challenge_responses", TType::List, 5))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::String, fld_var.len() as i32))?;
      for e in fld_var {
        o_prot.write_bytes(e)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// ConnectResponse
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ConnectResponse {
  pub connection_id: Option<i32>,
  pub status: Option<StatusCode>,
  pub agent: Option<Agent>,
  pub reason: Option<String>,
}

impl ConnectResponse {
  pub fn new<F1, F2, F3, F4>(connection_id: F1, status: F2, agent: F3, reason: F4) -> ConnectResponse where F1: Into<Option<i32>>, F2: Into<Option<StatusCode>>, F3: Into<Option<Agent>>, F4: Into<Option<String>> {
    ConnectResponse {
      connection_id: connection_id.into(),
      status: status.into(),
      agent: agent.into(),
      reason: reason.into(),
    }
  }
}

impl TSerializable for ConnectResponse {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<ConnectResponse> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = Some(0);
    let mut f_2: Option<StatusCode> = None;
    let mut f_3: Option<Agent> = None;
    let mut f_4: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = StatusCode::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        3 => {
          let val = Agent::read_from_in_protocol(i_prot)?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_string()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = ConnectResponse {
      connection_id: f_1,
      status: f_2,
      agent: f_3,
      reason: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("ConnectResponse");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.connection_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("connection_id", TType::I32, 1))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.status {
      o_prot.write_field_begin(&TFieldIdentifier::new("status", TType::I32, 2))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.agent {
      o_prot.write_field_begin(&TFieldIdentifier::new("agent", TType::Struct, 3))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.reason {
      o_prot.write_field_begin(&TFieldIdentifier::new("reason", TType::String, 4))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaHop
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct VisaHop {
  pub visa_pb: Option<Vec<u8>>,
  pub hop_count: Option<i32>,
  pub issuer_id: Option<i32>,
}

impl VisaHop {
  pub fn new<F1, F2, F3>(visa_pb: F1, hop_count: F2, issuer_id: F3) -> VisaHop where F1: Into<Option<Vec<u8>>>, F2: Into<Option<i32>>, F3: Into<Option<i32>> {
    VisaHop {
      visa_pb: visa_pb.into(),
      hop_count: hop_count.into(),
      issuer_id: issuer_id.into(),
    }
  }
}

impl TSerializable for VisaHop {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaHop> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<u8>> = Some(Vec::new());
    let mut f_2: Option<i32> = Some(0);
    let mut f_3: Option<i32> = Some(0);
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_bytes()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i32()?;
          f_3 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaHop {
      visa_pb: f_1,
      hop_count: f_2,
      issuer_id: f_3,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("VisaHop");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.visa_pb {
      o_prot.write_field_begin(&TFieldIdentifier::new("visa_pb", TType::String, 1))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.hop_count {
      o_prot.write_field_begin(&TFieldIdentifier::new("hop_count", TType::I32, 2))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.issuer_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("issuer_id", TType::I32, 3))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// Pong
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Pong {
  pub configuration: Option<i64>,
  pub policy_version: Option<i64>,
}

impl Pong {
  pub fn new<F1, F2>(configuration: F1, policy_version: F2) -> Pong where F1: Into<Option<i64>>, F2: Into<Option<i64>> {
    Pong {
      configuration: configuration.into(),
      policy_version: policy_version.into(),
    }
  }
}

impl TSerializable for Pong {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Pong> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = Some(0);
    let mut f_2: Option<i64> = Some(0);
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = Pong {
      configuration: f_1,
      policy_version: f_2,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("Pong");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.configuration {
      o_prot.write_field_begin(&TFieldIdentifier::new("configuration", TType::I64, 1))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.policy_version {
      o_prot.write_field_begin(&TFieldIdentifier::new("policy_version", TType::I64, 2))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TrafficDesc
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TrafficDesc {
  pub source: Option<Vec<u8>>,
  pub dest: Option<Vec<u8>>,
  pub protocol: Option<i32>,
  pub source_port: Option<i32>,
  pub dest_port: Option<i32>,
  pub flags: Option<i32>,
  pub icmp_type: Option<i16>,
  pub icmp_code: Option<i16>,
  pub size: Option<i32>,
  pub icmp_addr: Option<Vec<u8>>,
}

impl TrafficDesc {
  pub fn new<F1, F2, F3, F4, F5, F6, F7, F8, F9, F10>(source: F1, dest: F2, protocol: F3, source_port: F4, dest_port: F5, flags: F6, icmp_type: F7, icmp_code: F8, size: F9, icmp_addr: F10) -> TrafficDesc where F1: Into<Option<Vec<u8>>>, F2: Into<Option<Vec<u8>>>, F3: Into<Option<i32>>, F4: Into<Option<i32>>, F5: Into<Option<i32>>, F6: Into<Option<i32>>, F7: Into<Option<i16>>, F8: Into<Option<i16>>, F9: Into<Option<i32>>, F10: Into<Option<Vec<u8>>> {
    TrafficDesc {
      source: source.into(),
      dest: dest.into(),
      protocol: protocol.into(),
      source_port: source_port.into(),
      dest_port: dest_port.into(),
      flags: flags.into(),
      icmp_type: icmp_type.into(),
      icmp_code: icmp_code.into(),
      size: size.into(),
      icmp_addr: icmp_addr.into(),
    }
  }
}

impl TSerializable for TrafficDesc {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TrafficDesc> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<u8>> = Some(Vec::new());
    let mut f_2: Option<Vec<u8>> = Some(Vec::new());
    let mut f_3: Option<i32> = Some(0);
    let mut f_4: Option<i32> = Some(0);
    let mut f_5: Option<i32> = Some(0);
    let mut f_6: Option<i32> = Some(0);
    let mut f_7: Option<i16> = Some(0);
    let mut f_8: Option<i16> = Some(0);
    let mut f_9: Option<i32> = Some(0);
    let mut f_10: Option<Vec<u8>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_bytes()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bytes()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i32()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i32()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i32()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_i32()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_i16()?;
          f_7 = Some(val);
        },
        8 => {
          let val = i_prot.read_i16()?;
          f_8 = Some(val);
        },
        9 => {
          let val = i_prot.read_i32()?;
          f_9 = Some(val);
        },
        10 => {
          let val = i_prot.read_bytes()?;
          f_10 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = TrafficDesc {
      source: f_1,
      dest: f_2,
      protocol: f_3,
      source_port: f_4,
      dest_port: f_5,
      flags: f_6,
      icmp_type: f_7,
      icmp_code: f_8,
      size: f_9,
      icmp_addr: f_10,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TrafficDesc");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.source {
      o_prot.write_field_begin(&TFieldIdentifier::new("source", TType::String, 1))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.dest {
      o_prot.write_field_begin(&TFieldIdentifier::new("dest", TType::String, 2))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.protocol {
      o_prot.write_field_begin(&TFieldIdentifier::new("protocol", TType::I32, 3))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.source_port {
      o_prot.write_field_begin(&TFieldIdentifier::new("source_port", TType::I32, 4))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.dest_port {
      o_prot.write_field_begin(&TFieldIdentifier::new("dest_port", TType::I32, 5))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.flags {
      o_prot.write_field_begin(&TFieldIdentifier::new("flags", TType::I32, 6))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.icmp_type {
      o_prot.write_field_begin(&TFieldIdentifier::new("icmp_type", TType::I16, 7))?;
      o_prot.write_i16(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.icmp_code {
      o_prot.write_field_begin(&TFieldIdentifier::new("icmp_code", TType::I16, 8))?;
      o_prot.write_i16(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.size {
      o_prot.write_field_begin(&TFieldIdentifier::new("size", TType::I32, 9))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.icmp_addr {
      o_prot.write_field_begin(&TFieldIdentifier::new("icmp_addr", TType::String, 10))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaResponse
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct VisaResponse {
  pub status: Option<StatusCode>,
  pub visa: Option<VisaHop>,
  pub reason: Option<String>,
}

impl VisaResponse {
  pub fn new<F1, F2, F3>(status: F1, visa: F2, reason: F3) -> VisaResponse where F1: Into<Option<StatusCode>>, F2: Into<Option<VisaHop>>, F3: Into<Option<String>> {
    VisaResponse {
      status: status.into(),
      visa: visa.into(),
      reason: reason.into(),
    }
  }
}

impl TSerializable for VisaResponse {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaResponse> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<StatusCode> = None;
    let mut f_2: Option<VisaHop> = None;
    let mut f_3: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = StatusCode::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        2 => {
          let val = VisaHop::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_string()?;
          f_3 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaResponse {
      status: f_1,
      visa: f_2,
      reason: f_3,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("VisaResponse");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.status {
      o_prot.write_field_begin(&TFieldIdentifier::new("status", TType::I32, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.visa {
      o_prot.write_field_begin(&TFieldIdentifier::new("visa", TType::Struct, 2))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.reason {
      o_prot.write_field_begin(&TFieldIdentifier::new("reason", TType::String, 3))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

pub const CHALLENGE_TYPE_HMAC_SHA256: i32 = 0;

//
// VisaService service client
//

pub trait TVisaServiceSyncClient {
  fn hello(&mut self) -> thrift::Result<HelloResponse>;
  fn authenticate(&mut self, auth_request: NodeAuthRequest) -> thrift::Result<String>;
  fn de_register(&mut self, key: String) -> thrift::Result<()>;
  fn authorize_connect(&mut self, key: String, request: ConnectRequest) -> thrift::Result<ConnectResponse>;
  fn agent_disconnect(&mut self, keym: String, zpr_addr: Vec<u8>) -> thrift::Result<()>;
  fn ping(&mut self, key: String) -> thrift::Result<Pong>;
  fn request_visa(&mut self, key: String, src_tether_addr: Vec<u8>, traffic: TrafficDesc) -> thrift::Result<VisaResponse>;
}

pub trait TVisaServiceSyncClientMarker {}

pub struct VisaServiceSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  _i_prot: IP,
  _o_prot: OP,
  _sequence_number: i32,
}

impl <IP, OP> VisaServiceSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  pub fn new(input_protocol: IP, output_protocol: OP) -> VisaServiceSyncClient<IP, OP> {
    VisaServiceSyncClient { _i_prot: input_protocol, _o_prot: output_protocol, _sequence_number: 0 }
  }
}

impl <IP, OP> TThriftClient for VisaServiceSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  fn i_prot_mut(&mut self) -> &mut dyn TInputProtocol { &mut self._i_prot }
  fn o_prot_mut(&mut self) -> &mut dyn TOutputProtocol { &mut self._o_prot }
  fn sequence_number(&self) -> i32 { self._sequence_number }
  fn increment_sequence_number(&mut self) -> i32 { self._sequence_number += 1; self._sequence_number }
}

impl <IP, OP> TVisaServiceSyncClientMarker for VisaServiceSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {}

impl <C: TThriftClient + TVisaServiceSyncClientMarker> TVisaServiceSyncClient for C {
  fn hello(&mut self) -> thrift::Result<HelloResponse> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("hello", TMessageType::Call, self.sequence_number());
        let call_args = VisaServiceHelloArgs {  };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("hello", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = VisaServiceHelloResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn authenticate(&mut self, auth_request: NodeAuthRequest) -> thrift::Result<String> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("authenticate", TMessageType::Call, self.sequence_number());
        let call_args = VisaServiceAuthenticateArgs { auth_request };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("authenticate", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = VisaServiceAuthenticateResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn de_register(&mut self, key: String) -> thrift::Result<()> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("de_register", TMessageType::OneWay, self.sequence_number());
        let call_args = VisaServiceDeRegisterArgs { key };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    Ok(())
  }
  fn authorize_connect(&mut self, key: String, request: ConnectRequest) -> thrift::Result<ConnectResponse> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("authorize_connect", TMessageType::Call, self.sequence_number());
        let call_args = VisaServiceAuthorizeConnectArgs { key, request };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("authorize_connect", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = VisaServiceAuthorizeConnectResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn agent_disconnect(&mut self, keym: String, zpr_addr: Vec<u8>) -> thrift::Result<()> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("agent_disconnect", TMessageType::Call, self.sequence_number());
        let call_args = VisaServiceAgentDisconnectArgs { keym, zpr_addr };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("agent_disconnect", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = VisaServiceAgentDisconnectResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn ping(&mut self, key: String) -> thrift::Result<Pong> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("ping", TMessageType::Call, self.sequence_number());
        let call_args = VisaServicePingArgs { key };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("ping", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = VisaServicePingResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn request_visa(&mut self, key: String, src_tether_addr: Vec<u8>, traffic: TrafficDesc) -> thrift::Result<VisaResponse> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("request_visa", TMessageType::Call, self.sequence_number());
        let call_args = VisaServiceRequestVisaArgs { key, src_tether_addr, traffic };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("request_visa", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = VisaServiceRequestVisaResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
}

//
// VisaService service processor
//

pub trait VisaServiceSyncHandler {
  fn handle_hello(&self) -> thrift::Result<HelloResponse>;
  fn handle_authenticate(&self, auth_request: NodeAuthRequest) -> thrift::Result<String>;
  fn handle_de_register(&self, key: String) -> thrift::Result<()>;
  fn handle_authorize_connect(&self, key: String, request: ConnectRequest) -> thrift::Result<ConnectResponse>;
  fn handle_agent_disconnect(&self, keym: String, zpr_addr: Vec<u8>) -> thrift::Result<()>;
  fn handle_ping(&self, key: String) -> thrift::Result<Pong>;
  fn handle_request_visa(&self, key: String, src_tether_addr: Vec<u8>, traffic: TrafficDesc) -> thrift::Result<VisaResponse>;
}

pub struct VisaServiceSyncProcessor<H: VisaServiceSyncHandler> {
  handler: H,
}

impl <H: VisaServiceSyncHandler> VisaServiceSyncProcessor<H> {
  pub fn new(handler: H) -> VisaServiceSyncProcessor<H> {
    VisaServiceSyncProcessor {
      handler,
    }
  }
  fn process_hello(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TVisaServiceProcessFunctions::process_hello(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_authenticate(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TVisaServiceProcessFunctions::process_authenticate(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_de_register(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TVisaServiceProcessFunctions::process_de_register(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_authorize_connect(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TVisaServiceProcessFunctions::process_authorize_connect(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_agent_disconnect(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TVisaServiceProcessFunctions::process_agent_disconnect(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_ping(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TVisaServiceProcessFunctions::process_ping(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_request_visa(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TVisaServiceProcessFunctions::process_request_visa(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
}

pub struct TVisaServiceProcessFunctions;

impl TVisaServiceProcessFunctions {
  pub fn process_hello<H: VisaServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let _ = VisaServiceHelloArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_hello() {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("hello", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = VisaServiceHelloResult { result_value: Some(handler_return) };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("hello", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("hello", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_authenticate<H: VisaServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = VisaServiceAuthenticateArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_authenticate(args.auth_request) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("authenticate", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = VisaServiceAuthenticateResult { result_value: Some(handler_return) };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("authenticate", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("authenticate", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_de_register<H: VisaServiceSyncHandler>(handler: &H, _: i32, i_prot: &mut dyn TInputProtocol, _: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = VisaServiceDeRegisterArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_de_register(args.key) {
      Ok(_) => {
        Ok(())
      },
      Err(e) => {
        match e {
          thrift::Error::Application(app_err) => {
            Err(thrift::Error::Application(app_err))
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            Err(thrift::Error::Application(ret_err))
          },
        }
      },
    }
  }
  pub fn process_authorize_connect<H: VisaServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = VisaServiceAuthorizeConnectArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_authorize_connect(args.key, args.request) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("authorize_connect", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = VisaServiceAuthorizeConnectResult { result_value: Some(handler_return) };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("authorize_connect", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("authorize_connect", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_agent_disconnect<H: VisaServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = VisaServiceAgentDisconnectArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_agent_disconnect(args.keym, args.zpr_addr) {
      Ok(_) => {
        let message_ident = TMessageIdentifier::new("agent_disconnect", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = VisaServiceAgentDisconnectResult {  };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("agent_disconnect", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("agent_disconnect", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_ping<H: VisaServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = VisaServicePingArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_ping(args.key) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("ping", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = VisaServicePingResult { result_value: Some(handler_return) };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("ping", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("ping", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_request_visa<H: VisaServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = VisaServiceRequestVisaArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_request_visa(args.key, args.src_tether_addr, args.traffic) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("request_visa", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = VisaServiceRequestVisaResult { result_value: Some(handler_return) };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("request_visa", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("request_visa", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
}

impl <H: VisaServiceSyncHandler> TProcessor for VisaServiceSyncProcessor<H> {
  fn process(&self, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let message_ident = i_prot.read_message_begin()?;
    let res = match &*message_ident.name {
      "hello" => {
        self.process_hello(message_ident.sequence_number, i_prot, o_prot)
      },
      "authenticate" => {
        self.process_authenticate(message_ident.sequence_number, i_prot, o_prot)
      },
      "de_register" => {
        self.process_de_register(message_ident.sequence_number, i_prot, o_prot)
      },
      "authorize_connect" => {
        self.process_authorize_connect(message_ident.sequence_number, i_prot, o_prot)
      },
      "agent_disconnect" => {
        self.process_agent_disconnect(message_ident.sequence_number, i_prot, o_prot)
      },
      "ping" => {
        self.process_ping(message_ident.sequence_number, i_prot, o_prot)
      },
      "request_visa" => {
        self.process_request_visa(message_ident.sequence_number, i_prot, o_prot)
      },
      method => {
        Err(
          thrift::Error::Application(
            ApplicationError::new(
              ApplicationErrorKind::UnknownMethod,
              format!("unknown method {}", method)
            )
          )
        )
      },
    };
    thrift::server::handle_process_result(&message_ident, res, o_prot)
  }
}

//
// VisaServiceHelloArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceHelloArgs {
}

impl VisaServiceHelloArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceHelloArgs> {
    i_prot.read_struct_begin()?;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      i_prot.skip(field_ident.field_type)?;
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaServiceHelloArgs {};
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("hello_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceHelloResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceHelloResult {
  result_value: Option<HelloResponse>,
}

impl VisaServiceHelloResult {
  fn ok_or(self) -> thrift::Result<HelloResponse> {
    if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for VisaServiceHello"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceHelloResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<HelloResponse> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = HelloResponse::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaServiceHelloResult {
      result_value: f_0,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("VisaServiceHelloResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceAuthenticateArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceAuthenticateArgs {
  auth_request: NodeAuthRequest,
}

impl VisaServiceAuthenticateArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceAuthenticateArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<NodeAuthRequest> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = NodeAuthRequest::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("VisaServiceAuthenticateArgs.auth_request", &f_1)?;
    let ret = VisaServiceAuthenticateArgs {
      auth_request: f_1.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("authenticate_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("auth_request", TType::Struct, 1))?;
    self.auth_request.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceAuthenticateResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceAuthenticateResult {
  result_value: Option<String>,
}

impl VisaServiceAuthenticateResult {
  fn ok_or(self) -> thrift::Result<String> {
    if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for VisaServiceAuthenticate"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceAuthenticateResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = i_prot.read_string()?;
          f_0 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaServiceAuthenticateResult {
      result_value: f_0,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("VisaServiceAuthenticateResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::String, 0))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceDeRegisterArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceDeRegisterArgs {
  key: String,
}

impl VisaServiceDeRegisterArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceDeRegisterArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("VisaServiceDeRegisterArgs.key", &f_1)?;
    let ret = VisaServiceDeRegisterArgs {
      key: f_1.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("de_register_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("key", TType::String, 1))?;
    o_prot.write_string(&self.key)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceAuthorizeConnectArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceAuthorizeConnectArgs {
  key: String,
  request: ConnectRequest,
}

impl VisaServiceAuthorizeConnectArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceAuthorizeConnectArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    let mut f_2: Option<ConnectRequest> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = ConnectRequest::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("VisaServiceAuthorizeConnectArgs.key", &f_1)?;
    verify_required_field_exists("VisaServiceAuthorizeConnectArgs.request", &f_2)?;
    let ret = VisaServiceAuthorizeConnectArgs {
      key: f_1.expect("auto-generated code should have checked for presence of required fields"),
      request: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("authorize_connect_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("key", TType::String, 1))?;
    o_prot.write_string(&self.key)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("request", TType::Struct, 2))?;
    self.request.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceAuthorizeConnectResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceAuthorizeConnectResult {
  result_value: Option<ConnectResponse>,
}

impl VisaServiceAuthorizeConnectResult {
  fn ok_or(self) -> thrift::Result<ConnectResponse> {
    if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for VisaServiceAuthorizeConnect"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceAuthorizeConnectResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<ConnectResponse> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = ConnectResponse::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaServiceAuthorizeConnectResult {
      result_value: f_0,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("VisaServiceAuthorizeConnectResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceAgentDisconnectArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceAgentDisconnectArgs {
  keym: String,
  zpr_addr: Vec<u8>,
}

impl VisaServiceAgentDisconnectArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceAgentDisconnectArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    let mut f_2: Option<Vec<u8>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bytes()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("VisaServiceAgentDisconnectArgs.keym", &f_1)?;
    verify_required_field_exists("VisaServiceAgentDisconnectArgs.zpr_addr", &f_2)?;
    let ret = VisaServiceAgentDisconnectArgs {
      keym: f_1.expect("auto-generated code should have checked for presence of required fields"),
      zpr_addr: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("agent_disconnect_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("keym", TType::String, 1))?;
    o_prot.write_string(&self.keym)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("zpr_addr", TType::String, 2))?;
    o_prot.write_bytes(&self.zpr_addr)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceAgentDisconnectResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceAgentDisconnectResult {
}

impl VisaServiceAgentDisconnectResult {
  fn ok_or(self) -> thrift::Result<()> {
    Ok(())
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceAgentDisconnectResult> {
    i_prot.read_struct_begin()?;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      i_prot.skip(field_ident.field_type)?;
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaServiceAgentDisconnectResult {};
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("VisaServiceAgentDisconnectResult");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServicePingArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServicePingArgs {
  key: String,
}

impl VisaServicePingArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServicePingArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("VisaServicePingArgs.key", &f_1)?;
    let ret = VisaServicePingArgs {
      key: f_1.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("ping_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("key", TType::String, 1))?;
    o_prot.write_string(&self.key)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServicePingResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServicePingResult {
  result_value: Option<Pong>,
}

impl VisaServicePingResult {
  fn ok_or(self) -> thrift::Result<Pong> {
    if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for VisaServicePing"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServicePingResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<Pong> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = Pong::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaServicePingResult {
      result_value: f_0,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("VisaServicePingResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceRequestVisaArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceRequestVisaArgs {
  key: String,
  src_tether_addr: Vec<u8>,
  traffic: TrafficDesc,
}

impl VisaServiceRequestVisaArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceRequestVisaArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    let mut f_2: Option<Vec<u8>> = None;
    let mut f_3: Option<TrafficDesc> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bytes()?;
          f_2 = Some(val);
        },
        3 => {
          let val = TrafficDesc::read_from_in_protocol(i_prot)?;
          f_3 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("VisaServiceRequestVisaArgs.key", &f_1)?;
    verify_required_field_exists("VisaServiceRequestVisaArgs.src_tether_addr", &f_2)?;
    verify_required_field_exists("VisaServiceRequestVisaArgs.traffic", &f_3)?;
    let ret = VisaServiceRequestVisaArgs {
      key: f_1.expect("auto-generated code should have checked for presence of required fields"),
      src_tether_addr: f_2.expect("auto-generated code should have checked for presence of required fields"),
      traffic: f_3.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("request_visa_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("key", TType::String, 1))?;
    o_prot.write_string(&self.key)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("src_tether_addr", TType::String, 2))?;
    o_prot.write_bytes(&self.src_tether_addr)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("traffic", TType::Struct, 3))?;
    self.traffic.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// VisaServiceRequestVisaResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct VisaServiceRequestVisaResult {
  result_value: Option<VisaResponse>,
}

impl VisaServiceRequestVisaResult {
  fn ok_or(self) -> thrift::Result<VisaResponse> {
    if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for VisaServiceRequestVisa"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<VisaServiceRequestVisaResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<VisaResponse> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = VisaResponse::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = VisaServiceRequestVisaResult {
      result_value: f_0,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("VisaServiceRequestVisaResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

