# config for a "client" adapter which talks to the service.

[global]
name = "client"
ca_file = "ca-cert.pem"
certificate_file = "adapter-client-cert.pem"
private_key_file = "adapter-client-key.pem"
zpr_addr = [ "fd5a:5052:1::3133:7" ]
self_addr = "0.0.0.0:5000"

# use `sudo mktun.sh` to set this up
tun_if = "tun9"

[adapter]
node_addr = "172.16.1.1:5000"
node_public_key_file = "node-pubkey.pem"








