// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: vss/visa_service_support.proto

package vss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	vsio "zpr.org/vsx/snio/vsio"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallType int32

const (
	InstallType_VSS_INSTALL_TYPE_POLICY    InstallType = 0
	InstallType_VSS_INSTALL_TYPE_BOOTSTRAP InstallType = 1
)

// Enum value maps for InstallType.
var (
	InstallType_name = map[int32]string{
		0: "VSS_INSTALL_TYPE_POLICY",
		1: "VSS_INSTALL_TYPE_BOOTSTRAP",
	}
	InstallType_value = map[string]int32{
		"VSS_INSTALL_TYPE_POLICY":    0,
		"VSS_INSTALL_TYPE_BOOTSTRAP": 1,
	}
)

func (x InstallType) Enum() *InstallType {
	p := new(InstallType)
	*p = x
	return p
}

func (x InstallType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallType) Descriptor() protoreflect.EnumDescriptor {
	return file_vss_visa_service_support_proto_enumTypes[0].Descriptor()
}

func (InstallType) Type() protoreflect.EnumType {
	return &file_vss_visa_service_support_proto_enumTypes[0]
}

func (x InstallType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallType.Descriptor instead.
func (InstallType) EnumDescriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{0}
}

type LookupAgentKey int32

const (
	LookupAgentKey_LOOKUP_KEY_CONTACT_ADDR LookupAgentKey = 0
)

// Enum value maps for LookupAgentKey.
var (
	LookupAgentKey_name = map[int32]string{
		0: "LOOKUP_KEY_CONTACT_ADDR",
	}
	LookupAgentKey_value = map[string]int32{
		"LOOKUP_KEY_CONTACT_ADDR": 0,
	}
)

func (x LookupAgentKey) Enum() *LookupAgentKey {
	p := new(LookupAgentKey)
	*p = x
	return p
}

func (x LookupAgentKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LookupAgentKey) Descriptor() protoreflect.EnumDescriptor {
	return file_vss_visa_service_support_proto_enumTypes[1].Descriptor()
}

func (LookupAgentKey) Type() protoreflect.EnumType {
	return &file_vss_visa_service_support_proto_enumTypes[1]
}

func (x LookupAgentKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LookupAgentKey.Descriptor instead.
func (LookupAgentKey) EnumDescriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{1}
}

// HelloRequest is from visa service to its docking node
// Left empty for future expansion ;)
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{0}
}

// HelloResponse is a reply from node to visa service. Include a challenge for
// the visa service to reply to in order to be allowed to proceed.
type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChallengeType string `protobuf:"bytes,1,opt,name=challenge_type,json=challengeType,proto3" json:"challenge_type,omitempty"`
	Challenge     []byte `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetChallengeType() string {
	if x != nil {
		return x.ChallengeType
	}
	return ""
}

func (x *HelloResponse) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// AuthRquest is from visa service to the node. Includes a reply to the challenge
// presented in the HelloResponse.  Also includes a `access_token` which the node
// must furnish when it wants to use privileged functions in the visa service API.
type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge         []byte `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	ChallengeResponse []byte `protobuf:"bytes,2,opt,name=challenge_response,json=challengeResponse,proto3" json:"challenge_response,omitempty"`
	AccessToken       []byte `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // TODO: used for access to extra functions in visa service (I think...)
	VsTlsName         string `protobuf:"bytes,4,opt,name=vs_tls_name,json=vsTlsName,proto3" json:"vs_tls_name,omitempty"`     // TLS name to use when grpc'ing to the visa service
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *AuthRequest) GetChallengeResponse() []byte {
	if x != nil {
		return x.ChallengeResponse
	}
	return nil
}

func (x *AuthRequest) GetAccessToken() []byte {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *AuthRequest) GetVsTlsName() string {
	if x != nil {
		return x.VsTlsName
	}
	return ""
}

// AuthResponse is from the node to the visa service.  This is the final handshake
// message and indicates a successful autentication of the visa service to the node.AClaim
//
// The node includes the tether address assigned to the visa service so that the
// visa service is able to create a valid visa for initial communications with the node.
type AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TetherAddr []byte `protobuf:"bytes,1,opt,name=tether_addr,json=tetherAddr,proto3" json:"tether_addr,omitempty"` // The tether address assigned to visa service by dock
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetTetherAddr() []byte {
	if x != nil {
		return x.TetherAddr
	}
	return nil
}

type VisaBuffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VsData []byte `protobuf:"bytes,1,opt,name=vs_data,json=vsData,proto3" json:"vs_data,omitempty"` // visa in protocol buffer format
}

func (x *VisaBuffer) Reset() {
	*x = VisaBuffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisaBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisaBuffer) ProtoMessage() {}

func (x *VisaBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisaBuffer.ProtoReflect.Descriptor instead.
func (*VisaBuffer) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{4}
}

func (x *VisaBuffer) GetVsData() []byte {
	if x != nil {
		return x.VsData
	}
	return nil
}

// Installs a policy with optional visas.
type InstallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstallType   InstallType   `protobuf:"varint,1,opt,name=install_type,json=installType,proto3,enum=vss.InstallType" json:"install_type,omitempty"`
	PayloadFormat uint32        `protobuf:"varint,2,opt,name=payload_format,json=payloadFormat,proto3" json:"payload_format,omitempty"`
	Payload       []byte        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // the policy contaner
	ConfigId      uint64        `protobuf:"varint,4,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Visas         []*VisaBuffer `protobuf:"bytes,5,rep,name=visas,proto3" json:"visas,omitempty"` // visa-service and visa-support-service  visas for current policy
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{5}
}

func (x *InstallRequest) GetInstallType() InstallType {
	if x != nil {
		return x.InstallType
	}
	return InstallType_VSS_INSTALL_TYPE_POLICY
}

func (x *InstallRequest) GetPayloadFormat() uint32 {
	if x != nil {
		return x.PayloadFormat
	}
	return 0
}

func (x *InstallRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InstallRequest) GetConfigId() uint64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *InstallRequest) GetVisas() []*VisaBuffer {
	if x != nil {
		return x.Visas
	}
	return nil
}

type InstallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ConfigId uint64 `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
}

func (x *InstallResponse) Reset() {
	*x = InstallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResponse) ProtoMessage() {}

func (x *InstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResponse.ProtoReflect.Descriptor instead.
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{6}
}

func (x *InstallResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallResponse) GetConfigId() uint64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

type LookupAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     LookupAgentKey `protobuf:"varint,1,opt,name=key,proto3,enum=vss.LookupAgentKey" json:"key,omitempty"`
	Address []byte         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *LookupAgentRequest) Reset() {
	*x = LookupAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAgentRequest) ProtoMessage() {}

func (x *LookupAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAgentRequest.ProtoReflect.Descriptor instead.
func (*LookupAgentRequest) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{7}
}

func (x *LookupAgentRequest) GetKey() LookupAgentKey {
	if x != nil {
		return x.Key
	}
	return LookupAgentKey_LOOKUP_KEY_CONTACT_ADDR
}

func (x *LookupAgentRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type LookupAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent *vsio.Agent `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"` // Will be nil if not found
}

func (x *LookupAgentResponse) Reset() {
	*x = LookupAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vss_visa_service_support_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAgentResponse) ProtoMessage() {}

func (x *LookupAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vss_visa_service_support_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAgentResponse.ProtoReflect.Descriptor instead.
func (*LookupAgentResponse) Descriptor() ([]byte, []int) {
	return file_vss_visa_service_support_proto_rawDescGZIP(), []int{8}
}

func (x *LookupAgentResponse) GetAgent() *vsio.Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

var File_vss_visa_service_support_proto protoreflect.FileDescriptor

var file_vss_visa_service_support_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x76, 0x73, 0x73, 0x2f, 0x76, 0x69, 0x73, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x76, 0x73, 0x73, 0x1a, 0x10, 0x76, 0x73, 0x69, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x9d, 0x01,
	0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a,
	0x0b, 0x76, 0x73, 0x5f, 0x74, 0x6c, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x76, 0x73, 0x54, 0x6c, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a,
	0x0c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x65, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x74, 0x65, 0x74, 0x68, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x22, 0x25,
	0x0a, 0x0a, 0x56, 0x69, 0x73, 0x61, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07,
	0x76, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x76,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0xca, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x76, 0x73, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x76,
	0x69, 0x73, 0x61, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x73, 0x73,
	0x2e, 0x56, 0x69, 0x73, 0x61, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x05, 0x76, 0x69, 0x73,
	0x61, 0x73, 0x22, 0x48, 0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x12,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x76, 0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x38, 0x0a, 0x13, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x73, 0x69, 0x6f,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2a, 0x4a, 0x0a,
	0x0b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17,
	0x56, 0x53, 0x53, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x56, 0x53, 0x53,
	0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x4f,
	0x4f, 0x54, 0x53, 0x54, 0x52, 0x41, 0x50, 0x10, 0x01, 0x2a, 0x2d, 0x0a, 0x0e, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x17, 0x4c,
	0x4f, 0x4f, 0x4b, 0x55, 0x50, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x43,
	0x54, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x10, 0x00, 0x32, 0x87, 0x02, 0x0a, 0x12, 0x56, 0x69, 0x73,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x3b, 0x0a, 0x10, 0x56, 0x69, 0x73, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x11, 0x2e, 0x76, 0x73, 0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x76, 0x73, 0x73, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0f,
	0x56, 0x69, 0x73, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x10, 0x2e, 0x76, 0x73, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x76, 0x73, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x07, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x12, 0x13, 0x2e, 0x76, 0x73, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x76, 0x73, 0x73, 0x2e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42,
	0x0a, 0x0b, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e,
	0x76, 0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x7a, 0x70, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x76, 0x73,
	0x78, 0x2f, 0x73, 0x6e, 0x69, 0x6f, 0x2f, 0x76, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_vss_visa_service_support_proto_rawDescOnce sync.Once
	file_vss_visa_service_support_proto_rawDescData = file_vss_visa_service_support_proto_rawDesc
)

func file_vss_visa_service_support_proto_rawDescGZIP() []byte {
	file_vss_visa_service_support_proto_rawDescOnce.Do(func() {
		file_vss_visa_service_support_proto_rawDescData = protoimpl.X.CompressGZIP(file_vss_visa_service_support_proto_rawDescData)
	})
	return file_vss_visa_service_support_proto_rawDescData
}

var file_vss_visa_service_support_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vss_visa_service_support_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_vss_visa_service_support_proto_goTypes = []interface{}{
	(InstallType)(0),            // 0: vss.InstallType
	(LookupAgentKey)(0),         // 1: vss.LookupAgentKey
	(*HelloRequest)(nil),        // 2: vss.HelloRequest
	(*HelloResponse)(nil),       // 3: vss.HelloResponse
	(*AuthRequest)(nil),         // 4: vss.AuthRequest
	(*AuthResponse)(nil),        // 5: vss.AuthResponse
	(*VisaBuffer)(nil),          // 6: vss.VisaBuffer
	(*InstallRequest)(nil),      // 7: vss.InstallRequest
	(*InstallResponse)(nil),     // 8: vss.InstallResponse
	(*LookupAgentRequest)(nil),  // 9: vss.LookupAgentRequest
	(*LookupAgentResponse)(nil), // 10: vss.LookupAgentResponse
	(*vsio.Agent)(nil),          // 11: vsio.Agent
}
var file_vss_visa_service_support_proto_depIdxs = []int32{
	0,  // 0: vss.InstallRequest.install_type:type_name -> vss.InstallType
	6,  // 1: vss.InstallRequest.visas:type_name -> vss.VisaBuffer
	1,  // 2: vss.LookupAgentRequest.key:type_name -> vss.LookupAgentKey
	11, // 3: vss.LookupAgentResponse.agent:type_name -> vsio.Agent
	2,  // 4: vss.VisaServiceSupport.VisaServiceHello:input_type -> vss.HelloRequest
	4,  // 5: vss.VisaServiceSupport.VisaServiceAuth:input_type -> vss.AuthRequest
	7,  // 6: vss.VisaServiceSupport.Install:input_type -> vss.InstallRequest
	9,  // 7: vss.VisaServiceSupport.LookupAgent:input_type -> vss.LookupAgentRequest
	3,  // 8: vss.VisaServiceSupport.VisaServiceHello:output_type -> vss.HelloResponse
	5,  // 9: vss.VisaServiceSupport.VisaServiceAuth:output_type -> vss.AuthResponse
	8,  // 10: vss.VisaServiceSupport.Install:output_type -> vss.InstallResponse
	10, // 11: vss.VisaServiceSupport.LookupAgent:output_type -> vss.LookupAgentResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_vss_visa_service_support_proto_init() }
func file_vss_visa_service_support_proto_init() {
	if File_vss_visa_service_support_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vss_visa_service_support_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vss_visa_service_support_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vss_visa_service_support_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vss_visa_service_support_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vss_visa_service_support_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisaBuffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vss_visa_service_support_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vss_visa_service_support_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vss_visa_service_support_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vss_visa_service_support_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vss_visa_service_support_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vss_visa_service_support_proto_goTypes,
		DependencyIndexes: file_vss_visa_service_support_proto_depIdxs,
		EnumInfos:         file_vss_visa_service_support_proto_enumTypes,
		MessageInfos:      file_vss_visa_service_support_proto_msgTypes,
	}.Build()
	File_vss_visa_service_support_proto = out.File
	file_vss_visa_service_support_proto_rawDesc = nil
	file_vss_visa_service_support_proto_goTypes = nil
	file_vss_visa_service_support_proto_depIdxs = nil
}
