// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: vss/visa_service_support.proto

package vss

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	VisaServiceSupport_VisaServiceHello_FullMethodName = "/vss.VisaServiceSupport/VisaServiceHello"
	VisaServiceSupport_VisaServiceAuth_FullMethodName  = "/vss.VisaServiceSupport/VisaServiceAuth"
	VisaServiceSupport_Install_FullMethodName          = "/vss.VisaServiceSupport/Install"
	VisaServiceSupport_LookupAgent_FullMethodName      = "/vss.VisaServiceSupport/LookupAgent"
)

// VisaServiceSupportClient is the client API for VisaServiceSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisaServiceSupportClient interface {
	// Bootstrap functions
	VisaServiceHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	VisaServiceAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*InstallResponse, error)
	// Visa Service interface into the RAFT based datastore
	LookupAgent(ctx context.Context, in *LookupAgentRequest, opts ...grpc.CallOption) (*LookupAgentResponse, error)
}

type visaServiceSupportClient struct {
	cc grpc.ClientConnInterface
}

func NewVisaServiceSupportClient(cc grpc.ClientConnInterface) VisaServiceSupportClient {
	return &visaServiceSupportClient{cc}
}

func (c *visaServiceSupportClient) VisaServiceHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, VisaServiceSupport_VisaServiceHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceSupportClient) VisaServiceAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, VisaServiceSupport_VisaServiceAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceSupportClient) Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*InstallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallResponse)
	err := c.cc.Invoke(ctx, VisaServiceSupport_Install_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visaServiceSupportClient) LookupAgent(ctx context.Context, in *LookupAgentRequest, opts ...grpc.CallOption) (*LookupAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupAgentResponse)
	err := c.cc.Invoke(ctx, VisaServiceSupport_LookupAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisaServiceSupportServer is the server API for VisaServiceSupport service.
// All implementations must embed UnimplementedVisaServiceSupportServer
// for forward compatibility
type VisaServiceSupportServer interface {
	// Bootstrap functions
	VisaServiceHello(context.Context, *HelloRequest) (*HelloResponse, error)
	VisaServiceAuth(context.Context, *AuthRequest) (*AuthResponse, error)
	Install(context.Context, *InstallRequest) (*InstallResponse, error)
	// Visa Service interface into the RAFT based datastore
	LookupAgent(context.Context, *LookupAgentRequest) (*LookupAgentResponse, error)
	mustEmbedUnimplementedVisaServiceSupportServer()
}

// UnimplementedVisaServiceSupportServer must be embedded to have forward compatible implementations.
type UnimplementedVisaServiceSupportServer struct {
}

func (UnimplementedVisaServiceSupportServer) VisaServiceHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisaServiceHello not implemented")
}
func (UnimplementedVisaServiceSupportServer) VisaServiceAuth(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisaServiceAuth not implemented")
}
func (UnimplementedVisaServiceSupportServer) Install(context.Context, *InstallRequest) (*InstallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedVisaServiceSupportServer) LookupAgent(context.Context, *LookupAgentRequest) (*LookupAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupAgent not implemented")
}
func (UnimplementedVisaServiceSupportServer) mustEmbedUnimplementedVisaServiceSupportServer() {}

// UnsafeVisaServiceSupportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisaServiceSupportServer will
// result in compilation errors.
type UnsafeVisaServiceSupportServer interface {
	mustEmbedUnimplementedVisaServiceSupportServer()
}

func RegisterVisaServiceSupportServer(s grpc.ServiceRegistrar, srv VisaServiceSupportServer) {
	s.RegisterService(&VisaServiceSupport_ServiceDesc, srv)
}

func _VisaServiceSupport_VisaServiceHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceSupportServer).VisaServiceHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaServiceSupport_VisaServiceHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceSupportServer).VisaServiceHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaServiceSupport_VisaServiceAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceSupportServer).VisaServiceAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaServiceSupport_VisaServiceAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceSupportServer).VisaServiceAuth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaServiceSupport_Install_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceSupportServer).Install(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaServiceSupport_Install_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceSupportServer).Install(ctx, req.(*InstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisaServiceSupport_LookupAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaServiceSupportServer).LookupAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisaServiceSupport_LookupAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaServiceSupportServer).LookupAgent(ctx, req.(*LookupAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisaServiceSupport_ServiceDesc is the grpc.ServiceDesc for VisaServiceSupport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisaServiceSupport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vss.VisaServiceSupport",
	HandlerType: (*VisaServiceSupportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VisaServiceHello",
			Handler:    _VisaServiceSupport_VisaServiceHello_Handler,
		},
		{
			MethodName: "VisaServiceAuth",
			Handler:    _VisaServiceSupport_VisaServiceAuth_Handler,
		},
		{
			MethodName: "Install",
			Handler:    _VisaServiceSupport_Install_Handler,
		},
		{
			MethodName: "LookupAgent",
			Handler:    _VisaServiceSupport_LookupAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vss/visa_service_support.proto",
}
