[global]
name = "cli"
ca_file = "auth-ca.crt"
certificate_file = "adapter-cli-noise.crt"
private_key_file = "adapter-cli-noise.key"

[adapter]
node_addr = "192.168.6.176:5000"
node_public_key_file = "node-noise-pub.pem"

[authentication]
bas_key = "adapter-cli-bas.key"








