[global]
name = "cli"
ca_file = "auth-ca.crt"
certificate_file = "adapter-cli-noise.crt"
private_key_file = "adapter-cli-noise.key"
zpr_addr = [ "fd5a:5052:1::20" ] 
self_addr = "SUBSTRATE_ADDR_HERE:5000"

# use `sudo ./mktun.sh` to set this up
tun_if = "tun9"


[adapter]
node_addr = "192.168.4.69:5000"
node_public_key_file = "node-noise-pub.pem"









