[package]
name = "ph-test"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayref = { version = "0.3.7" }
foreign-types = { version = "0.3.2" }
libc = { version = "0.2.155" }
nix = { version = "0.28.0", features = ["fs", "net", "socket", "uio"] }
openssl = { version = "0.10.64" }
openssl-sys = { version = "0.9.102" }
tokio = { version = "1.37.0", features = ["full"] }
tokio-openssl = { version = "0.6.4" }
zerocopy = { version = "0.7.34", features = ["byteorder"] }
zerocopy-derive = { version = "0.7.34" }
