[package]
name = "ph"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
admin-api = { path = "../admin-api" }
aws-lc-rs = "1.17"
arrayref = { version = "0.3.7" }
base64 = "0.22.1"
blake3 = { version = "1.5.4" }
bytes = { version = "1.11.1" }
capnp = { workspace = true }
capnp-futures = { workspace = true, optional = true }
capnp-rpc = { workspace = true }
cbpf-rs = { workspace = true }
chrono = "0.4.39"
clap = { workspace = true, features = ["env"] }
clap_complete = { workspace = true, optional = true }
cslab = { git = "https://github.com/org-zpr/zpr-utils.git", tag = "cslab-v0.1.2" }
curve25519-dalek = "4.1.3"
dashmap = { version = "6.0.1" }
enum-map = { version = "2.7.3" }
enumset = "1.1.5"
hdrhistogram = { version = "7.5.4" }
internet-checksum = { workspace = true }
ipnet = { workspace = true }
itertools = "0.14"
libc = { version = "0.2.183" }
libnode = { package = "libnode2", path = "../../libnode2" }
nix = { version = "0.29.0", features = ["fs", "ioctl", "net", "poll", "uio"] }
open-enum = { version = "0.5.1" }
pkcs8 = "0.11"
rand = "0.9.3"
rcu = { git = "https://github.com/org-zpr/zpr-utils.git", tag = "rcu-v0.1.1", default-features = false }
replace_with = "0.1.8"
reqwest = { version = "0.13.1", features = ["json", "query"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.140"
snow = "0.10.0"
socket2 = { version = "0.5.7", features = ["all"] }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
toml = "0.9.11"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = "2.5.4"
zerocopy = { version = "0.8.3", features = ["derive", "std"] }
zpr = { workspace = true }
zpr-ext = { workspace = true, features = ["bytes", "tokio", "socket2", "zerocopy"] }
zpr-utils = { git = "https://github.com/org-zpr/zpr-utils.git", tag = "zpr-utils-v0.2.0"}
x509-cert = { version = "0.3.0", features = ["builder"] }
x509-parser = "0.18"
ed25519-dalek = { version = "3.0.0", features = ["pkcs8", "alloc"] }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { version = "0.7.4", optional = true }
tokio-tun = { version = "0.11.5" }

[dev-dependencies]
futures = "0.3.31"
serial_test = "3.2"
tokio = { workspace = true, features = ["test-util"] }

[features]
default = ["io-uring", "rcu-crossbeam-epoch"]
ci = []
rcu-aarc = ["rcu/rcu-aarc", "zpr/rcu-aarc"]
rcu-arc-swap = ["rcu/rcu-arc-swap", "zpr/rcu-arc-swap"]
rcu-crossbeam-epoch = ["rcu/rcu-crossbeam-epoch", "zpr/rcu-crossbeam-epoch"]
rcu-mutex-arc = ["rcu/rcu-mutex-arc", "zpr/rcu-mutex-arc"]
rcu-rwlock = ["rcu/rcu-rwlock", "zpr/rcu-rwlock"]
complete = ["clap_complete"]
capnp-ancillary = ["dep:capnp-futures", "capnp-futures/tokio-unix-fd-stream"]

[[bin]]
name = "ph"
path = "src/main.rs"

[[bin]]
name = "generate_completions"
path = "src/generate_completions.rs"
required-features = ["complete"]
