# Example node configuration file.


[creds]
ca_certificate = "ca-cert.pem"
rsa_certificate = "node-rsa-cert.pem"
rsa_private_key = "node-rsa-key.pem"

[dock]
enabled = true
listen_address = "0.0.0.0:5000"
noise_certificate = "node-noise-cert.pem"
noise_private_key = "<base64 encoded noise private key here>"


[claims]
"zpr.addr" = "fc00:3001:abd5::3836"
"x509.cn" = "node.zpr"


