use crate::assembly::Assembly;
use crate::km::*;
use crate::km_cert_exchange::KmCertExchange;
use crate::km_noise::{KmNoise, NoiseKeypair};
use crate::link_state::LinkEvent;
use crate::logging::targets::{KEY_MGMT, LINK_STATE};
use crate::mgmt::requests;
use crate::peer_table::KmHandle;
use bytes::Bytes;
use std::collections::HashMap;
use std::sync::Arc;
use tokio::{sync::mpsc, time};
use tokio_util::sync::CancellationToken;
use tracing::*;
use zpr;

/// How often the signal monitor worker checks the error conditions
/// on the KeyManager state machines.  Indirectly, this controls how
/// quickly the KeyManager state machines will restart the handshake
/// process in case of error.
const CHECK_ERROR_INTERVAL: time::Duration = time::Duration::from_millis(500);

#[derive(Debug)]
pub enum KmMsgProcessingError {
    LinkUnconfigured,
    EnqueueFailed,
}

#[allow(dead_code)]
#[derive(Debug)]
pub enum KmSetupError {
    InitializationError(KmError),
    LinkNotFound,
}

/// Global state for the KM system.
/// TODO: Move to assembly?
pub struct KmState {
    // `ctok` is the parent CancellationToken for the statemachines that are set running per link.
    // Cancelling this will shut down all the state machines.
    ctok: CancellationToken,
    km_tx: mpsc::Sender<KmLinkMsg<Bytes>>,
    km_sig_tx: mpsc::Sender<KmLinkMsg<KmSignal>>,
}

impl KmState {
    /// Create the Key Manager state.
    ///
    /// - `km_buffers_out` is for key management messages generated by the state machines. Each message
    ///   indicates its source link ID.
    /// - `km_sig_tx` is for signals generated by the state machines. Each signal indicates its source link ID.
    pub fn new(
        km_buffers_out: mpsc::Sender<KmLinkMsg<Bytes>>,
        km_sig_tx: mpsc::Sender<KmLinkMsg<KmSignal>>,
    ) -> Self {
        Self {
            ctok: CancellationToken::new(),
            km_tx: km_buffers_out,
            km_sig_tx,
        }
    }
}

#[derive(Debug, Clone)]
struct ErrorStatus {
    error_count: usize,          // if zero then no error
    last_error_t: time::Instant, // Last time error occurred
    restart_t: time::Instant,    // Last time we restarted the KM
}

/// Start the signal watcher worker.
///
/// This is one of the multiplexor related workers, the other one is in main.rs.
/// This watches for signals from the running KeyManagers and updates the SAState
/// when SA's are established.
///
/// TODO: Handle case when SAs are torn down.
pub async fn launch_signal_worker(
    asm: Arc<Assembly>,
    mut sig_queue: mpsc::Receiver<KmLinkMsg<KmSignal>>,
) {
    let sp_ctok = asm.km_state.ctok.clone();

    let mut status: HashMap<zpr::LinkId, ErrorStatus> = HashMap::new();
    let mut interval = time::interval(CHECK_ERROR_INTERVAL);

    loop {
        tokio::select! {
            _ = sp_ctok.cancelled() => {
                debug!(target: KEY_MGMT, "Multiplexor shutting down");
                break;
            }

            _ = interval.tick() => {
                let now = time::Instant::now();
                for (link_id, stat) in status.iter_mut() {
                    if stat.error_count > 0 && stat.last_error_t >= stat.restart_t && now - stat.last_error_t > time::Duration::from_secs(stat.error_count as u64) {
                        if let Some(km) = asm.peer_table.clone_km_manager(*link_id) {
                            match km.restart() {
                                Ok(_) => {
                                    debug!(target: KEY_MGMT, "multiplexor: restarted key manager on link {link_id} (error_count = {})", stat.error_count);
                                    stat.restart_t = now;
                                }
                                Err(e) => {
                                    error!(target: KEY_MGMT, "multiplexor: failed to restart KM on link {link_id}: {e:?}");
                                    stat.error_count += 1;
                                }
                            }
                        } else {
                            error!(target: KEY_MGMT, "multiplexor: unable to restart key manager on link {link_id}: not found in peer table");
                        }
                    }
                }
            }

            Some(linkmsg) = sig_queue.recv() => {
                debug!(target: KEY_MGMT, "multiplexor: link: {}, signal {:?}", linkmsg.link_id, linkmsg.msg);
                match linkmsg.msg {
                    KmSignal::SaIdChange { old, new } => {
                        debug!(target: KEY_MGMT, "multiplexor: SA ID change on link {}: {} -> {}", linkmsg.link_id, old, new);
                        if old == 0 {
                            let _ = status.remove(&linkmsg.link_id);
                        }
                    }
                    KmSignal::SaEstablished(sa) => {
                        debug!(target: KEY_MGMT, "multiplexor: link {}: SA established (SEND_ZPIS: {}, RECV_ZPIS: {}",
                            linkmsg.link_id, sa.send_zpis, sa.recv_zpis);
                        match asm.peer_table.set_security_association(linkmsg.link_id, sa) {
                            Ok(_) => (),
                            Err(e) => {
                                error!(target: KEY_MGMT, "multiplexor: failed to set SA established: {e:?}");
                            }
                        }
                        match asm.process_link_state_event(linkmsg.link_id, LinkEvent::KeyingDone) {
                            Err(e) => {
                                error!(target: LINK_STATE, "error: {e:?}");
                            }
                            Ok(_) => (),
                        }
                        match status.get_mut(&linkmsg.link_id) {
                            Some(s) if s.error_count == 0 => {
                                s.error_count = 0;
                            }
                            Some(_) => {}
                            None => (),
                        }
                    }
                    KmSignal::Reset => { }
                    KmSignal::Error => {
                        let stat = match status.get_mut(&linkmsg.link_id) {
                            Some(s) => s,
                            None => {
                                let ts = time::Instant::now();
                                let estat = ErrorStatus {
                                    error_count: 0,
                                    last_error_t: ts,
                                    restart_t: ts,
                                };
                                status.insert(linkmsg.link_id, estat);
                                status.get_mut(&linkmsg.link_id).unwrap()
                            }
                        };
                        stat.error_count += 1;
                        stat.last_error_t = time::Instant::now();
                        warn!(target: KEY_MGMT, "multiplexor: Error signal on link {}", linkmsg.link_id);
                    }
                    KmSignal::Termination => {
                        let _ = status.remove(&linkmsg.link_id);
                        debug!(target: KEY_MGMT, "multiplexor: termination signal on link {}", linkmsg.link_id);
                    }
                }
            }
        }
    }
}

/// Start the key management message worker.
///
/// Wait for key management messages generated by link key managemenet state machines,
/// dispatch them to an egress function.
pub async fn launch_message_worker(
    asm: Arc<Assembly>,
    mut msg_queue: mpsc::Receiver<KmLinkMsg<Bytes>>,
) {
    while let Some(km_buf_msg) = msg_queue.recv().await {
        requests::send_key_management(&*asm, km_buf_msg.link_id, zpr::KM_ID_NOISE, &km_buf_msg.msg);
    }
}

/// Creates a new KeyManager for the link from an adapter to a node and starts its state machine.  An adapter link will
/// initiate the KM exchange with its peer.
///
///
/// - `link_id` is the link to the peer, in this case better be a link to a node.
/// - `peer_noise_key` is the public noise key for the node/dock.
///
/// Note that the link must already have a peer_table entry.
pub fn add_adapter_link(
    asm: &Assembly,
    link_id: zpr::LinkId,
    recv_zpis: ZPIPair,
    local_noise_key: NoiseKeypair,
    peer_noise_key: [u8; 32],
    certx: KmCertExchange,
) -> Result<(), KmSetupError> {
    let noise = match KmNoise::new(
        true,
        Some(peer_noise_key.into()),
        Some(local_noise_key),
        recv_zpis,
        certx,
    ) {
        Ok(n) => n,
        Err(e) => {
            return Err(KmSetupError::InitializationError(e));
        }
    };
    add_noise_link(asm, link_id, noise)
}

/// Creates a new KeyManager for the link from a node to an adapter and starts its state machine.  A node link waits for a
/// KM initiator.
///
/// - `link_id` is the link to the peer, in this case better be a link to an adapter.
/// - `local_noise_key` is the local noise key for the dock (public part of this key must be shared out of band with adapters).
///
/// Note that the link must already have a peer_table entry.
pub fn add_node_link(
    asm: &Assembly,
    link_id: zpr::LinkId,
    recv_zpis: ZPIPair,
    local_noise_key: NoiseKeypair,
    certx: KmCertExchange,
) -> Result<(), KmSetupError> {
    let noise = match KmNoise::new(false, None, Some(local_noise_key), recv_zpis, certx) {
        Ok(n) => n,
        Err(e) => return Err(KmSetupError::InitializationError(e)),
    };
    add_noise_link(asm, link_id, noise)
}

/// Remove all state for this link, invalidating the SA and stopping the Key Manager.
pub async fn drop_link(asm: &Arc<Assembly>, link_id: zpr::LinkId) {
    // If present in state, turn off the SA.
    let _ = asm.peer_table.clear_security_association(link_id);

    // remove the SA and handle from our km state, stop the KM state machine
    if let Some(kmh) = asm.peer_table.remove_km_state(link_id) {
        kmh.ctok.cancel(); // stop the KM
        match kmh.join_handle.await {
            Ok(_) => (),
            Err(e) => {
                error!(target: KEY_MGMT, "statemachine shutdown join failed on link {link_id}: {e:?}");
            }
        }
    }
}

// Completes the add_*_link functions above.
fn add_noise_link(
    asm: &Assembly,
    link_id: zpr::LinkId,
    noise: KmNoise,
) -> Result<(), KmSetupError> {
    let mgr = KeyManager::new(link_id, Box::new(noise));

    // Link must already have a table entry
    assert!(
        asm.peer_table.get(link_id).is_some(),
        "link_id must be in peer_table before adding key management"
    );

    let mut spawn_mgr = mgr.clone();
    let child_ctok = asm.km_state.ctok.child_token();
    let spawn_ctok = child_ctok.clone();
    let spawn_km_tx = asm.km_state.km_tx.clone();
    let spawn_sig_tx = asm.km_state.km_sig_tx.clone();

    let (km_tx, km_rx) = mpsc::channel(asm.topology_config.km_link_queue_size);

    let sph = tokio::spawn(async move {
        match spawn_mgr
            .start(spawn_ctok, spawn_km_tx, spawn_sig_tx, km_rx)
            .await
        {
            Ok(_) => (),
            Err(e) => {
                error!(target: KEY_MGMT, "failed on link {link_id}: {e:?}");
            }
        }
    });

    let handle = KmHandle {
        join_handle: sph,
        ctok: child_ctok,
        mgr,
        km_tx,
    };

    asm.peer_table
        .set_km_handle(link_id, handle)
        .or(Err(KmSetupError::LinkNotFound))
}

/// When an inbound key management ZDP message arrives on a link, send it here after parsing.
///
/// The `km_payload` should be the km-payload part of the ZDP KM message.  We copy the payload before
/// returning.
///
/// Note that this will block if the KeyManager queue is full.
///
/// # Errors
///
/// - [KmMsgProcessingError::EnqueueFailed] if the message could not be enqueued on the state machine.
/// - [KmMsgProcessingError::LinkUnconfigured] if the link is not configured for Key Management.
///
pub fn handle_inbound_km_msg(
    asm: &Assembly,
    from_link: zpr::LinkId,
    km_payload: &[u8],
) -> Result<(), KmMsgProcessingError> {
    let tx = match asm.peer_table.clone_km_tx_chan(from_link) {
        Some(h) => h,
        None => return Err(KmMsgProcessingError::LinkUnconfigured),
    };
    let km_buf = Bytes::copy_from_slice(km_payload);
    match tx.try_send(km_buf) {
        Ok(_) => Ok(()),
        Err(_) => Err(KmMsgProcessingError::EnqueueFailed),
    }
}

#[cfg(test)]
mod test {
    use super::*;

    use crate::assembly::test::{create_assembly, TestAssemblyBuilder};
    use crate::km::KmLinkMsg;
    use crate::km_testdata::test::*;
    use crate::link_state::LinkType;
    use crate::mgmt_processor_worker;
    use crate::net_defs;
    use crate::peer_table;
    use base64::prelude::*;
    use std::net::{IpAddr, Ipv4Addr};
    use std::time::Duration;
    use tokio::task::{self, yield_now};
    use tokio::time::timeout;

    #[tokio::test]
    async fn test_km_multiplexor_updates_assembly_state() {
        let node_kp = NoiseKeypair::new(
            BASE64_STANDARD
                .decode(NODE_NOISE_KEY)
                .unwrap()
                .try_into()
                .unwrap(),
        );
        let adapter_kp = NoiseKeypair::new(
            BASE64_STANDARD
                .decode(ADAPTER_NOISE_KEY)
                .unwrap()
                .try_into()
                .unwrap(),
        );

        let adapter_exchanger =
            KmCertExchange::new_from_pem(ADAPTER_CERT_DATA, CA_CERT_DATA).unwrap();
        let node_exchanger = KmCertExchange::new_from_pem(NODE_CERT_DATA, CA_CERT_DATA).unwrap();

        let (km_sig_tx, km_sig_rx) = mpsc::channel(4);
        let (km_tx, mut km_rx) = mpsc::channel(4);
        let km_state = KmState::new(km_tx, km_sig_tx);

        let mut builder = TestAssemblyBuilder::new();
        builder.km_state = Some(km_state);

        let asm = Arc::new(create_assembly(builder));

        // Create this local "taskset" becuase adding an entry to the peer table ends up
        // calling `spawn_local`.  Not sure I need the whole rest of this unit test in here
        // but does appear to work.  Note that default tokio unit test runtime is
        // single-threaded.

        let local = task::LocalSet::new();
        local
            .run_until(async move {
                // add a fake adapter.
                let adapter_link_id: zpr::LinkId;
                {
                    let entry = asm.peer_table.vacant_entry().unwrap();

                    let worker_config = mgmt_processor_worker::Config {
                        link_id: entry.key(),
                    };

                    let fake_sa =
                        zpr::SubstrateAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 9000);

                    let fake_intf_addr = net_defs::ScopedIpAddr::V4(Ipv4Addr::new(127, 0, 0, 2));

                    let peer_state = peer_table::PeerState::new(
                        entry.key(),
                        LinkType::NodeToAdapter,
                        fake_sa,
                        fake_intf_addr,
                        |q| mgmt_processor_worker::launch(worker_config, asm.clone(), q),
                    );

                    adapter_link_id = entry.insert(peer_state).get();
                }

                // Adding a link starts a KM
                add_adapter_link(
                    &asm,
                    adapter_link_id,
                    ZPIPair::new(1, 2),
                    adapter_kp,
                    node_kp.public.clone(),
                    adapter_exchanger,
                )
                .unwrap();

                yield_now().await;

                // Start our multiplexor worker
                tokio::spawn(launch_signal_worker(asm.clone(), km_sig_rx));
                yield_now().await;

                // An adapter should send a KM message over link 1.
                let handshake_req: Bytes;
                match timeout(Duration::from_secs(2), km_rx.recv()).await {
                    Ok(resp) => match resp {
                        Some(KmLinkMsg { link_id, msg }) => {
                            assert_eq!(link_id, adapter_link_id);
                            assert_eq!(msg.len(), 913); // should be a KM payload
                            handshake_req = msg;
                        }
                        None => panic!("Expected KMLinkMessage message"),
                    },
                    Err(_) => panic!("Timed out waiting for KM message"),
                }

                // Check that initially, our state is not established.
                {
                    assert!(!asm
                        .peer_table
                        .is_security_association_established(adapter_link_id))
                }

                // Pretend to be a node and send back a valid reply.
                let mut responder = KmNoise::new(
                    false,
                    None,
                    Some(node_kp),
                    ZPIPair::new(3, 4),
                    node_exchanger,
                )
                .unwrap();
                match responder.reset() {
                    Ok(Some(_m)) => panic!("unexpected message from responder.reset!"),
                    Ok(None) => {} // good
                    Err(e) => {
                        panic!("error resetting responder: {:?}", e);
                    }
                };

                // Since we have a "raw" responder, we can just pass the payload (no ZDP headers have been added).
                let handshake_reply = match responder.handle_message(&handshake_req) {
                    Ok(Some(m)) => m,
                    Ok(None) => {
                        panic!("expected handshake-1 message, got nothing!");
                    }
                    Err(e) => {
                        panic!("responder handle_message failed on handshake-req: {:?}", e);
                    }
                };

                // Now send the reply back into our link.
                handle_inbound_km_msg(&asm, adapter_link_id, &handshake_reply).unwrap();

                yield_now().await;

                // The KM on the link will process the message and transition to established-state.
                // It will send two signals - SaIdChange followed by SaEstablished.  Both signals
                // are picked up by our multiplexor worker.  The second one triggers a state update.
                {
                    assert!(asm
                        .peer_table
                        .is_security_association_established(adapter_link_id))
                }

                drop_link(&asm, adapter_link_id).await;
            })
            .await;
    }
}
