// Code generated by Thrift Compiler (0.20.0). DO NOT EDIT.

package vsapi

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"log/slog"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type StatusCode int64
const (
  StatusCode_SUCCESS StatusCode = 0
  StatusCode_FAIL StatusCode = 1
)

func (p StatusCode) String() string {
  switch p {
  case StatusCode_SUCCESS: return "SUCCESS"
  case StatusCode_FAIL: return "FAIL"
  }
  return "<UNSET>"
}

func StatusCodeFromString(s string) (StatusCode, error) {
  switch s {
  case "SUCCESS": return StatusCode_SUCCESS, nil 
  case "FAIL": return StatusCode_FAIL, nil 
  }
  return StatusCode(0), fmt.Errorf("not a valid StatusCode string")
}


func StatusCodePtr(v StatusCode) *StatusCode { return &v }

func (p StatusCode) MarshalText() ([]byte, error) {
return []byte(p.String()), nil
}

func (p *StatusCode) UnmarshalText(text []byte) error {
q, err := StatusCodeFromString(string(text))
if (err != nil) {
return err
}
*p = q
return nil
}

func (p *StatusCode) Scan(value interface{}) error {
v, ok := value.(int64)
if !ok {
return errors.New("Scan value is not int64")
}
*p = StatusCode(v)
return nil
}

func (p * StatusCode) Value() (driver.Value, error) {
  if p == nil {
    return nil, nil
  }
return int64(*p), nil
}
type AgentType int64
const (
  AgentType_ADAPTER AgentType = 0
  AgentType_NODE AgentType = 1
)

func (p AgentType) String() string {
  switch p {
  case AgentType_ADAPTER: return "ADAPTER"
  case AgentType_NODE: return "NODE"
  }
  return "<UNSET>"
}

func AgentTypeFromString(s string) (AgentType, error) {
  switch s {
  case "ADAPTER": return AgentType_ADAPTER, nil 
  case "NODE": return AgentType_NODE, nil 
  }
  return AgentType(0), fmt.Errorf("not a valid AgentType string")
}


func AgentTypePtr(v AgentType) *AgentType { return &v }

func (p AgentType) MarshalText() ([]byte, error) {
return []byte(p.String()), nil
}

func (p *AgentType) UnmarshalText(text []byte) error {
q, err := AgentTypeFromString(string(text))
if (err != nil) {
return err
}
*p = q
return nil
}

func (p *AgentType) Scan(value interface{}) error {
v, ok := value.(int64)
if !ok {
return errors.New("Scan value is not int64")
}
*p = AgentType(v)
return nil
}

func (p * AgentType) Value() (driver.Value, error) {
  if p == nil {
    return nil, nil
  }
return int64(*p), nil
}
type APIKey string

func APIKeyPtr(v APIKey) *APIKey { return &v }

// Attributes:
//  - AgentType
//  - Attrs
//  - AuthExpires
//  - ZprAddr
//  - TetherAddr
//  - Ident
//  - Provides
type Agent struct {
  AgentType AgentType `thrift:"agent_type,1" db:"agent_type" json:"agent_type"`
  Attrs map[string]string `thrift:"attrs,2" db:"attrs" json:"attrs"`
  AuthExpires int64 `thrift:"auth_expires,3" db:"auth_expires" json:"auth_expires"`
  ZprAddr []byte `thrift:"zpr_addr,4" db:"zpr_addr" json:"zpr_addr"`
  TetherAddr []byte `thrift:"tether_addr,5" db:"tether_addr" json:"tether_addr"`
  Ident string `thrift:"ident,6" db:"ident" json:"ident"`
  Provides []string `thrift:"provides,7" db:"provides" json:"provides"`
}

func NewAgent() *Agent {
  return &Agent{}
}


func (p *Agent) GetAgentType() AgentType {
  return p.AgentType
}

func (p *Agent) GetAttrs() map[string]string {
  return p.Attrs
}

func (p *Agent) GetAuthExpires() int64 {
  return p.AuthExpires
}

func (p *Agent) GetZprAddr() []byte {
  return p.ZprAddr
}

func (p *Agent) GetTetherAddr() []byte {
  return p.TetherAddr
}

func (p *Agent) GetIdent() string {
  return p.Ident
}

func (p *Agent) GetProvides() []string {
  return p.Provides
}
func (p *Agent) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.MAP {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField3(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField4(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 5:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField5(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 6:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField6(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 7:
      if fieldTypeId == thrift.LIST {
        if err := p.ReadField7(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *Agent)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  temp := AgentType(v)
  p.AgentType = temp
}
  return nil
}

func (p *Agent)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  _, _, size, err := iprot.ReadMapBegin(ctx)
  if err != nil {
    return thrift.PrependError("error reading map begin: ", err)
  }
  tMap := make(map[string]string, size)
  p.Attrs =  tMap
  for i := 0; i < size; i ++ {
var _key0 string
    if v, err := iprot.ReadString(ctx); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _key0 = v
}
var _val1 string
    if v, err := iprot.ReadString(ctx); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _val1 = v
}
    p.Attrs[_key0] = _val1
  }
  if err := iprot.ReadMapEnd(ctx); err != nil {
    return thrift.PrependError("error reading map end: ", err)
  }
  return nil
}

func (p *Agent)  ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(ctx); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.AuthExpires = v
}
  return nil
}

func (p *Agent)  ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.ZprAddr = v
}
  return nil
}

func (p *Agent)  ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 5: ", err)
} else {
  p.TetherAddr = v
}
  return nil
}

func (p *Agent)  ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 6: ", err)
} else {
  p.Ident = v
}
  return nil
}

func (p *Agent)  ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
  _, size, err := iprot.ReadListBegin(ctx)
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]string, 0, size)
  p.Provides =  tSlice
  for i := 0; i < size; i ++ {
var _elem2 string
    if v, err := iprot.ReadString(ctx); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _elem2 = v
}
    p.Provides = append(p.Provides, _elem2)
  }
  if err := iprot.ReadListEnd(ctx); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *Agent) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "Agent"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField3(ctx, oprot); err != nil { return err }
    if err := p.writeField4(ctx, oprot); err != nil { return err }
    if err := p.writeField5(ctx, oprot); err != nil { return err }
    if err := p.writeField6(ctx, oprot); err != nil { return err }
    if err := p.writeField7(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *Agent) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "agent_type", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:agent_type: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.AgentType)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.agent_type (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:agent_type: ", p), err) }
  return err
}

func (p *Agent) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "attrs", thrift.MAP, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:attrs: ", p), err) }
  if err := oprot.WriteMapBegin(ctx, thrift.STRING, thrift.STRING, len(p.Attrs)); err != nil {
    return thrift.PrependError("error writing map begin: ", err)
  }
  for k, v := range p.Attrs {
    if err := oprot.WriteString(ctx, string(k)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    if err := oprot.WriteString(ctx, string(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteMapEnd(ctx); err != nil {
    return thrift.PrependError("error writing map end: ", err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:attrs: ", p), err) }
  return err
}

func (p *Agent) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "auth_expires", thrift.I64, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:auth_expires: ", p), err) }
  if err := oprot.WriteI64(ctx, int64(p.AuthExpires)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.auth_expires (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:auth_expires: ", p), err) }
  return err
}

func (p *Agent) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "zpr_addr", thrift.STRING, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:zpr_addr: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.ZprAddr); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.zpr_addr (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:zpr_addr: ", p), err) }
  return err
}

func (p *Agent) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "tether_addr", thrift.STRING, 5); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:tether_addr: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.TetherAddr); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.tether_addr (5) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 5:tether_addr: ", p), err) }
  return err
}

func (p *Agent) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "ident", thrift.STRING, 6); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:ident: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.Ident)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.ident (6) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 6:ident: ", p), err) }
  return err
}

func (p *Agent) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "provides", thrift.LIST, 7); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:provides: ", p), err) }
  if err := oprot.WriteListBegin(ctx, thrift.STRING, len(p.Provides)); err != nil {
    return thrift.PrependError("error writing list begin: ", err)
  }
  for _, v := range p.Provides {
    if err := oprot.WriteString(ctx, string(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteListEnd(ctx); err != nil {
    return thrift.PrependError("error writing list end: ", err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 7:provides: ", p), err) }
  return err
}

func (p *Agent) Equals(other *Agent) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.AgentType != other.AgentType { return false }
  if len(p.Attrs) != len(other.Attrs) { return false }
  for k, _tgt := range p.Attrs {
    _src3 := other.Attrs[k]
    if _tgt != _src3 { return false }
  }
  if p.AuthExpires != other.AuthExpires { return false }
  if bytes.Compare(p.ZprAddr, other.ZprAddr) != 0 { return false }
  if bytes.Compare(p.TetherAddr, other.TetherAddr) != 0 { return false }
  if p.Ident != other.Ident { return false }
  if len(p.Provides) != len(other.Provides) { return false }
  for i, _tgt := range p.Provides {
    _src4 := other.Provides[i]
    if _tgt != _src4 { return false }
  }
  return true
}

func (p *Agent) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("Agent(%+v)", *p)
}

func (p *Agent) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.Agent",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*Agent)(nil)

func (p *Agent) Validate() error {
  return nil
}
// Attributes:
//  - ChallengeType
//  - ChallengeData
type Challenge struct {
  ChallengeType int32 `thrift:"challenge_type,1" db:"challenge_type" json:"challenge_type"`
  ChallengeData []byte `thrift:"challenge_data,2" db:"challenge_data" json:"challenge_data"`
}

func NewChallenge() *Challenge {
  return &Challenge{}
}


func (p *Challenge) GetChallengeType() int32 {
  return p.ChallengeType
}

func (p *Challenge) GetChallengeData() []byte {
  return p.ChallengeData
}
func (p *Challenge) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *Challenge)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.ChallengeType = v
}
  return nil
}

func (p *Challenge)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.ChallengeData = v
}
  return nil
}

func (p *Challenge) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "Challenge"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *Challenge) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "challenge_type", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:challenge_type: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.ChallengeType)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.challenge_type (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:challenge_type: ", p), err) }
  return err
}

func (p *Challenge) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "challenge_data", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:challenge_data: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.ChallengeData); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.challenge_data (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:challenge_data: ", p), err) }
  return err
}

func (p *Challenge) Equals(other *Challenge) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.ChallengeType != other.ChallengeType { return false }
  if bytes.Compare(p.ChallengeData, other.ChallengeData) != 0 { return false }
  return true
}

func (p *Challenge) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("Challenge(%+v)", *p)
}

func (p *Challenge) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.Challenge",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*Challenge)(nil)

func (p *Challenge) Validate() error {
  return nil
}
// Attributes:
//  - ChallengeType
//  - ResponseType
//  - ResponseData
type ChallengeResponse struct {
  ChallengeType int32 `thrift:"challenge_type,1" db:"challenge_type" json:"challenge_type"`
  ResponseType int32 `thrift:"response_type,2" db:"response_type" json:"response_type"`
  ResponseData []byte `thrift:"response_data,3" db:"response_data" json:"response_data"`
}

func NewChallengeResponse() *ChallengeResponse {
  return &ChallengeResponse{}
}


func (p *ChallengeResponse) GetChallengeType() int32 {
  return p.ChallengeType
}

func (p *ChallengeResponse) GetResponseType() int32 {
  return p.ResponseType
}

func (p *ChallengeResponse) GetResponseData() []byte {
  return p.ResponseData
}
func (p *ChallengeResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField3(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ChallengeResponse)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.ChallengeType = v
}
  return nil
}

func (p *ChallengeResponse)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.ResponseType = v
}
  return nil
}

func (p *ChallengeResponse)  ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.ResponseData = v
}
  return nil
}

func (p *ChallengeResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "ChallengeResponse"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField3(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ChallengeResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "challenge_type", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:challenge_type: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.ChallengeType)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.challenge_type (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:challenge_type: ", p), err) }
  return err
}

func (p *ChallengeResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "response_type", thrift.I32, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:response_type: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.ResponseType)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.response_type (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:response_type: ", p), err) }
  return err
}

func (p *ChallengeResponse) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "response_data", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:response_data: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.ResponseData); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.response_data (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:response_data: ", p), err) }
  return err
}

func (p *ChallengeResponse) Equals(other *ChallengeResponse) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.ChallengeType != other.ChallengeType { return false }
  if p.ResponseType != other.ResponseType { return false }
  if bytes.Compare(p.ResponseData, other.ResponseData) != 0 { return false }
  return true
}

func (p *ChallengeResponse) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ChallengeResponse(%+v)", *p)
}

func (p *ChallengeResponse) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.ChallengeResponse",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ChallengeResponse)(nil)

func (p *ChallengeResponse) Validate() error {
  return nil
}
// Attributes:
//  - ConnectionID
//  - DockAddr
//  - Claims
//  - Challenge
//  - ChallengeResponse
type ConnectRequest struct {
  ConnectionID int32 `thrift:"connection_id,1" db:"connection_id" json:"connection_id"`
  DockAddr []byte `thrift:"dock_addr,2" db:"dock_addr" json:"dock_addr"`
  Claims map[string]string `thrift:"claims,3" db:"claims" json:"claims"`
  Challenge []byte `thrift:"challenge,4" db:"challenge" json:"challenge"`
  ChallengeResponse []byte `thrift:"challenge_response,5" db:"challenge_response" json:"challenge_response"`
}

func NewConnectRequest() *ConnectRequest {
  return &ConnectRequest{}
}


func (p *ConnectRequest) GetConnectionID() int32 {
  return p.ConnectionID
}

func (p *ConnectRequest) GetDockAddr() []byte {
  return p.DockAddr
}

func (p *ConnectRequest) GetClaims() map[string]string {
  return p.Claims
}

func (p *ConnectRequest) GetChallenge() []byte {
  return p.Challenge
}

func (p *ConnectRequest) GetChallengeResponse() []byte {
  return p.ChallengeResponse
}
func (p *ConnectRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.MAP {
        if err := p.ReadField3(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField4(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 5:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField5(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ConnectRequest)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.ConnectionID = v
}
  return nil
}

func (p *ConnectRequest)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.DockAddr = v
}
  return nil
}

func (p *ConnectRequest)  ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
  _, _, size, err := iprot.ReadMapBegin(ctx)
  if err != nil {
    return thrift.PrependError("error reading map begin: ", err)
  }
  tMap := make(map[string]string, size)
  p.Claims =  tMap
  for i := 0; i < size; i ++ {
var _key5 string
    if v, err := iprot.ReadString(ctx); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _key5 = v
}
var _val6 string
    if v, err := iprot.ReadString(ctx); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _val6 = v
}
    p.Claims[_key5] = _val6
  }
  if err := iprot.ReadMapEnd(ctx); err != nil {
    return thrift.PrependError("error reading map end: ", err)
  }
  return nil
}

func (p *ConnectRequest)  ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.Challenge = v
}
  return nil
}

func (p *ConnectRequest)  ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 5: ", err)
} else {
  p.ChallengeResponse = v
}
  return nil
}

func (p *ConnectRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "ConnectRequest"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField3(ctx, oprot); err != nil { return err }
    if err := p.writeField4(ctx, oprot); err != nil { return err }
    if err := p.writeField5(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ConnectRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "connection_id", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:connection_id: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.ConnectionID)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.connection_id (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:connection_id: ", p), err) }
  return err
}

func (p *ConnectRequest) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "dock_addr", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:dock_addr: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.DockAddr); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.dock_addr (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:dock_addr: ", p), err) }
  return err
}

func (p *ConnectRequest) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "claims", thrift.MAP, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:claims: ", p), err) }
  if err := oprot.WriteMapBegin(ctx, thrift.STRING, thrift.STRING, len(p.Claims)); err != nil {
    return thrift.PrependError("error writing map begin: ", err)
  }
  for k, v := range p.Claims {
    if err := oprot.WriteString(ctx, string(k)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    if err := oprot.WriteString(ctx, string(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteMapEnd(ctx); err != nil {
    return thrift.PrependError("error writing map end: ", err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:claims: ", p), err) }
  return err
}

func (p *ConnectRequest) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "challenge", thrift.STRING, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:challenge: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.Challenge); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.challenge (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:challenge: ", p), err) }
  return err
}

func (p *ConnectRequest) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "challenge_response", thrift.STRING, 5); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:challenge_response: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.ChallengeResponse); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.challenge_response (5) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 5:challenge_response: ", p), err) }
  return err
}

func (p *ConnectRequest) Equals(other *ConnectRequest) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.ConnectionID != other.ConnectionID { return false }
  if bytes.Compare(p.DockAddr, other.DockAddr) != 0 { return false }
  if len(p.Claims) != len(other.Claims) { return false }
  for k, _tgt := range p.Claims {
    _src7 := other.Claims[k]
    if _tgt != _src7 { return false }
  }
  if bytes.Compare(p.Challenge, other.Challenge) != 0 { return false }
  if bytes.Compare(p.ChallengeResponse, other.ChallengeResponse) != 0 { return false }
  return true
}

func (p *ConnectRequest) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ConnectRequest(%+v)", *p)
}

func (p *ConnectRequest) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.ConnectRequest",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ConnectRequest)(nil)

func (p *ConnectRequest) Validate() error {
  return nil
}
// Attributes:
//  - ConnectionID
//  - Status
//  - Agent
//  - Reason
type ConnectResponse struct {
  ConnectionID int32 `thrift:"connection_id,1" db:"connection_id" json:"connection_id"`
  Status StatusCode `thrift:"status,2" db:"status" json:"status"`
  Agent *Agent `thrift:"agent,3" db:"agent" json:"agent,omitempty"`
  Reason *string `thrift:"reason,4" db:"reason" json:"reason,omitempty"`
}

func NewConnectResponse() *ConnectResponse {
  return &ConnectResponse{}
}


func (p *ConnectResponse) GetConnectionID() int32 {
  return p.ConnectionID
}

func (p *ConnectResponse) GetStatus() StatusCode {
  return p.Status
}
var ConnectResponse_Agent_DEFAULT *Agent
func (p *ConnectResponse) GetAgent() *Agent {
  if !p.IsSetAgent() {
    return ConnectResponse_Agent_DEFAULT
  }
  return p.Agent
}
var ConnectResponse_Reason_DEFAULT string
func (p *ConnectResponse) GetReason() string {
  if !p.IsSetReason() {
    return ConnectResponse_Reason_DEFAULT
  }
  return *p.Reason
}
func (p *ConnectResponse) IsSetAgent() bool {
  return p.Agent != nil
}

func (p *ConnectResponse) IsSetReason() bool {
  return p.Reason != nil
}

func (p *ConnectResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField3(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField4(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ConnectResponse)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.ConnectionID = v
}
  return nil
}

func (p *ConnectResponse)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  temp := StatusCode(v)
  p.Status = temp
}
  return nil
}

func (p *ConnectResponse)  ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
  p.Agent = &Agent{}
  if err := p.Agent.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Agent), err)
  }
  return nil
}

func (p *ConnectResponse)  ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.Reason = &v
}
  return nil
}

func (p *ConnectResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "ConnectResponse"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField3(ctx, oprot); err != nil { return err }
    if err := p.writeField4(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ConnectResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "connection_id", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:connection_id: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.ConnectionID)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.connection_id (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:connection_id: ", p), err) }
  return err
}

func (p *ConnectResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "status", thrift.I32, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:status: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.Status)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.status (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:status: ", p), err) }
  return err
}

func (p *ConnectResponse) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetAgent() {
    if err := oprot.WriteFieldBegin(ctx, "agent", thrift.STRUCT, 3); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:agent: ", p), err) }
    if err := p.Agent.Write(ctx, oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Agent), err)
    }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 3:agent: ", p), err) }
  }
  return err
}

func (p *ConnectResponse) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetReason() {
    if err := oprot.WriteFieldBegin(ctx, "reason", thrift.STRING, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:reason: ", p), err) }
    if err := oprot.WriteString(ctx, string(*p.Reason)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.reason (4) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:reason: ", p), err) }
  }
  return err
}

func (p *ConnectResponse) Equals(other *ConnectResponse) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.ConnectionID != other.ConnectionID { return false }
  if p.Status != other.Status { return false }
  if !p.Agent.Equals(other.Agent) { return false }
  if p.Reason != other.Reason {
    if p.Reason == nil || other.Reason == nil {
      return false
    }
    if (*p.Reason) != (*other.Reason) { return false }
  }
  return true
}

func (p *ConnectResponse) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ConnectResponse(%+v)", *p)
}

func (p *ConnectResponse) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.ConnectResponse",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ConnectResponse)(nil)

func (p *ConnectResponse) Validate() error {
  return nil
}
// Attributes:
//  - SessionID
//  - Nonce
type VSChallenge struct {
  SessionID int64 `thrift:"session_id,1" db:"session_id" json:"session_id"`
  Nonce []byte `thrift:"nonce,2" db:"nonce" json:"nonce"`
}

func NewVSChallenge() *VSChallenge {
  return &VSChallenge{}
}


func (p *VSChallenge) GetSessionID() int64 {
  return p.SessionID
}

func (p *VSChallenge) GetNonce() []byte {
  return p.Nonce
}
func (p *VSChallenge) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *VSChallenge)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.SessionID = v
}
  return nil
}

func (p *VSChallenge)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Nonce = v
}
  return nil
}

func (p *VSChallenge) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "VSChallenge"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VSChallenge) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "session_id", thrift.I64, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:session_id: ", p), err) }
  if err := oprot.WriteI64(ctx, int64(p.SessionID)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.session_id (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:session_id: ", p), err) }
  return err
}

func (p *VSChallenge) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "nonce", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:nonce: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.Nonce); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.nonce (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:nonce: ", p), err) }
  return err
}

func (p *VSChallenge) Equals(other *VSChallenge) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.SessionID != other.SessionID { return false }
  if bytes.Compare(p.Nonce, other.Nonce) != 0 { return false }
  return true
}

func (p *VSChallenge) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VSChallenge(%+v)", *p)
}

func (p *VSChallenge) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.VSChallenge",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VSChallenge)(nil)

func (p *VSChallenge) Validate() error {
  return nil
}
type VisaService interface {
  Hello(ctx context.Context) (_r *VSChallenge, _err error)
  // Parameters:
  //  - Challenge
  //  - Timestamp
  //  - NodeCert
  //  - Hmac
  //  - NodeAgent
  Authenticate(ctx context.Context, challenge *VSChallenge, timestamp int64, node_cert []byte, hmac []byte, node_agent *Agent) (_r APIKey, _err error)
  // Parameters:
  //  - Key
  DeRegister(ctx context.Context, key APIKey) (_err error)
  // Parameters:
  //  - Key
  //  - Request
  AuthorizeConnect(ctx context.Context, key APIKey, request *ConnectRequest) (_r *ConnectResponse, _err error)
}

type VisaServiceClient struct {
  c thrift.TClient
  meta thrift.ResponseMeta
}

func NewVisaServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *VisaServiceClient {
  return &VisaServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewVisaServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *VisaServiceClient {
  return &VisaServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewVisaServiceClient(c thrift.TClient) *VisaServiceClient {
  return &VisaServiceClient{
    c: c,
  }
}

func (p *VisaServiceClient) Client_() thrift.TClient {
  return p.c
}

func (p *VisaServiceClient) LastResponseMeta_() thrift.ResponseMeta {
  return p.meta
}

func (p *VisaServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
  p.meta = meta
}

func (p *VisaServiceClient) Hello(ctx context.Context) (_r *VSChallenge, _err error) {
  var _args8 VisaServiceHelloArgs
  var _result10 VisaServiceHelloResult
  var _meta9 thrift.ResponseMeta
  _meta9, _err = p.Client_().Call(ctx, "hello", &_args8, &_result10)
  p.SetLastResponseMeta_(_meta9)
  if _err != nil {
    return
  }
  if _ret11 := _result10.GetSuccess(); _ret11 != nil {
    return _ret11, nil
  }
  return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "hello failed: unknown result")
}

// Parameters:
//  - Challenge
//  - Timestamp
//  - NodeCert
//  - Hmac
//  - NodeAgent
func (p *VisaServiceClient) Authenticate(ctx context.Context, challenge *VSChallenge, timestamp int64, node_cert []byte, hmac []byte, node_agent *Agent) (_r APIKey, _err error) {
  var _args12 VisaServiceAuthenticateArgs
  _args12.Challenge = challenge
  _args12.Timestamp = timestamp
  _args12.NodeCert = node_cert
  _args12.Hmac = hmac
  _args12.NodeAgent = node_agent
  var _result14 VisaServiceAuthenticateResult
  var _meta13 thrift.ResponseMeta
  _meta13, _err = p.Client_().Call(ctx, "authenticate", &_args12, &_result14)
  p.SetLastResponseMeta_(_meta13)
  if _err != nil {
    return
  }
  return _result14.GetSuccess(), nil
}

// Parameters:
//  - Key
func (p *VisaServiceClient) DeRegister(ctx context.Context, key APIKey) (_err error) {
  var _args15 VisaServiceDeRegisterArgs
  _args15.Key = key
  p.SetLastResponseMeta_(thrift.ResponseMeta{})
  if _, err := p.Client_().Call(ctx, "de_register", &_args15, nil); err != nil {
    return err
  }
  return nil
}

// Parameters:
//  - Key
//  - Request
func (p *VisaServiceClient) AuthorizeConnect(ctx context.Context, key APIKey, request *ConnectRequest) (_r *ConnectResponse, _err error) {
  var _args16 VisaServiceAuthorizeConnectArgs
  _args16.Key = key
  _args16.Request = request
  var _result18 VisaServiceAuthorizeConnectResult
  var _meta17 thrift.ResponseMeta
  _meta17, _err = p.Client_().Call(ctx, "authorize_connect", &_args16, &_result18)
  p.SetLastResponseMeta_(_meta17)
  if _err != nil {
    return
  }
  if _ret19 := _result18.GetSuccess(); _ret19 != nil {
    return _ret19, nil
  }
  return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "authorize_connect failed: unknown result")
}

type VisaServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler VisaService
}

func (p *VisaServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *VisaServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *VisaServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewVisaServiceProcessor(handler VisaService) *VisaServiceProcessor {

  self20 := &VisaServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self20.processorMap["hello"] = &visaServiceProcessorHello{handler:handler}
  self20.processorMap["authenticate"] = &visaServiceProcessorAuthenticate{handler:handler}
  self20.processorMap["de_register"] = &visaServiceProcessorDeRegister{handler:handler}
  self20.processorMap["authorize_connect"] = &visaServiceProcessorAuthorizeConnect{handler:handler}
return self20
}

func (p *VisaServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
  if err2 != nil { return false, thrift.WrapTException(err2) }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(ctx, thrift.STRUCT)
  iprot.ReadMessageEnd(ctx)
  x21 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
  x21.Write(ctx, oprot)
  oprot.WriteMessageEnd(ctx)
  oprot.Flush(ctx)
  return false, x21

}

type visaServiceProcessorHello struct {
  handler VisaService
}

func (p *visaServiceProcessorHello) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  var _write_err22 error
  args := VisaServiceHelloArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "hello", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelCauseFunc
    ctx, cancel = context.WithCancelCause(ctx)
    defer cancel(nil)
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelCauseFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel(thrift.ErrAbandonRequest)
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := VisaServiceHelloResult{}
  if retval, err2 := p.handler.Hello(ctx); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
    if errors.Is(err2, thrift.ErrAbandonRequest) {
      return false, thrift.WrapTException(err2)
    }
    if errors.Is(err2, context.Canceled) {
      if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
        return false, thrift.WrapTException(err)
      }
    }
    _exc23 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing hello: " + err2.Error())
    if err2 := oprot.WriteMessageBegin(ctx, "hello", thrift.EXCEPTION, seqId); err2 != nil {
      _write_err22 = thrift.WrapTException(err2)
    }
    if err2 := _exc23.Write(ctx, oprot); _write_err22 == nil && err2 != nil {
      _write_err22 = thrift.WrapTException(err2)
    }
    if err2 := oprot.WriteMessageEnd(ctx); _write_err22 == nil && err2 != nil {
      _write_err22 = thrift.WrapTException(err2)
    }
    if err2 := oprot.Flush(ctx); _write_err22 == nil && err2 != nil {
      _write_err22 = thrift.WrapTException(err2)
    }
    if _write_err22 != nil {
      return false, thrift.WrapTException(_write_err22)
    }
    return true, err
  } else {
    result.Success = retval
  }
  tickerCancel()
  if err2 := oprot.WriteMessageBegin(ctx, "hello", thrift.REPLY, seqId); err2 != nil {
    _write_err22 = thrift.WrapTException(err2)
  }
  if err2 := result.Write(ctx, oprot); _write_err22 == nil && err2 != nil {
    _write_err22 = thrift.WrapTException(err2)
  }
  if err2 := oprot.WriteMessageEnd(ctx); _write_err22 == nil && err2 != nil {
    _write_err22 = thrift.WrapTException(err2)
  }
  if err2 := oprot.Flush(ctx); _write_err22 == nil && err2 != nil {
    _write_err22 = thrift.WrapTException(err2)
  }
  if _write_err22 != nil {
    return false, thrift.WrapTException(_write_err22)
  }
  return true, err
}

type visaServiceProcessorAuthenticate struct {
  handler VisaService
}

func (p *visaServiceProcessorAuthenticate) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  var _write_err24 error
  args := VisaServiceAuthenticateArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "authenticate", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelCauseFunc
    ctx, cancel = context.WithCancelCause(ctx)
    defer cancel(nil)
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelCauseFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel(thrift.ErrAbandonRequest)
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := VisaServiceAuthenticateResult{}
  if retval, err2 := p.handler.Authenticate(ctx, args.Challenge, args.Timestamp, args.NodeCert, args.Hmac, args.NodeAgent); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
    if errors.Is(err2, thrift.ErrAbandonRequest) {
      return false, thrift.WrapTException(err2)
    }
    if errors.Is(err2, context.Canceled) {
      if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
        return false, thrift.WrapTException(err)
      }
    }
    _exc25 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing authenticate: " + err2.Error())
    if err2 := oprot.WriteMessageBegin(ctx, "authenticate", thrift.EXCEPTION, seqId); err2 != nil {
      _write_err24 = thrift.WrapTException(err2)
    }
    if err2 := _exc25.Write(ctx, oprot); _write_err24 == nil && err2 != nil {
      _write_err24 = thrift.WrapTException(err2)
    }
    if err2 := oprot.WriteMessageEnd(ctx); _write_err24 == nil && err2 != nil {
      _write_err24 = thrift.WrapTException(err2)
    }
    if err2 := oprot.Flush(ctx); _write_err24 == nil && err2 != nil {
      _write_err24 = thrift.WrapTException(err2)
    }
    if _write_err24 != nil {
      return false, thrift.WrapTException(_write_err24)
    }
    return true, err
  } else {
    result.Success = &retval
  }
  tickerCancel()
  if err2 := oprot.WriteMessageBegin(ctx, "authenticate", thrift.REPLY, seqId); err2 != nil {
    _write_err24 = thrift.WrapTException(err2)
  }
  if err2 := result.Write(ctx, oprot); _write_err24 == nil && err2 != nil {
    _write_err24 = thrift.WrapTException(err2)
  }
  if err2 := oprot.WriteMessageEnd(ctx); _write_err24 == nil && err2 != nil {
    _write_err24 = thrift.WrapTException(err2)
  }
  if err2 := oprot.Flush(ctx); _write_err24 == nil && err2 != nil {
    _write_err24 = thrift.WrapTException(err2)
  }
  if _write_err24 != nil {
    return false, thrift.WrapTException(_write_err24)
  }
  return true, err
}

type visaServiceProcessorDeRegister struct {
  handler VisaService
}

func (p *visaServiceProcessorDeRegister) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := VisaServiceDeRegisterArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  _ = tickerCancel

  if err2 := p.handler.DeRegister(ctx, args.Key); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
  }
  tickerCancel()
  return true, err
}

type visaServiceProcessorAuthorizeConnect struct {
  handler VisaService
}

func (p *visaServiceProcessorAuthorizeConnect) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  var _write_err26 error
  args := VisaServiceAuthorizeConnectArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "authorize_connect", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelCauseFunc
    ctx, cancel = context.WithCancelCause(ctx)
    defer cancel(nil)
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelCauseFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel(thrift.ErrAbandonRequest)
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := VisaServiceAuthorizeConnectResult{}
  if retval, err2 := p.handler.AuthorizeConnect(ctx, args.Key, args.Request); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
    if errors.Is(err2, thrift.ErrAbandonRequest) {
      return false, thrift.WrapTException(err2)
    }
    if errors.Is(err2, context.Canceled) {
      if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
        return false, thrift.WrapTException(err)
      }
    }
    _exc27 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing authorize_connect: " + err2.Error())
    if err2 := oprot.WriteMessageBegin(ctx, "authorize_connect", thrift.EXCEPTION, seqId); err2 != nil {
      _write_err26 = thrift.WrapTException(err2)
    }
    if err2 := _exc27.Write(ctx, oprot); _write_err26 == nil && err2 != nil {
      _write_err26 = thrift.WrapTException(err2)
    }
    if err2 := oprot.WriteMessageEnd(ctx); _write_err26 == nil && err2 != nil {
      _write_err26 = thrift.WrapTException(err2)
    }
    if err2 := oprot.Flush(ctx); _write_err26 == nil && err2 != nil {
      _write_err26 = thrift.WrapTException(err2)
    }
    if _write_err26 != nil {
      return false, thrift.WrapTException(_write_err26)
    }
    return true, err
  } else {
    result.Success = retval
  }
  tickerCancel()
  if err2 := oprot.WriteMessageBegin(ctx, "authorize_connect", thrift.REPLY, seqId); err2 != nil {
    _write_err26 = thrift.WrapTException(err2)
  }
  if err2 := result.Write(ctx, oprot); _write_err26 == nil && err2 != nil {
    _write_err26 = thrift.WrapTException(err2)
  }
  if err2 := oprot.WriteMessageEnd(ctx); _write_err26 == nil && err2 != nil {
    _write_err26 = thrift.WrapTException(err2)
  }
  if err2 := oprot.Flush(ctx); _write_err26 == nil && err2 != nil {
    _write_err26 = thrift.WrapTException(err2)
  }
  if _write_err26 != nil {
    return false, thrift.WrapTException(_write_err26)
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

type VisaServiceHelloArgs struct {
}

func NewVisaServiceHelloArgs() *VisaServiceHelloArgs {
  return &VisaServiceHelloArgs{}
}

func (p *VisaServiceHelloArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    if err := iprot.Skip(ctx, fieldTypeId); err != nil {
      return err
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *VisaServiceHelloArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "hello_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VisaServiceHelloArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VisaServiceHelloArgs(%+v)", *p)
}

func (p *VisaServiceHelloArgs) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.VisaServiceHelloArgs",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VisaServiceHelloArgs)(nil)

// Attributes:
//  - Success
type VisaServiceHelloResult struct {
  Success *VSChallenge `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewVisaServiceHelloResult() *VisaServiceHelloResult {
  return &VisaServiceHelloResult{}
}

var VisaServiceHelloResult_Success_DEFAULT *VSChallenge
func (p *VisaServiceHelloResult) GetSuccess() *VSChallenge {
  if !p.IsSetSuccess() {
    return VisaServiceHelloResult_Success_DEFAULT
  }
  return p.Success
}
func (p *VisaServiceHelloResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *VisaServiceHelloResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField0(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *VisaServiceHelloResult)  ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
  p.Success = &VSChallenge{}
  if err := p.Success.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *VisaServiceHelloResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "hello_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VisaServiceHelloResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(ctx, oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *VisaServiceHelloResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VisaServiceHelloResult(%+v)", *p)
}

func (p *VisaServiceHelloResult) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.VisaServiceHelloResult",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VisaServiceHelloResult)(nil)

// Attributes:
//  - Challenge
//  - Timestamp
//  - NodeCert
//  - Hmac
//  - NodeAgent
type VisaServiceAuthenticateArgs struct {
  Challenge *VSChallenge `thrift:"challenge,1" db:"challenge" json:"challenge"`
  Timestamp int64 `thrift:"timestamp,2" db:"timestamp" json:"timestamp"`
  NodeCert []byte `thrift:"node_cert,3" db:"node_cert" json:"node_cert"`
  Hmac []byte `thrift:"hmac,4" db:"hmac" json:"hmac"`
  NodeAgent *Agent `thrift:"node_agent,5" db:"node_agent" json:"node_agent"`
}

func NewVisaServiceAuthenticateArgs() *VisaServiceAuthenticateArgs {
  return &VisaServiceAuthenticateArgs{}
}

var VisaServiceAuthenticateArgs_Challenge_DEFAULT *VSChallenge
func (p *VisaServiceAuthenticateArgs) GetChallenge() *VSChallenge {
  if !p.IsSetChallenge() {
    return VisaServiceAuthenticateArgs_Challenge_DEFAULT
  }
  return p.Challenge
}

func (p *VisaServiceAuthenticateArgs) GetTimestamp() int64 {
  return p.Timestamp
}

func (p *VisaServiceAuthenticateArgs) GetNodeCert() []byte {
  return p.NodeCert
}

func (p *VisaServiceAuthenticateArgs) GetHmac() []byte {
  return p.Hmac
}
var VisaServiceAuthenticateArgs_NodeAgent_DEFAULT *Agent
func (p *VisaServiceAuthenticateArgs) GetNodeAgent() *Agent {
  if !p.IsSetNodeAgent() {
    return VisaServiceAuthenticateArgs_NodeAgent_DEFAULT
  }
  return p.NodeAgent
}
func (p *VisaServiceAuthenticateArgs) IsSetChallenge() bool {
  return p.Challenge != nil
}

func (p *VisaServiceAuthenticateArgs) IsSetNodeAgent() bool {
  return p.NodeAgent != nil
}

func (p *VisaServiceAuthenticateArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField3(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField4(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 5:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField5(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *VisaServiceAuthenticateArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Challenge = &VSChallenge{}
  if err := p.Challenge.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Challenge), err)
  }
  return nil
}

func (p *VisaServiceAuthenticateArgs)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Timestamp = v
}
  return nil
}

func (p *VisaServiceAuthenticateArgs)  ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.NodeCert = v
}
  return nil
}

func (p *VisaServiceAuthenticateArgs)  ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.Hmac = v
}
  return nil
}

func (p *VisaServiceAuthenticateArgs)  ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
  p.NodeAgent = &Agent{}
  if err := p.NodeAgent.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.NodeAgent), err)
  }
  return nil
}

func (p *VisaServiceAuthenticateArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "authenticate_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField3(ctx, oprot); err != nil { return err }
    if err := p.writeField4(ctx, oprot); err != nil { return err }
    if err := p.writeField5(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VisaServiceAuthenticateArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "challenge", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:challenge: ", p), err) }
  if err := p.Challenge.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Challenge), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:challenge: ", p), err) }
  return err
}

func (p *VisaServiceAuthenticateArgs) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "timestamp", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:timestamp: ", p), err) }
  if err := oprot.WriteI64(ctx, int64(p.Timestamp)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.timestamp (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:timestamp: ", p), err) }
  return err
}

func (p *VisaServiceAuthenticateArgs) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "node_cert", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:node_cert: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.NodeCert); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.node_cert (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:node_cert: ", p), err) }
  return err
}

func (p *VisaServiceAuthenticateArgs) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "hmac", thrift.STRING, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:hmac: ", p), err) }
  if err := oprot.WriteBinary(ctx, p.Hmac); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.hmac (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:hmac: ", p), err) }
  return err
}

func (p *VisaServiceAuthenticateArgs) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "node_agent", thrift.STRUCT, 5); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:node_agent: ", p), err) }
  if err := p.NodeAgent.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.NodeAgent), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 5:node_agent: ", p), err) }
  return err
}

func (p *VisaServiceAuthenticateArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VisaServiceAuthenticateArgs(%+v)", *p)
}

func (p *VisaServiceAuthenticateArgs) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.VisaServiceAuthenticateArgs",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VisaServiceAuthenticateArgs)(nil)

// Attributes:
//  - Success
type VisaServiceAuthenticateResult struct {
  Success *APIKey `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewVisaServiceAuthenticateResult() *VisaServiceAuthenticateResult {
  return &VisaServiceAuthenticateResult{}
}

var VisaServiceAuthenticateResult_Success_DEFAULT APIKey
func (p *VisaServiceAuthenticateResult) GetSuccess() APIKey {
  if !p.IsSetSuccess() {
    return VisaServiceAuthenticateResult_Success_DEFAULT
  }
  return *p.Success
}
func (p *VisaServiceAuthenticateResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *VisaServiceAuthenticateResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField0(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *VisaServiceAuthenticateResult)  ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 0: ", err)
} else {
  temp := APIKey(v)
  p.Success = &temp
}
  return nil
}

func (p *VisaServiceAuthenticateResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "authenticate_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VisaServiceAuthenticateResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRING, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := oprot.WriteString(ctx, string(*p.Success)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.success (0) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *VisaServiceAuthenticateResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VisaServiceAuthenticateResult(%+v)", *p)
}

func (p *VisaServiceAuthenticateResult) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.VisaServiceAuthenticateResult",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VisaServiceAuthenticateResult)(nil)

// Attributes:
//  - Key
type VisaServiceDeRegisterArgs struct {
  Key APIKey `thrift:"key,1" db:"key" json:"key"`
}

func NewVisaServiceDeRegisterArgs() *VisaServiceDeRegisterArgs {
  return &VisaServiceDeRegisterArgs{}
}


func (p *VisaServiceDeRegisterArgs) GetKey() APIKey {
  return p.Key
}
func (p *VisaServiceDeRegisterArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *VisaServiceDeRegisterArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  temp := APIKey(v)
  p.Key = temp
}
  return nil
}

func (p *VisaServiceDeRegisterArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "de_register_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VisaServiceDeRegisterArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "key", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:key: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.Key)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.key (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:key: ", p), err) }
  return err
}

func (p *VisaServiceDeRegisterArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VisaServiceDeRegisterArgs(%+v)", *p)
}

func (p *VisaServiceDeRegisterArgs) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.VisaServiceDeRegisterArgs",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VisaServiceDeRegisterArgs)(nil)

// Attributes:
//  - Key
//  - Request
type VisaServiceAuthorizeConnectArgs struct {
  Key APIKey `thrift:"key,1" db:"key" json:"key"`
  Request *ConnectRequest `thrift:"request,2" db:"request" json:"request"`
}

func NewVisaServiceAuthorizeConnectArgs() *VisaServiceAuthorizeConnectArgs {
  return &VisaServiceAuthorizeConnectArgs{}
}


func (p *VisaServiceAuthorizeConnectArgs) GetKey() APIKey {
  return p.Key
}
var VisaServiceAuthorizeConnectArgs_Request_DEFAULT *ConnectRequest
func (p *VisaServiceAuthorizeConnectArgs) GetRequest() *ConnectRequest {
  if !p.IsSetRequest() {
    return VisaServiceAuthorizeConnectArgs_Request_DEFAULT
  }
  return p.Request
}
func (p *VisaServiceAuthorizeConnectArgs) IsSetRequest() bool {
  return p.Request != nil
}

func (p *VisaServiceAuthorizeConnectArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *VisaServiceAuthorizeConnectArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  temp := APIKey(v)
  p.Key = temp
}
  return nil
}

func (p *VisaServiceAuthorizeConnectArgs)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  p.Request = &ConnectRequest{}
  if err := p.Request.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Request), err)
  }
  return nil
}

func (p *VisaServiceAuthorizeConnectArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "authorize_connect_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VisaServiceAuthorizeConnectArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "key", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:key: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.Key)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.key (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:key: ", p), err) }
  return err
}

func (p *VisaServiceAuthorizeConnectArgs) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "request", thrift.STRUCT, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:request: ", p), err) }
  if err := p.Request.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Request), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:request: ", p), err) }
  return err
}

func (p *VisaServiceAuthorizeConnectArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VisaServiceAuthorizeConnectArgs(%+v)", *p)
}

func (p *VisaServiceAuthorizeConnectArgs) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.VisaServiceAuthorizeConnectArgs",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VisaServiceAuthorizeConnectArgs)(nil)

// Attributes:
//  - Success
type VisaServiceAuthorizeConnectResult struct {
  Success *ConnectResponse `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewVisaServiceAuthorizeConnectResult() *VisaServiceAuthorizeConnectResult {
  return &VisaServiceAuthorizeConnectResult{}
}

var VisaServiceAuthorizeConnectResult_Success_DEFAULT *ConnectResponse
func (p *VisaServiceAuthorizeConnectResult) GetSuccess() *ConnectResponse {
  if !p.IsSetSuccess() {
    return VisaServiceAuthorizeConnectResult_Success_DEFAULT
  }
  return p.Success
}
func (p *VisaServiceAuthorizeConnectResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *VisaServiceAuthorizeConnectResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField0(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *VisaServiceAuthorizeConnectResult)  ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
  p.Success = &ConnectResponse{}
  if err := p.Success.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *VisaServiceAuthorizeConnectResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "authorize_connect_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VisaServiceAuthorizeConnectResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(ctx, oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *VisaServiceAuthorizeConnectResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VisaServiceAuthorizeConnectResult(%+v)", *p)
}

func (p *VisaServiceAuthorizeConnectResult) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*vsapi.VisaServiceAuthorizeConnectResult",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VisaServiceAuthorizeConnectResult)(nil)


