@startuml

|fastpath|

start

:""lookup_peer()"";

if (peer known?) then (yes)
else (no)
    end
endif

:""decrypt()"";

if (decrypt succeeded?) then (yes)
else (no)
    end
endif

:""maybe_capture()""; <<procedure>>

:""decap_zpi()"";

if (parse OK?) then (yes)
else (no)
    end
endif

:parse ""BaseHeader"";

if (parse OK?) then (yes)
else (no)
    end
endif

if (""TransitPacket"") then (yes)
else (no)
    :""dispatch_mgmt_packet()""; <<procedure>>
    detach
endif

:parse ""PerFlowHeader"";

stop

@enduml
