# Example ZPR configuration file for an adapter

[profile]
# Each config must have a unique name
name = "myconf_1"

# Cert that has signed everything
root_ca = "ca-root.pem"

[dock]
host_or_ip = "127.0.0.1"
port = 5000

# noise public key of the dock (node)
noise_public_key = "RWS4DcBgPxTmKmCfjZ0hHn6bmT9WiIZI4Vb4EEZTaGc="

[adapter]
# This is the signed noise public key for this adapter.
noise_certificate = "conf1-noise.crt"

# adapters private key
noise_private_key = "OH0M46qQqz+rfdmwaY2BJVTVsQL6TAY5iHw+Dg7klVk="


