# Example ZPR configuration file for an adapter

[profile]
# Each config must have a unique name
name = "myconf_1"

# And have a copy of the root authority certificate
root_ca = "/path/to/auth.crt"


[dock]
# The node listening dock address
host_or_ip = "a.spacelaser.net"
startup_port = 5000

# node's public noise key
noise_public_key = "ABfny3qb3/RSLJqJAvl0+d8pYAcf9wb9F2Er+sXEEGo="



[adapter]
# RSA credentials for the adapter.  Cert should be signed by authority.
certificate = "/path/to/adapter.crt"
private_key = "/path/to/adapter.key"

