#!/bin/sh

# Git pre-commit hooks. Checks to ensure code is formatted and compiles without warnings
# when a user tries to commit. Can be over-ruled by running git commit with --no-verify

GIT_BASE_DIR=`git rev-parse --show-toplevel`
GIT_PH_DIR="$GIT_BASE_DIR/adapter/ph"
GIT_LIBNODE_DIR="$GIT_BASE_DIR/libnode"

# Check if there are any files in PH that are changed by this commit
if  ! git diff HEAD --cached --quiet --relative="$GIT_PH_DIR"
then
    # Checks to make sure cargo fmt has been run on ph
    cargo fmt --manifest-path "$GIT_PH_DIR/Cargo.toml" --check --quiet

    if [ $? -ne 0 ]
    then
        echo "Please run cargo fmt on ph before committing"
        exit 1
    fi

    # Checks warnings in ph before committing
    cargo rustc --manifest-path "$GIT_PH_DIR/Cargo.toml" --bin ph -- -D warnings > /dev/null 2>&1 #could remove this in order to make warnings show on terminal

    if [ $? -ne 0 ]
    then
        echo "Please clean up warnings in ph binary before committing"
        exit 1
    fi

    # Checks warnings with cargo test in ph before committing
    cargo rustc --tests --manifest-path "$GIT_PH_DIR/Cargo.toml" -- -D warnings > /dev/null 2>&1

    if [ $? -ne 0 ]
    then
        echo "Please clean up warnings with tests in ph before committing"
        exit 1
    fi
fi

# Check if there are any files in libnode that are changed by this commit
if ! git diff HEAD --cached --quiet --relative="$GIT_LIBNODE_DIR"
then
    # Checks warnings in libnode before committing
    cargo rustc --manifest-path "$GIT_LIBNODE_DIR/Cargo.toml" --lib -- -D warnings > /dev/null 2>&1 #could remove this in order to make warnings show on terminal

    if [ $? -ne 0 ]
    then
        echo "Please clean up warnings in libnode before committing"
        exit 1
    fi

    # Checks warnings with cargo test in libnode before committing
    cargo rustc --tests --manifest-path "$GIT_LIBNODE_DIR/Cargo.toml" -- -D warnings > /dev/null 2>&1

    if [ $? -ne 0 ]
    then
        echo "Please clean up warnings with tests in libnode before committing"
        exit 1
    fi
fi
