# node configuration file.

[global]
name = "n0"
ca_file = "ca-cert.pem"
certificate_file = "node-cert.pem"
private_key_file = "node-key.pem"
self_addr = "172.16.1.1:5000"
zpr_addr = [ "fd5a:5052:90de::1" ]

# use `sudo ./mktun.sh` to set this up
tun_if = "tun9"

# TODO: need to set claims (in adapter too)?
#       for node we need:
#
#          "zpr.addr" = "fd5a:5052:90de::1"
#

