# node configuration file.

[global]
name = "n0"
ca_file = "ca-cert.pem"
certificate_file = "node-cert.pem"
private_key_file = "node-key.pem"
self_addr = "127.16.1.1:5000"

# Currently tokio TUN on linux will not set an IPv6 address on a TUN interface.
# So the running of the node needs to first create and then pass in the TUN
# interface name using `--tun-if` on the command line.
tun_if = "MISSING_TUN"

# TODO: need to set claims (in adapter too)?
#       for node we need:
#
#          "zpr.addr" = "fd5a:5052:90de::1"
#
#       Also, how does node set its internal adapter address?

