#!/usr/bin/env bash


# Our PKI helper tool
ZPR_PKI_BIN=$(realpath "$(dirname $0)/lib/zpr-pki")


#
# Functions used in multiple integration tests
#

# Re-exec the calling test script inside an unprivileged user + network
# namespace (unshare -nr).  Inside it we are mapped to root with full
# capabilities over any namespace we create, so none of the ip/tc/tuntap
# plumbing below needs sudo.  Call it right after sourcing this file,
# forwarding the script arguments:
#
#   enter_test_namespace "$@"
function enter_test_namespace() {
  if [ -n "${ZPR_TEST_IN_USERNS:-}" ]
  then
    # Already inside; bring up loopback in the orchestration namespace.
    ip link set lo up
    return 0
  fi

  if ! unshare -nr true 2> /dev/null
  then
    echo "ERROR: cannot create an unprivileged user+network namespace (unshare -nr)." >&2
    echo "On Ubuntu 24.04+ this is usually AppArmor's user-namespace restriction;" >&2
    echo "a one-time admin fix is:" >&2
    echo "  echo kernel.apparmor_restrict_unprivileged_userns=0 | sudo tee /etc/sysctl.d/60-zpr-userns.conf" >&2
    echo "  sudo sysctl --system" >&2
    exit 1
  fi

  export ZPR_TEST_IN_USERNS=1
  exec unshare -nr "$0" "$@"
}

# Each test network namespace is an anonymous netns pinned by a holder
# process; NETNS_PID maps namespace name -> holder pid.  No /run/netns
# entries and no root privileges are involved, and when the holders die the
# namespaces evaporate, so a crashed test cannot leak namespaces into the
# host.
declare -A NETNS_PID

function new_netns() {
  local NAME=$1

  unshare -n sleep infinity &
  local PID=$!

  # Wait until the holder has actually unshared its network namespace;
  # entering it before that would target the orchestration namespace.
  local OUR_NS HOLDER_NS
  OUR_NS=$(readlink "/proc/$$/ns/net")
  for ((i = 0; i < 50; ++i))
  do
    HOLDER_NS=$(readlink "/proc/$PID/ns/net" 2> /dev/null || true)
    if [ -n "$HOLDER_NS" ] && [ "$HOLDER_NS" != "$OUR_NS" ]
    then
      NETNS_PID[$NAME]=$PID
      return 0
    fi
    sleep 0.1
  done

  echo "failed to create network namespace $NAME" >&2
  return 1
}

# Run a command in a test namespace created by new_netns.
# NOTE: unlike `ip netns exec`, this only enters the network namespace and
# does not remount /sys, so read interface state via `ip link`, not
# /sys/class/net.
function in_ns() {
  local NAME=$1
  shift
  nsenter -t "${NETNS_PID[$NAME]}" -n -- "$@"
}

# Create a veth pair in the orchestration namespace and move one end into
# each of two test namespaces.  The test namespaces are freshly created, so
# explicit names cannot collide (the old `ip netns` flow had to rely on
# kernel-autogenerated names to dodge a root-namespace name clash).
function connect_ns() {
  local NS_A=$1 IF_A=$2 NS_B=$3 IF_B=$4

  ip link add "$IF_A" type veth peer name "$IF_B"
  ip link set "$IF_A" netns "${NETNS_PID[$NS_A]}"
  ip link set "$IF_B" netns "${NETNS_PID[$NS_B]}"
}

function prefix_log() {
  SYSNAME=$1
  printf -v PREFIX '%10s' "[$SYSNAME]"
  sed "s/^/$PREFIX /"
}

function wait_for() {
  RETRIES=$1
  shift
  CMD=("$@")

  if "${CMD[@]}"
  then return 0
  else RET=$?
  fi

  for ((i = 0; i < RETRIES; ++i))
  do
    sleep 1

    if "${CMD[@]}"
    then return 0
    else RET=$?
    fi
  done

  return "$RET"
}

function create_network() {
  new_netns zpr-node
  new_netns zpr-vs
  new_netns zpr-a
  new_netns zpr-b
  new_netns zpr-c

  # loopback

  in_ns zpr-node ip link set lo up
  in_ns zpr-vs ip link set lo up
  in_ns zpr-a ip link set lo up
  in_ns zpr-b ip link set lo up
  in_ns zpr-c ip link set lo up

  # virtual Ethernet pairs

  connect_ns zpr-vs veth0 zpr-node veth-zpr-vs
  connect_ns zpr-a veth0 zpr-node veth-zpr-a
  connect_ns zpr-b veth0 zpr-node veth-zpr-b
  connect_ns zpr-c veth0 zpr-node veth-zpr-c

  in_ns zpr-node ip addr add "$NODE_SUBSTRATE_ADDR_VS" peer "$VS_SUBSTRATE_ADDR" dev veth-zpr-vs
  in_ns zpr-node ip addr add "$NODE_SUBSTRATE_ADDR_A" peer "$A_SUBSTRATE_ADDR" dev veth-zpr-a
  in_ns zpr-node ip addr add "$NODE_SUBSTRATE_ADDR_B" peer "$B_SUBSTRATE_ADDR" dev veth-zpr-b
  in_ns zpr-node ip addr add "$NODE_SUBSTRATE_ADDR_C/24" dev veth-zpr-c
  if [ -n "${NODE_SUBSTRATE_ADDR_C_ALT-}" ]
  then in_ns zpr-node ip addr add "$NODE_SUBSTRATE_ADDR_C_ALT/24" dev veth-zpr-c  # Used for testing routing.
  fi
  in_ns zpr-vs ip addr add "$VS_SUBSTRATE_ADDR" peer "$NODE_SUBSTRATE_ADDR_VS" dev veth0
  in_ns zpr-a ip addr add "$A_SUBSTRATE_ADDR" peer "$NODE_SUBSTRATE_ADDR_A" dev veth0
  in_ns zpr-b ip addr add "$B_SUBSTRATE_ADDR" peer "$NODE_SUBSTRATE_ADDR_B" dev veth0
  in_ns zpr-c ip addr add "$C_SUBSTRATE_ADDR/24" dev veth0

  in_ns zpr-node ip link set veth-zpr-vs up
  in_ns zpr-node ip link set veth-zpr-a up
  in_ns zpr-node ip link set veth-zpr-b up
  in_ns zpr-node ip link set veth-zpr-c up
  in_ns zpr-vs ip link set veth0 up
  in_ns zpr-a ip link set veth0 up
  in_ns zpr-b ip link set veth0 up
  in_ns zpr-c ip link set veth0 up

  # TUN devices.  No `user` option: everything runs as the namespace's
  # mapped root, which holds CAP_NET_ADMIN over these devices anyway.

  in_ns zpr-node ip tuntap add name tun0 mode tun multi_queue
  in_ns zpr-vs ip tuntap add name tun0 mode tun multi_queue
  in_ns zpr-a ip tuntap add name tun0 mode tun multi_queue
  in_ns zpr-b ip tuntap add name tun0 mode tun multi_queue
  in_ns zpr-c ip tuntap add name tun0 mode tun multi_queue

  in_ns zpr-node ip link set tun0 up
  in_ns zpr-vs ip link set tun0 up
  in_ns zpr-a ip link set tun0 up
  in_ns zpr-b ip link set tun0 up
  in_ns zpr-c ip link set tun0 up

  # Kernel bug: kernels older than 6.10 don't set peer route correctly
  # when interface is down.  I think <https://github.com/torvalds/linux/commit/d0098e4c6b83e502cc1cd96d67ca86bc79a6c559>
  # fixes this issue.  For now, add the addresses after we bring the link up.
  in_ns zpr-node ip addr add "$NODE_ZPR_ADDR" peer "$VS_ZPR_ADDR" dev tun0
  in_ns zpr-vs ip addr add "$VS_ZPR_ADDR" peer "$NODE_ZPR_ADDR" dev tun0
  in_ns zpr-a ip addr add "$A_ZPR_ADDR" peer "$ZPR_SUBNET" dev tun0
  in_ns zpr-b ip addr add "$B_ZPR_ADDR" peer "$ZPR_SUBNET" dev tun0
  in_ns zpr-c ip addr add "$C_ZPR_ADDR" peer "$ZPR_SUBNET" dev tun0
}

function configure_netem() {
  echo "Configuring netem $@" > /dev/stderr
  for NIC in vs a b c
  do
    in_ns zpr-node tc qdisc add dev veth-zpr-"$NIC" root netem "$@"
  done
}

function destroy_network() {
  # The namespaces are anonymous, pinned only by their holder processes;
  # killing the holders destroys them.
  local NAME
  for NAME in "${!NETNS_PID[@]}"
  do
    kill "${NETNS_PID[$NAME]}" 2> /dev/null || true
  done
  NETNS_PID=()
}

function create_ca_key_and_cert() {
  CA_NAME=$1
  # We can't do this properly until we pull in the policy compiler
  # So just use the pair set up in the examples directory for now
  cp "$PREGEN/ca-key.pem" "$CA_NAME.key"
  cp "$PREGEN/ca-cert.pem" "$CA_NAME.crt"
  #"$ZPR_PKI_BIN" gencakey >"$CA_NAME.key"
  #"$ZPR_PKI_BIN" gencacert /CN="$CA_NAME" 1 <"$CA_NAME.key" >"$CA_NAME.crt"
  #openssl genrsa -out "$CA_NAME.key"
  #openssl x509 -new -subj /CN="$CA_NAME" -key "$CA_NAME.key" -extfile /etc/ssl/openssl.cnf -extensions v3_ca -days 1 -out "$CA_NAME.crt"
}

function create_actor_key_and_cert() {
  CA_NAME=$1
  ACTOR_NAME=$2
  "$ZPR_PKI_BIN" genkey >"$ACTOR_NAME.key"
  "$ZPR_PKI_BIN" pubkey <"$ACTOR_NAME.key" >"$ACTOR_NAME.pubkey"
  "$ZPR_PKI_BIN" gensignedcert "$CA_NAME.crt" "$CA_NAME.key" /CN="$ACTOR_NAME" 1 <"$ACTOR_NAME.pubkey" >"$ACTOR_NAME.crt"
  
  #openssl genrsa -out "$ACTOR_NAME.key"
  #openssl req -new -subj /CN="$ACTOR_NAME" -key "$ACTOR_NAME.key" -config /etc/ssl/openssl.cnf -reqexts v3_req -out "$ACTOR_NAME.csr" 2> /dev/null
  #openssl x509 -req -CA "$CA_NAME.crt" -CAkey "$CA_NAME.key" -copy_extensions copyall -days 1 -in "$ACTOR_NAME.csr" -out "$ACTOR_NAME.crt" 2> /dev/null
}

function emit_vs_config() {
  # Args retained for backward compatibility with existing callers.
  CA_NAME=$1
  VS_ACTOR_NAME=$2
  cat <<EOF
[core]
admin_cert = "$(realpath "$PREGEN/zpr-rsa-cert.pem")"
admin_key = "$(realpath "$PREGEN/zpr-rsa-key.pem")"
vk_uri = "redis://127.0.0.1:6379"
EOF
}

function check_vs_valkey_port() {
  in_ns zpr-vs bash -lc 'exec 3<>/dev/tcp/127.0.0.1/6379'
}

function ping_test() {
  RESULT=0

  in_ns zpr-node ping -q -c 5 -w 5 "$VS_ZPR_ADDR" & wait -f $!; let RESULT="RESULT||$?"
  in_ns zpr-vs ping -q -c 5 -w 5 "$NODE_ZPR_ADDR" & wait -f $!; let RESULT="RESULT||$?"
  in_ns zpr-a ping -q -c 5 -w 5 "$B_ZPR_ADDR" & wait -f $!; let RESULT="RESULT||$?"
  in_ns zpr-b ping -q -c 5 -w 5 "$A_ZPR_ADDR" & wait -f $!; let RESULT="RESULT||$?"

  if [[ "$NUM_ACTORS" -ge 3 ]]; then
    in_ns zpr-a ping -q -c 5 -w 5 "$C_ZPR_ADDR" & wait -f $!; let RESULT="RESULT||$?"
    in_ns zpr-b ping -q -c 5 -w 5 "$C_ZPR_ADDR" & wait -f $!; let RESULT="RESULT||$?"
    in_ns zpr-c ping -q -c 5 -w 5 "$A_ZPR_ADDR" & wait -f $!; let RESULT="RESULT||$?"
    in_ns zpr-c ping -q -c 5 -w 5 "$B_ZPR_ADDR" & wait -f $!; let RESULT="RESULT||$?"
  fi

  return "$RESULT"
}

function check_carrier() {
  NETNS=$1
  IF=$2

  # `nsenter -n` does not remount /sys (unlike `ip netns exec`), so
  # /sys/class/net would show the wrong namespace; ask ip(8) instead.
  in_ns "$NETNS" ip link show dev "$IF" | grep -q LOWER_UP
}

# Visible sleep for n seconds.  Takes one arg: number of seconds.
function countdown() {
    count=$1
    (( ++count ))
    while (( --count > 0 )); do
        echo -n "$count...   "
        sleep 1
    done
    echo
}

# Get all descendant PIDs whose name matches a specific list
function get_descendants() {
    exenames="(ph|node|adapter|vservice|vs|valkey-server)"
    regex="$exenames\(([0-9]+)\)"
    echo $(pstree -pT "$$" | egrep -o "$regex" | sed -E "s/$regex/\2/")
}

# Takes one arg- filepath relative to TMPDIR
function emitlog() {
    echo -e "\n\n==== $1 ====\n"
    if [ -e "$TMPDIR/$1" ]
        then
            cat "$TMPDIR/$1"
        else
            echo "(MISSING)"
    fi
}


function cleanup() {
  # Kill the known test processes (ph/vs/valkey and the netns holders) first:
  # `jobs -p` only yields each pipeline's leader, and killing that leaves the
  # actual daemons running with the `tee`s still holding their pipes, which
  # would make the `wait -f` below hang until the CI job times out whenever a
  # test aborts mid-run.
  for pid in $(get_descendants)
  do kill -9 "$pid" 2> /dev/null || true
  done

  for child in $(jobs -p)
  do kill -9 "$child" 2> /dev/null || true
  done

  wait -f

  destroy_network || true

  SHOW_LOGS="${ZPR_TEST_VERBOSE:-no}"

  if [ "$SHOW_LOGS" != "no" ]
     then
         emitlog "node.log"
         emitlog "vs.log"
         emitlog "adapter1.log"
         emitlog "adapter2.log"
         emitlog "adapter3.log"
  fi

  popd > /dev/null
  rm -r "$TMPDIR" || true
}
