name: Rust-adapter

on:
  push:
    branches: [ "main" ]
    paths:
      - 'adapter/ph/**'
      - 'adapter/cli/**'
      - 'zpr-ext/**'
      - 'cslab/**'
      - 'cbpf-rs/**'
      - 'libnode/**'
      - 'integration-test/**'
      - '.github/workflows/adapter.yml'
  pull_request:
    paths:
      - 'adapter/ph/**'
      - 'adapter/cli/**'
      - 'zpr-ext/**'
      - 'cslab/**'
      - 'cbpf-rs/**'
      - 'libnode/**'
      - 'integration-test/**'
      - '.github/workflows/adapter.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  VISA_SERVICE_RELEASE: v0.6.0

jobs:
  # Build and upload ph
  build-ph:
    name: PH
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-build-test.yml@b9b1a41fe4fdee44c4970cc473b79c266bdf89f5
    with:
      name: 'ph'
      path: './adapter/ph'
      package: true
    secrets: inherit

  # Build and upload ph-cli
  build-ph-cli:
    name: PH CLI
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-build-test.yml@b9b1a41fe4fdee44c4970cc473b79c266bdf89f5
    with:
      name: 'ph-cli'
      path: './adapter/cli'
      package: true
      runs-on: "['ubuntu-latest']"
      needs-libpcap: true
    secrets: inherit

  # Test ph, check for warnings, and check formatting
  test-ph:
    name: PH
    needs: [build-ph]
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-test.yml@b9b1a41fe4fdee44c4970cc473b79c266bdf89f5
    with:
      name: 'ph'
      path: './adapter/ph'
    secrets: inherit

  # Test ph-cli, check for warnings, and check formatting
  test-ph-cli:
    name: PH CLI
    needs: [build-ph-cli]
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-test.yml@b9b1a41fe4fdee44c4970cc473b79c266bdf89f5
    with:
      name: 'ph-cli'
      path: './adapter/cli'
      runs-on: "['ubuntu-latest']"
      needs-libpcap: true
    secrets: inherit

  # Integration tests
  basic-integration-test:
    name: Run 1-Node Test (v6)
    needs: [build-ph, build-ph-cli]
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
    # Necessary to run before rust-cache
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
      with:
        workspaces: |
          adapter/ph
          adapter/cli
          zpr-ext
          cslab
          cbpf-rs

    # see <https://github.com/docker-library/golang/issues/452>
    - name: Set workspace as safe
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Setup Git credentials
      timeout-minutes: 1
      run: |
        echo 'echo $ZPR_CICD_RO_TOKEN' > "$HOME/.git-askpass"
        chmod +x "$HOME/.git-askpass"
        echo "GIT_ASKPASS=$HOME/.git-askpass" >> "$GITHUB_ENV"
        go env -w GOPRIVATE="github.com/org-zpr/*"

    - uses: actions/download-artifact@v5
      with:
        pattern: ph-*${{ matrix.os }}
        merge-multiple: true

    - name: Build
      timeout-minutes: 10
      env:
        ZPR_CICD_RO_TOKEN: ${{ secrets.ZPR_CICD_RO_TOKEN }}
      run: |
        tar -xvf ph.tar
        tar -xvf ph-cli.tar

    - name: Download Asset
      uses: robinraju/release-downloader@v1
      with:
        repository: 'org-zpr/zpr-visaservice'
        tag: ${{ env.VISA_SERVICE_RELEASE }}
        fileName: 'release-linux-x86_64.tar.gz'
        extract: true
        out-file-path: 'integration-test'
        token: ${{ secrets.ZPR_CICD_RO_TOKEN }}

    - name: One Node v6 Test
      timeout-minutes: 10
      run: |
        ZPR_TEST_VERBOSE=1 integration-test/one-node-v6-test.sh

  capture-integration-test:
    name: Run Capture Test
    needs: [build-ph, build-ph-cli]
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
    # Necessary to run before rust-cache
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
      with:
        workspaces: |
          adapter/ph
          adapter/cli
          zpr-ext
          cslab
          cbpf-rs

    # see <https://github.com/docker-library/golang/issues/452>
    - name: Set workspace as safe
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Setup Git credentials
      timeout-minutes: 1
      run: |
        echo 'echo $ZPR_CICD_RO_TOKEN' > "$HOME/.git-askpass"
        chmod +x "$HOME/.git-askpass"
        echo "GIT_ASKPASS=$HOME/.git-askpass" >> "$GITHUB_ENV"
        go env -w GOPRIVATE="github.com/org-zpr/*"

    - uses: actions/download-artifact@v5
      with:
        pattern: ph-*${{ matrix.os }}
        merge-multiple: true

    - name: Build
      timeout-minutes: 10
      env:
        ZPR_CICD_RO_TOKEN: ${{ secrets.ZPR_CICD_RO_TOKEN }}
      run: |
        tar -xvf ph.tar
        tar -xvf ph-cli.tar  

    - name: Download Asset
      uses: robinraju/release-downloader@v1
      with:
        repository: 'org-zpr/zpr-visaservice'
        tag: ${{ env.VISA_SERVICE_RELEASE }}
        fileName: 'release-linux-x86_64.tar.gz'
        extract: true
        out-file-path: 'integration-test'
        token: ${{ secrets.ZPR_CICD_RO_TOKEN }}


    - name: Capture Test
      timeout-minutes: 10
      run: |
        ZPR_TEST_VERBOSE=1 integration-test/capture-test.sh
