name: Rust-cslab

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cslab/**'
      - '.github/workflows/cslab.yml'
  pull_request:
    paths:
      - 'cslab/**'
      - '.github/workflows/cslab.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  cslab-build:
    name: Cslab
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-build-test.yml@7b12954f051d0ebac6f726a8ba94730d0e1b0c94
    with:
      name: 'Cslab'
      path: './cslab'
    secrets: inherit
