name: Go-adapter

on:
  push
  pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  cactl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build + test cactl
      run: cd adapter/cactl && make build && make test
