# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-visaservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - visaservice/mods/**
      - visaservice/core/**
      - visaservice/thrift/**

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: install build deps
      run: sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libboost-filesystem-dev libboost-thread-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev

    - name: install thrift
      run: |
        wget https://dlcdn.apache.org/thrift/0.21.0/thrift-0.21.0.tar.gz
        tar -xvf thrift-0.21.0.tar.gz
        cd thrift-0.21.0
        ./bootstrap.sh
        ./configure --with-go --with-rs --without-python --without-py3 --without-swift --without-php --without-kotlin --without-java --disable-dependency-tracking
        make
        sudo make install

    - name: Build
      run: |
        cd visaservice
        make all-go

    - name: Test
      run: |
        cd visaservice
        make test-go
