name: Rust-node

on:
  push:
    branches: [ "main" ]
    paths:
      - 'libnode/**'
      - '.github/workflows/libnode.yml'
  pull_request:
    paths:
      - 'libnode/**'
      - '.github/workflows/libnode.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  libnode-build:
    name: Libnode
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-containerized-build-test.yml@v1.1
    with:
      name: Libnode
      path: ./libnode
    secrets: inherit
