name: Rust-node

on:
  push:
    branches: [ "main" ]
    paths:
      - 'libnode2/**'
      - '.github/workflows/libnode.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'libnode2/**'
      - '.github/workflows/libnode.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  libnode-build:
    name: Libnode
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-containerized-build-test.yml@v1.4
    with:
      name: Libnode
      path: ./libnode2
      features: build-lnt
    secrets: inherit
