name: Rust-cslab

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - 'cslab/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  cslab-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build + test cbpf
      run: |
        cd cslab
        cargo build --verbose
        cargo test --verbose

  cslab-format:
    needs: [cslab-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check format
      run: |
        cd cslab
        cargo fmt --check

  cslab-warnings:
    needs: [cslab-build]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Check warnings
      run: |
        cd cslab
        cargo rustc -- -D warnings

  cslab-test-warnings:
    needs: [cslab-build]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Check test warnings
      run: |
        cd cslab
        cargo rustc --tests -- -D warnings
