name: Rust-visaservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - 'visaservice/cli/**'
      - 'visaservice/thrift/**'
      - '.github/workflows/rust-visaservice.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/org-zpr/38f3bb925e5e:latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Rust
      timeout-minutes: 5
      run: rustup default stable

    - name: Build
      timeout-minutes: 5
      run: |
        cd visaservice
        make all-rs

    - name: Test
      timeout-minutes: 5
      run: |
        cd visaservice
        make test-rs

