name: Rust-adapter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build + test cd
      run: cd adapter/cd && make build && make test

  ph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build + test ph
      run: cd adapter/ph && make build && make test

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check format
      run: cd adapter/ph && cargo fmt --check

  warnings:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Check warnings
      run: cd adapter/ph && cargo rustc -- -D warnings

  test-warnings:
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v4
      - name: Check test warnings
        run: cd adapter/ph && cargo rustc --tests -- -D warnings > /dev/null 2>&1
