name: Rust-cbpfrs

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - cbpf-rs/**

env:
  CARGO_TERM_COLOR: always

jobs:
  cbpf-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build + test cbpf
      run: |
        sudo apt update
        sudo apt install libpcap-dev
        cd cbpf-rs && cargo build --verbose
        cargo test --verbose

  cbpf-format:
    needs: [cbpf-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check format
      run: |
        cd cbpf-rs
        cargo fmt --check

  cbpf-warnings:
    needs: [cbpf-build]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Check warnings
      run: |
        cd cbpf-rs
        cargo rustc -- -D warnings

  cbpf-test-warnings:
    needs: [cbpf-build]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Check test warnings
      run: |
        sudo apt update
        sudo apt install libpcap-dev
        cd cbpf-rs && cargo rustc --tests -- -D warnings
