name: Rust-cslab

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - 'cslab/**'
      - '.github/workflows/rust-cslab.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  cslab-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Build + test cbpf
      timeout-minutes: 5
      run: |
        cd cslab
        cargo build --verbose
        cargo test --verbose

  cslab-format:
    needs: [cslab-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Check format
      timeout-minutes: 5
      run: |
        cd cslab
        cargo fmt --check

  cslab-warnings:
    needs: [cslab-build]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Check warnings
      timeout-minutes: 5
      run: |
        cd cslab
        cargo rustc -- -D warnings

  cslab-test-warnings:
    needs: [cslab-build]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Check test warnings
      timeout-minutes: 5
      run: |
        cd cslab
        cargo rustc --tests -- -D warnings
