name: Rust-cbpfrs

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  cbpf-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build + test cbpf
      run: cd cbpf-rs && cargo build --verbose && cargo test --verbose

  cbpf-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check format
      run: cd cbpf-rs && cargo fmt --check

  cbpf-warnings:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Check warnings
      run: cd cbpf-rs && cargo rustc -- -D warnings

  cbpf-test-warnings:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Check test warnings
      run: cd cbpf-rs && cargo rustc --tests -- -D warnings
