name: Rust-node

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths: 
      - node/**
      - visaservice/thrift/**
      - adapter/ph/**
      - zpr-ext/**
      - cslab/**
      - cbpf-rs/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/install-thrift-rs.yml
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        cd node && make all

    - name: Run tests
      run: |
        cd node && make test

