name: Rust-cbpfrs

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - 'cbpf-rs/**'
      - '.github/workflows/rust-cbpfrs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  cbpf-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cbpf-rs
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Install dependencies
      timeout-minutes: 5
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
        sudo apt install libpcap-dev

    - name: Build cbpf
      id: build
      timeout-minutes: 5
      run: cargo build --verbose

    - name: Test cbpf
      if: ${{ ! cancelled() && steps.build.outcome == 'success' }}
      timeout-minutes: 5
      run: cargo test --verbose

    - name: Check format
      if: ${{ ! cancelled() }}
      timeout-minutes: 1
      run: cargo fmt --check

    - name: Check warnings
      if: ${{ ! cancelled() && steps.build.outcome == 'success' }}
      timeout-minutes: 5
      run: cargo rustc -- -D warnings

    - name: Check test warnings
      if: ${{ ! cancelled() && steps.build.outcome == 'success' }}
      timeout-minutes: 5
      run: cargo rustc --tests -- -D warnings
