name: Rust-visaservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - visaservice/cli/**
      - visaservice/thrift/**
      
env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cd visaservice
        make all-rs

    - name: Test
      run: |
        cd visaservice
        make test-rs

