name: Rust-visaservice

on:
  push:
    branches: [ "main" ]
    paths:
      - 'libnode/**'
      - 'visaservice/vs-client/**'
      - 'visaservice/vs-admin/**'
      - '.github/workflows/vs-tools.yml'
  pull_request:
    paths:
      - 'libnode/**'
      - 'visaservice/vs-client/**'
      - 'visaservice/vs-admin/**'
      - '.github/workflows/vs-tools.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-vs:
    name: ${{ matrix.target }}
    strategy:
      matrix:
        target: [vs-client, vs-admin]
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-containerized-build-test.yml@18db4a3e7ba9852e3cd4a330843742bd93406c48
    with:
      name: ${{ matrix.target }}
      path: ./visaservice/${{ matrix.target }}
    secrets: inherit
