name: Rust-zprext

on:
  push:
    branches: [ "main" ]
    paths:
      - 'zpr-ext/**'
      - '.github/workflows/zprext.yml'
  pull_request:
    paths:
      - 'zpr-ext/**'
      - '.github/workflows/zprext.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  zpr-ext:
    name: ZPR Ext
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-build-test.yml@c4bf03c27fc14ac08cdb1b8a8c49de91f21786a7
    with:
      name: 'ZPR-Ext'
      path: './zpr-ext'
    secrets: inherit
